site_name: AI绘画核心技术与实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - AI绘画核心技术与实战.md
  
   - 开篇词-AI技术爆发，如何实现绘画模型自由？.md
  
   - 先导篇-先睹为快，AI绘画作品集.md
  
   - 01-WebUI：免费AI绘画工具箱的N大绘图功能.md
  
   - 02-Prompt使用技巧：如何更精准地控制绘画风格和内容？.md
  
   - 03-进阶应用：图生图技巧与创作社区初探.md
  
   - 04-实战项目（一）：用LoRA制作一个你自己的漫画故事.md
  
   - 05- 旧画师GAN：天生有缺陷还是学艺不精湛？.md
  
   - 06 - 颠覆者扩散模型：直观去理解加噪与去噪.md
  
   - 07-AIGC的核心魔法：搞懂Transformer.md
  
   - 08-巧用神经网络：如何用UNet预测噪声.md
  
   - 09-采样器：龟兔赛跑，如何选择更好更快的采样器？.md
  
   - 10-CLIP：让AI绘画模型乖乖听你的话.md
  
   - 11-VAE系列：如何压缩图像给GPU腾腾地方.md
  
   - 12-实战项目（二）：动手训练一个你自己的扩散模型.md
  
   - 答疑课堂1-热点问题答疑&前两章思考题答案.md
  
   - 13-前浪DALL-E 2：帮你魔改经典画作.md
  
   - 14-挑战者Imagen：为什么会后来居上？.md
  
   - 15-显微镜下的Stable Diffusion（一）：惊艳效果下的关键技术揭秘.md
  
   - 16-显微镜下的Stable Diffusion（二）：从图像变体到神雕侠侣（SDXL）.md
  
   - 17-巅峰画师Midjourney：一起来猜猜年入1亿美元背后的技术方案.md
  
   - 18-DreamBooth和LoRA：低成本实现IP专属的AI绘画模型.md
  
   - 19- 实战项目（三）：动手做一个自己的LoRA模型.md
  
   - 20-ControlNet：出道即巅峰，构图控制没有对手.md
  
   - 21- 实战项目（四）：用ControlNet给你的创意上色.md
  
   - 22-AI图像编辑：如何用Prompt2Prompt实现“言出法随”.md
  
   - 23-实战项目（五）：做一个类似LensaAI的梦幻照相馆.md
  
   - 24-实战项目（六）：妙用SD，如何给你的照片带上千百种风格？.md
  
   - 25-视频-3D-数字人：探索AI绘画的N种可能.md
  
   - 答疑课堂2-热点问题答疑&第三、四章思考题答案.md
  
   - 用户故事-潇然：持续充电，拥抱未来！.md
  
   - 26-DALL-E 3技术探秘（一）：用OpenAI的方式搞数据.md
  
   - 27-DALL-E 3技术探秘（二）：从unCLIP到缝合怪方案.md
  
   - 直播回放-AI绘画发展脉络与LoRA模型训练实战.md
  
   - 直播回放-畅谈 AIGC，从 AI 绘画到 GPT-4 Vision.md
  
   - 结束语-未来可期，一起拥抱AI绘画的新时代.md
  
   - 结课测试-来赴一场满分之约！.md
  