site_name: 互联网人的英语私教课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 互联网人的英语私教课.md
  
   - 开篇词 - 把技能当知识，是学英语最大的坑.md
  
   - 学习指南 - 我想和你交代下这门课的设计思路.md
  
   - 01-导读：背景知识对于理解文章究竟有多重要？.md
  
   - 02 - 什么时候适合用“词根词缀法”来背单词？.md
  
   - 03-到底要不要学语法？什么时候学比较好？.md
  
   - 每周一起背10句 - week 01.md
  
   - 04 - 从那些不规范的表达中，我们可以学到什么？.md
  
   - 05-tradeoff 还是 trade-off？用连字符到底对不对？.md
  
   - 06-小心那些平淡无奇、人畜无害的简单小词！.md
  
   - 每周一起背10句 - week 02.md
  
   - 07-为什么虚拟语气一看就懂、一用就忘？.md
  
   - 08-带你一次性搞懂非限定性和限定性定语从句.md
  
   - 09 - 导读：通过阅读序言段了解文章的背景知识.md
  
   - 每周一起背10句 - week 03.md
  
   - 10-一切始于“主干”，万变不离其宗.md
  
   - 11-并列句 = 简单句 + 并列连词 + 简单句.md
  
   - 12 - 谓语动词永远是英语句子的核心.md
  
   - 每周一起背10句 - week 04.md
  
   - 13 - 导读：如何逐渐培养阅读习惯，快速抓住文章大意？.md
  
   - 14-为什么介词如此“烦人”？.md
  
   - 15-同位语的两个重要作用.md
  
   - 每周一起背10句 - week 05.md
  
   - 16-动词：英语宇宙的中心.md
  
   - 17-参透“主从分明”的树状结构，即可“庖丁解牛”.md
  
   - 18-全篇通读（上）：从读懂一句话慢慢转向读懂一篇文章.md
  
   - 每周一起背10句 - week 06.md
  
   - 19-全篇通读（下）：不是所有的文章和书籍都值得读完.md
  
   - 20-英语词汇学习的唯一有效途径：阅读、阅读、阅读.md
  
   - 21-你和所有见过的单词或短语都只是加了“好友”而已.md
  
   - 每周一起背10句 - week 07.md
  
   - 22-paraphrase：跨越阅读和写作两项技能的练习法.md
  
   - 23-练习paraphrase的最终目的，是有一天可以不再需要它.md
  
   - 24-如何用“金字塔原理”来练习阅读和写作？.md
  
   - 每周一起背10句 - week 08.md
  
   - 25-如何利用“30秒电梯原则”写出言简意赅的读书总结？.md
  
   - 26 - 阅读准备：当我们谈论快速阅读时，我们究竟在谈论什么？.md
  
   - 27 - 行业预测类文章，动词就是它的全部.md
  
   - 每周一起背10句 - week 09.md
  
   - 28 - 没有经过相关专业训练，如何自学新的专业知识？.md
  
   - 29 - 如何通过定期的主题阅读计划，个性化定制专属的语料库？.md
  
   - 30 - 突破实用型、技术类阅读，外面还有另一片星辰大海.md
  
   - 开学直播回顾 - 程序员如何阅读英语资料？.md
  
   - 结束语 - 学英语也是修行.md
  
   - 用户故事 - 张理查：作为软件工程师，我怎么学习英语专栏？.md
  