site_name: 技术领导力实战笔记

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 技术领导力实战笔记.md
  
   - 开篇词 - 卓越的团队，必然有一个卓越的领导者.md
  
   - 第1讲 - 你的能力模型决定你的职位.md
  
   - 第2讲 - 七位CTO纵论技术领导者核心能力.md
  
   - 第3讲 - CEO实话实说：我需要这样的CTO.md
  
   - 第4讲 - 技术领导者不等于技术管理者.md
  
   - 大咖对话 - 从几个工程师到2000+个工程师的技术团队成长秘诀.md
  
   - 第5讲 - CTO的三重境界.md
  
   - 第6讲 - 像CEO一样思考.md
  
   - 第7讲 - 要制定技术战略，先看清局面.md
  
   - 第8讲 - 技术领导力就是“成事”的能力.md
  
   - 大咖对话 - 未来技术负责人与首席增长官将如何协作？.md
  
   - 第9讲 - CTO是商业思维和技术思维交汇的那个点.md
  
   - 第10讲 - 创业公司CTO的认知升级.md
  
   - 第11讲 - 最合适的技术才是最有价值的技术.md
  
   - 第12讲 - 谈谈CTO在商业战略中的定位.md
  
   - 大咖问答 - 打造自己的个人品牌，你也可以.md
  
   - 第13讲 - 把脉高效执行的关键要素.md
  
   - 第14讲 - 从零开始搭建轻量级研发团队.md
  
   - 第15讲 - 定制高效研发流程.md
  
   - 第16讲 - 培养中层团队的管理认知.md
  
   - 大咖问答 - 发现下一个小米，不是只能靠运气.md
  
   - 第17讲 - 团队成长要靠技巧和体系.md
  
   - 第18讲 - 做到这四点，团队必定飞速成长.md
  
   - 第19讲 - 将企业打造成一所终身大学.md
  
   - 第20讲 - 论团队管理与共同升级.md
  
   - 大咖对话 - 技术人真正需要的是升维思考.md
  
   - 第21讲 - 绩效管理的目标不仅仅是绩效考核.md
  
   - 第22讲 - 验证研发团队价值的绩效考核机制.md
  
   - 第23讲 - 产品技术团队OKR使用法则.md
  
   - 第24讲 - 996、987，程序员加班文化你怎么看？.md
  
   - 大咖对话 - 技术管理者应该向优秀的体育教练学习.md
  
   - 第25讲 - 建立有效的员工淘汰机制.md
  
   - 第26讲 - 让细节的“病毒”感染你的团队.md
  
   - 第27讲 - 如何在不同组织文化下推行技术管理.md
  
   - 第28讲 - 业务高速增长期的团队管理：“知轻重、重绸缪、调缓急”.md
  
   - 大咖对话 - 让团队成员持续的enjoy.md
  
   - 第29讲 - 被80%的人误解的工程师文化.md
  
   - 第30讲 - 关于工程师文化的六个问题.md
  
   - 第31讲 - 五位技术领导者的文化构建实战.md
  
   - 第32讲 - 文化是管理的那只无形之手.md
  
   - 大咖对话 - 创业就是把自己过去的经验快速的产品化.md
  
   - 第33讲 - 选对的人，做正确的事情.md
  
   - 第34讲 - 打好技术团队搭建的基础.md
  
   - 第35讲 - 做个合格的技术岗位面试官.md
  
   - 第36讲 - “高潜力人才”的内部培养.md
  
   - 大咖对话 - 如何高效管理8000+规模的技术团队.md
  
   - 第37讲 - 技术创业该如何选择赛道.md
  
   - 第38讲 - CTO要掌握的产品哲学：理性与人性的权衡.md
  
   - 第39讲 - 从客户价值谈技术创新.md
  
   - 第40讲 - 技术人投身创业公司之前，应当考虑些什么？.md
  
   - 大咖对话 - 技术人创业前衡量自我的3P3C模型.md
  
   - 第41讲 - 技术人创业前要问自己的六个问题.md
  
   - 第42讲 - 团队激励之分配好你的奖金.md
  
   - 第43讲 - 通过积分考核提升技术团队的绩效.md
  
   - 第44讲 - 空降技术高管的“择业七计”.md
  
   - 大咖对话 - 如何打造自我驱动型的技术团队？.md
  
   - 第45讲 - 选好人生下一站——CTO空降上篇.md
  
   - 第46讲 - 走出“至暗时刻”——CTO空降下篇.md
  
   - 第47讲 - 空降领导者平稳落地要做的四道题（上）.md
  
   - 第48讲 - 空降领导者平稳落地要做的四道题（下）.md
  
   - 大咖对话 - 管理者是首席铲屎官？.md
  
   - 第49讲 - 打造高效的研发组织架构：高效研发流程那些事（一）.md
  
   - 第50讲 - 你的研发流程符合你的组织架构吗？谈高效研发流程那些事（二）.md
  
   - 第51讲 - 聊聊研发流程管理中的那些坑：高效研发流程那些事（三）.md
  
   - 第52讲 - 数据如何驱动研发高效运转？谈高效研发流程那些事（四）.md
  
   - 大咖对话 - 对人才的长期投资是人才体系打造的根本.md
  
   - 第53讲 - 如何打造高效且敏捷的组织文化？谈高效研发流程那些亊（五）.md
  
   - 第54讲 - 打造高速运转的迭代机器：现代研发流程体系打造（一）.md
  
   - 第55讲 - 用机器打造迭代机器：现代研发流程体系打造（二）.md
  
   - 第56讲 - 有了敏捷开发，那交付期限去哪儿了？.md
  
   - 大咖对话 - 项目成功的秘诀——技术产品双头负责制.md
  
   - 第57讲 - 敏捷中的期限之殇，软件业该怎么做？.md
  
   - 第58讲 - 如何打造个人技术品牌？.md
  
   - 第59讲 - 技术演讲，有章可循.md
  
   - 第60讲 - 正确对待技术演讲中的失误.md
  
   - 大咖对话 - 不可替代的Java：生态与程序员是两道护城河.md
  
   - 第61讲 - 刘俊强：技术最高决策者应该关注技术细节吗？.md
  
   - 第62讲 - 张溪梦：技术领袖需要具备的商业价值思维.md
  
   - 第63讲 - 未来组织形态带来的领导力挑战.md
  
   - 第64讲 - 如何判断业务价值的高低.md
  
   - 大咖对话 - 池建强：做产品不要执着于打造爆款.md
  
   - 第65讲 - 如何打造高效的分布式团队？.md
  
   - 第66讲 - 如何打造有活力、持续创新的研发团队？.md
  
   - 第67讲 - 如何打造独属自己的工程师文化？.md
  
   - 第68讲 - 如何打造一个自组织团队？.md
  
   - 大咖对话 - 童剑：用合伙人管理结构打造完美团队.md
  
   - 第69讲 - 茹炳晟：QE团队向工程效能团队转型的实践之路.md
  
   - 第70讲 - 技术、产品、管理的不同视角.md
  
   - 第71讲 - 什么样的人适合考虑管理角色.md
  
   - 第72讲 - 创业公司如何招到合适的人才.md
  
   - 大咖对话 - 以产生价值判断工程师贡献——读者留言精选.md
  
   - 第73讲 - 用数据来分析管理员工.md
  
   - 第74讲 - 为什么给了高工资，依然留不住核心员工？.md
  
   - 第75讲 - 刘俊强：一本正经教你如何毁掉一场技术演讲.md
  
   - 第76讲 - 内部技术会议的价值.md
  
   - 大咖对话 - 韩军：CTO转型CEO如何转变思路.md
  
   - 第79讲 - 程军：从0到1打造高效技术团队的方法论.md
  
   - 第80讲 - 技术Leader的持续成长.md
  
   - 大咖对话 - 焦烈焱：从四个维度更好的激发团队创造力.md
  
   - 第81讲 - 游舒帆：一流团队必备的商业思维能力.md
  
   - 第82讲 - 游舒帆：数据力，透过数据掌握公司经营大小事.md
  
   - 第83讲 - 游舒帆：运营力，让用户出现你期待的行为.md
  
   - 大咖对话 - 谭待：架构的本质是折中.md
  
   - 第84讲 - 游舒帆：策略力，让目标与行动具备高度一致性.md
  
   - 第85讲 - 游舒帆：敏捷力，拥抱不确定性，与VUCA共舞.md
  
   - 第86讲 - 刘俊强：管理者必备的高效会议指南（上）.md
  
   - 第87讲 - 刘俊强：管理者必备的高效会议指南（下）.md
  
   - 大咖对话 - 陈斌：如何打造高创造力、高动力的技术团队.md
  
   - 第88讲 - 刘俊强：做好一对一沟通的关键要素（上）.md
  
   - 第89讲 - 刘俊强：做好一对一沟通的关键要素（下）.md
  
   - 第90讲 - 程军：打造高效技术团队之招人.md
  
   - 第91讲 - 程军：打造高效技术团队之做事.md
  
   - 大咖对话 - 万玉权：高效团队的关键，以目标为导向，用数据来说话.md
  
   - 第92讲 - 成敏：技术负责人如何做优先级决策.md
  
   - 第93讲 - 兰军：团队研发效率低下的要因分析.md
  
   - 第94讲 - 兰军：提升产品团队研发效率的实践（上）.md
  
   - 第95讲 - 兰军：提升产品团队研发效率的实践（下）.md
  
   - 大咖对话 - 万玉权：如何招到并培养核心人才.md
  
   - 第96讲 - 阿禅：工程师转型产品经理可能踩到的“坑”.md
  
   - 第97讲 - 阿禅：工程师转型产品经理的必备思维.md
  
   - 第98讲 - 徐裕键：业务高速增长过程中的团队迭代.md
  
   - 第99讲 - 徐裕键：业务高速增长过程中的技术演进.md
  
   - 大咖对话 - 杨育斌：技术领导者要打造技术团队的最大化价值.md
  
   - 第100讲 - 徐裕键：团队文化建设，保持创业公司的战斗力.md
  
   - 第101讲 - 刘俊强：领导力提升指南之培养积极的态度.md
  
   - 第102讲 - 姚从磊：巧用AARRR模型，吸引优秀技术人才（一）.md
  
   - 第103讲 - 姚从磊：巧用AARRR模型，吸引优秀技术人才（二）.md
  
   - 大咖对话 - 谢孟军：技术人如何建立自己的个人品牌.md
  
   - 第104讲 - 姚从磊：巧用 AARRR 模型，吸引优秀技术人才（三）.md
  
   - 第105讲 - 姚从磊：巧用 AARRR 模型，吸引优秀技术人才（四）.md
  
   - 第106讲 - 程军：技术人的「知行合一」（一）.md
  
   - 第107讲 - 刘俊强：消除压力的七种方法.md
  
   - 大咖对话 - 余沛：进阶CTO必备的素质与能力.md
  
   - 第108讲 - 谢呈：技术高手转身创业的坑和坡.md
  
   - 第109讲 - 谢呈：关于垂直互联网创业的一些经验之谈.md
  
   - 第110讲 - 成敏：创业公司为什么会技术文化产品缺失.md
  
   - 第111讲 - 蔡锐涛：从0到1再到100，创业不同阶段的技术管理思考.md
  
   - 大咖对话 - 余沛：打造以最佳交付实践为目标的技术导向.md
  
   - 第112讲 - 刘俊强：必知绩效管理知识之绩效管理循环.md
  
   - 第113讲 - 程军：技术人的「知行合一」（二）.md
  
   - 第114讲 - 成敏：谈谈不同阶段技术公司的特点.md
  
   - 第115讲 - 成敏：打造优秀团队与文化的三个推手.md
  
   - 大咖对话 - 季昕华：以不变的目的应对多变的技术浪潮.md
  
   - 第116讲 - 刘俊强：必知绩效管理知识之绩效目标的制定.md
  
   - 第117讲 - 程军：技术人的「知行合一」（三）.md
  
   - 第118讲 - 吴铭：成本评估是技术leader的关键素质.md
  
   - 第119讲 - 汤力嘉：CTO如何进行产品决策（一）.md
  
   - 大咖对话 - 胡哲人：技术人创业要跨过的思维坎.md
  
   - 第120讲 - 刘俊强：必知绩效管理知识之绩效数据收集（上）.md
  
   - 第121讲 - 刘俊强：必知绩效管理知识之绩效数据收集（下）.md
  
   - 第122讲 - 黄伟坚：创业中那些永远回避不了的问题.md
  
   - 第123讲 - 黄伟坚：用系统性思维看待创业.md
  
   - 大咖对话 - 袁店明：打造高效研发团队的五个要点.md
  
   - 第124讲 - 刘俊强：必知绩效管理知识之评定绩效.md
  
   - 第125讲 - 洪强宁：从程序员到架构师，从架构师到CTO（一）.md
  
   - 第126讲 - 洪强宁：从程序员到架构师，从架构师到CTO（二）.md
  
   - 第127讲 - 刘俊强：必知绩效管理知识之绩效沟通（一）.md
  
   - 大咖对话 - 袁店明：如何将打造自组织团队落诸实践.md
  
   - 第128讲 - 王坚：年轻人永远是创新的主体.md
  
   - 第129讲 - 刘俊强：必知绩效管理知识之绩效沟通（二）.md
  
   - 第130讲 - 刘俊强：必知绩效管理知识之绩效沟通（三）.md
  
   - 第131讲 - 汤力嘉：CTO如何在产品方面进行决策（二）.md
  
   - 大咖对话 - 王坚：我从不吃后悔药.md
  
   - 第132讲 - 徐函秋：转型技术管理者初期的三大挑战（一）.md
  
   - 第133讲 - 徐函秋：转型技术管理者初期的三大挑战（二）.md
  
   - 第134讲 - 刘建国：我各方面做得都很好，就是做不好向上沟通.md
  
   - 第135讲 - 钮博彦：软件研发度量体系建设（一）.md
  
   - 大咖对话 - 高斌：过分渲染会过度拉高大众对人工智能的期望.md
  
   - 第136讲 - 钮博彦：软件研发度量体系建设（二）.md
  
   - 第137讲 - 成敏：创业者不要成为自己公司产品技术文化的破坏者.md
  
   - 第138讲 - 于艺：以生存为核心，B端产品的定位心法.md
  
   - 第139讲 - 成敏：创业者应该具备的认知与思维方式.md
  
   - 大咖对话 - 张建锋：创业可以快而大，也可以小而美.md
  
   - 第140讲 - 袁店明：创业产品必须迈过的鸿沟.md
  
   - 第141讲 - 徐毅：五星级软件工程师的高效秘诀（一）.md
  
   - 第142讲 - 徐毅：五星级软件工程师的高效秘诀（二）.md
  
   - 第143讲 - 徐毅：技术Leader应该具备的能力或素质.md
  
   - 大咖对话 - 徐毅：打造高效研发团队的五个维度及相关实践.md
  
   - 第144讲 - 于艺：如何提升自己的能力与动力.md
  
   - 第145讲 - 李列为：技术人员的商业思维.md
  
   - 第146讲 - 刘天胜：打造高效团队，关键在于平衡人、事和时间（一）.md
  
   - 第147讲 - 刘天胜：打造高效团队，关键在于平衡人、事和时间（二）.md
  
   - 大咖对话 - 徐毅：如何提升员工的活力与动力？.md
  
   - 第148讲 - 肖德时：创业团队技术领导者必备的十个领导力技能（上）.md
  
   - 第149讲 - 肖德时：创业团队技术领导者必备的十个领导力技能（下）.md
  
   - 第150讲 - 暨家愉：技术人如何快乐的自我成长（上）.md
  
   - 第151讲 - 暨家愉：技术人如何快乐的自我成长（下）.md
  
   - 大咖对话 - 王龙：利用 C 端连接 B 端实现产业互联网是下半场的重中之重.md
  
   - 第152讲 - 施翔：如何打造7*24高效交付通道（上）.md
  
   - 第153讲 - 施翔：如何打造7*24高效交付通道（下）.md
  
   - 第154讲 - 谢东升：说说技术管理者从外企到民企的挑战.md
  
   - 第155讲 - 王可光：如何搭建初创团队之人才关.md
  
   - 大咖对话 - 王平：从人、事、价值观、文化等维度看技术团队转型.md
  
   - 第156讲 - 成敏：技术人转型管理的两大秘诀.md
  
   - 第157讲 - 成敏：技术人才的管理公式.md
  
   - 第158讲 - 胡峰：人到中年：失业与恐惧.md
  
   - 第159讲 - 黄云：技术管理者如何科学的做好向上管理.md
  
   - 大咖对话 - 王平：如何快速搭建核心技术团队.md
  
   - 第160讲 - 胡键：创业公司需要高凝聚力高绩效的技术团队.md
  
   - 第161讲 - 卢亿雷：企业发展的不同阶段，该如何打造高效的研发流程体系.md
  
   - 第162讲 - 王海亮：提升技术团队效率的5个提示（上）.md
  
   - 第163讲 - 王海亮：提升技术团队效率的5个提示（下）.md
  
   - 大咖对话 - 彭跃辉：保持高效迭代的团队是如何炼成的.md
  
   - 第164讲 - 陈崇磐：心理成熟度 - 创业公司识人利器.md
  
   - 第165讲 - 陈崇磐：管事与管人 - 如何避开创业公司组队陷阱.md
  
   - 第166讲 - 俞圆圆：合格CTO应该做好的5件事（上）.md
  
   - 第167讲 - 俞圆圆：合格CTO应该做好的5件事（下）.md
  
   - 大咖对话 - 彭跃辉：解决用户痛点就是立足于市场的秘诀.md
  
   - 新春特辑1 - 卓越CTO必备的能力与素质.md
  
   - 新春特辑2 - 如何成长为优秀的技术管理者？.md
  
   - 新春特辑3 - 如何打造高质效的技术团队？.md
  
   - 新春特辑4 - 如何打造高效的研发流程与文化？.md
  
   - 新春特辑5 - 如何做好人才的选育用留？.md
  
   - 第168讲 - 余加林：从技术人到创业合伙人必备的三个维度的改变.md
  
   - 第169讲 - 高琦：如何给研发打绩效不头疼而又公正？（上）.md
  
   - 第170讲 - 高琦：如何给研发打绩效不头疼而又公正？（下）.md
  
   - 第171讲 - 邱良军：如何有效地找到你心仪的人才.md
  
   - 大咖对话 - 王鹏云：管理方式的差异是为了更好地实现企业商业价值.md
  
   - 第172讲 - 于人：研发团队人均产能3年提升3.6倍的秘诀（上）.md
  
   - 第173讲 - 于人：研发团队人均产能3年提升3.6倍的秘诀（下）.md
  
   - 第174讲 - 邱良军：打造高效技术团队，你准备好了吗！.md
  
   - 第175讲 - 邱良军：打造高效技术团队的人才招聘攻略.md
  
   - 大咖对话 - 王鹏云：技术人创业该如何选择合伙人？.md
  
   - 第176讲 - 胡键：创业公司如何打造高凝聚力高绩效的技术团队：组织篇.md
  
   - 第177讲 - 胡键：创业公司如何打造高凝聚力高绩效的技术团队：工具篇.md
  
   - 第178讲 - 马连浩：用人的关键在于用人所长，而非改人之短.md
  
   - 第179讲 - 张矗：技术管理者必经的几个思维转变.md
  
   - 大咖对话 - 李昊：创业公司如何做好技术团队绩效考核？.md
  
   - 第180讲 - 钟忻：成为“温格”—聊聊如何当好CTO.md
  
   - 第181讲 - 姚威：技术团队管理中关于公平的五个核心准则.md
  
   - 第182讲 - 谢文杰：区块链的下一个十年.md
  
   - 第183讲 - 薛文植：技术管理的本质—要做尊重人性的管理.md
  
   - 大咖对话 - 陈天石：AI 芯片需要技术和资本的双重密集支撑.md
  
   - 第184讲 - 狼叔：2019年前端和Node的未来—大前端篇（上）.md
  
   - 第185讲 - 狼叔：2019年前端和Node的未来—大前端篇（下）.md
  
   - 第186讲 - 赵晓光：如何培养团队竞争力（上）.md
  
   - 第187讲 - 赵晓光：如何培养团队竞争力（下）.md
  
   - 大咖对话 - 李智慧：技术人如何应对“互联网寒冬”.md
  
   - 第188讲 - 张嵩：从心理学角度看待小中型团队的管理.md
  
   - 第189讲 - 狼叔：2019年前端和Node的未来—Node.js篇（上）.md
  
   - 第190讲 - 狼叔：2019年前端和Node的未来—Node.js篇（下）.md
  
   - 第191讲 - 肖冰：如何建立高信任度的团队.md
  
   - 大咖对话 - 刘俊强：谈谈我对2019年云计算趋势的看法.md
  
   - 第192讲 - 崔俊涛：如何做好技术团队的激励（上）.md
  
   - 第193讲 - 崔俊涛：如何做好技术团队的激励（下）.md
  
   - 第194讲 - 刘俊强：2019年云计算趋势对技术人员的影响.md
  
   - 第195讲 -  吴晖：企业B2B服务打磨的秘诀—ESI.md
  
   - 大咖对话 - 刘俊强：云计算时代技术管理者的应对之道.md
  
   - 第196讲 - 邱良军：关于做好技术团队管理的几点思考.md
  
   - 第197讲 - 邱良军：做好研发管理的3个关键.md
  
   - 第198讲 - 徐林：通过快速反馈建立充满信任的技术团队.md
  
   - 第199讲 - 宝玉：怎样平衡软件质量与时间成本范围的关系？.md
  
   - 大咖对话 - 陶真：技术人要爱上问问题，而不是自己的解决方案.md
  
   - 第200讲 - 邱良军：沟通，沟通，还是沟通（上）.md
  
   - 第201讲 - 邱良军：沟通，沟通，还是沟通（下）.md
  
   - 第202讲 - 陈嘉佳：奈飞文化宣言（上）.md
  
   - 第203讲 - 陈嘉佳：奈飞文化宣言（下）.md
  
   - 大咖对话 - 玉攻：四个维度看小程序与App的区别.md
  
   - 第204讲 - 邱良军：从小处着眼，修炼文化价值观.md
  
   - 第205讲 - 邵浩：人工智能新技术如何快速发现及落地（上）.md
  
   - 第206讲 - 邵浩：人工智能新技术如何快速发现及落地（下）.md
  
   - 第207讲 - 许良：科创板来了，我该怎么办？.md
  
   - 第208讲 - 陈阳：科创板投资，未来哪些行业受益最大？.md
  
   - 大咖对话 - 顾旻曼：投资时我们更多地是在找优秀的团队.md
  
   - 结束篇 - 即使远隔千山万水，也要乘风与你同往.md
  
   - 温故而知新 - 一键直达，六大文章主题索引.md
  