site_name: Python实战 · 从0到1搭建直播视频平台

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Python实战 · 从0到1搭建直播视频平台.md
  
   - 开篇词-打通前后端技术，玩转视频平台.md
  
   - 01-初识Python（上）：入门Python你应该怎么做？.md
  
   - 02-初识Python（下）：入门Python你应该怎么做？.md
  
   - 03-初识Web：学习Web最好的方式是什么？.md
  
   - 04-Vue概览：Vue哪些内容是你必须要掌握的？.md
  
   - 18-初识Flask：搭建第一个Flask项目.md
  
   - 19-路由定义和视图常用逻辑：路由定义和视图的核心是什么？.md
  
   - 20-匹配路由&异常捕获：如何用转化器实现匹配规则？.md
  
   - 21-数据库ORM对象关系映射（一）：数据库连接与必备操作.md
  
   - 22-数据库应用（二）：数据库ORM对象关系映射.md
  
   - 23-数据库应用（三）：项目数据库配置实战.md
  
   - 24-数据库应用（四）：如何在项目中灵活应用数据库操作.md
  
   - 25-Blueprint与Redprint：如何让程序进行模块化处理？.md
  
   - 26-RESTful API与Flask-Restful：如何实现后端接口的开发与封装？.md
  
   - 27-初识认证机制：认证机制能解决哪些问题？.md
  
   - 28-认证机制：Flask认证机制设计与实现.md
  
   - 29-后端功能接口实战（一）：后端接口该如何开发？.md
  
   - 30-后端功能接口实战（二）：后端接口该如何开发？.md
  
   - 31-项目实战与部署：如何实现接口部署与访问？.md
  
   - 32-全面解析HTTP：从HTTP-0.9到HTTP-3的演变.md
  
   - 33-直播流程：如何设计搭建直播的核心流程？.md
  
   - 34-Nginx安装与直播配置：Nginx如何实现直播配置？.md
  
   - 35-RTMP协议与NRM搭建：如何使用NRM支持HLS协议直播？.md
  
   - 36-推拉流、串流码与控制器：实现录制与停止直播流.md
  
   - 37-直播完整实现：使用Nginx-rtmp-module配置RTMP直播服务.md
  
   - 38-回顾总结：前后端知识体系全景回顾.md
  
   - 05-需求分析：如何确定在线视频平台的核心功能模块？.md
  
   - 06-框架搭建：如何用vue-cli搭建一个前端框架？.md
  
   - 07-路由设计：如何借助Vue Router设计出更合理的路由？.md
  
   - 08-个人中心与权限：如何玩转各类系统的权限管理？.md
  
   - 09-ElementU & CSS：如何设计页面逻辑与功能点？.md
  
   - 10-详情页实现：如何实现需求定制化？.md
  
   - 11-DPlayer播放器综合应用：怎样实现自己的第一个视频播放器？.md
  
   - 12-视频发布功能实现：怎样满足用户发布视频的需求？.md
  
   - 13-数据中心应用：平台数据大脑应具备哪些核心指标？.md
  
   - 14-ECharts实战：可视化如何更好地服务于创作者？.md
  
   - 15-直播中心搭建（一）：如何通过Video.js配置直播中心？.md
  
   - 16-直播中心搭建（二）：如何通过VideoJs配置直播中心？.md
  
   - 17-项目打包与优化：前端必备的Webpack打包配置详解.md
  
   - 答疑篇-前导篇&前端实战篇思考题答案.md
  
   - 结束语-在技术的浪潮中，成为奔腾不息的后浪.md
  
   - 结课测试-来赴一场满分之约！.md
  