site_name: 现代React Web开发实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 现代React Web开发实战.md
  
   - 开篇词-React Web开发这样学，才能独当一面！.md
  
   - 01-身为Web前端工程师，我都在开发什么？.md
  
   - 02-开发前端有哪些要点？React框架是如何应对的？.md
  
   - 03-看板应用：从零开始快速搭建一个React项目.md
  
   - 04-JSX：如何理解这种声明式语法糖？.md
  
   - 05-前端组件化：如何将完整应用拆分成React组件？.md
  
   - 06-虚拟DOM：为什么要关心React组件的渲染机制？.md
  
   - 07-组件样式：聊聊CSS-in-JS的特点和典型使用场景.md
  
   - 08-组件生命周期：React新老版本中生命周期的演化.md
  
   - 09-React Hooks（上）：为什么说在React中函数组件和Hooks是绝配？.md
  
   - 10-React Hooks（下）：用Hooks处理函数组件的副作用.md
  
   - 11-事件处理：React合成事件是什么？为什么不用原生DOM事件？.md
  
   - 12-组件表与里（上）：数据是如何在 React 组件之间流转的？.md
  
   - 13-组件表与里（下）：用接口的思路设计开发React组件.md
  
   - 14-现代化React：现代工程化技术下的React项目.md
  
   - 15-不可变数据：为什么对React这么重要？.md
  
   - 16-应用状态管理（上）：应用状态管理框架Redux.md
  
   - 17-应用状态管理（下）：该用React组件状态还是Redux？.md
  
   - 18-数据类型：活用TypeScript做类型检查.md
  
   - 19-代码复用：如何设计开发自定义Hooks和高阶组件？.md
  
   - 20-大型项目：源码越来越多，项目该如何扩展？.md
  
   - 21-性能优化：保证优秀的用户体验.md
  
   - 22-质量保证（上）：每次上线都出Bug？你需要E2E测试.md
  
   - 23-质量保证（下）：测试金字塔与React单元测试.md
  
   - 24-工程化与团队协作：让我们合作开发一个大型React项目.md
  
   - 加餐01-留言区心愿单：真·子组件以及jsx-runtime.md
  
   - 加餐02-留言区心愿单：Fiber协调引擎.md
  
   - 直播加餐01-前端开发为什么要工程化？.md
  
   - 直播加餐02-Freewheel前端工程化的演进和最佳实践.md
  
   - 结束语-对React和前端技术未来的展望.md
  
   - 特别加餐-用ChatGPT开发一个看板项目.md
  