site_name: 深度学习推荐系统实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 深度学习推荐系统实战.md
  
   - 开篇词 - 从0开始搭建一个深度学习推荐系统.md
  
   - 01 - 技术架构：深度学习推荐系统的经典技术架构长啥样？.md
  
   - 02 - Sparrow RecSys：我们要实现什么样的推荐系统？.md
  
   - 03 - 深度学习基础：你打牢深度学习知识的地基了吗？.md
  
   - 国庆策划 - 关于深度学习推荐系统，我有这些资料想推荐给你.md
  
   - 国庆策划 - 深度学习推荐系统基础，你掌握了多少？.md
  
   - 04 - 特征工程：推荐系统有哪些可供利用的特征？.md
  
   - 05 - 特征处理：如何利用Spark解决特征处理问题？.md
  
   - 06 - Embedding基础：所有人都在谈的Embedding技术到底是什么？.md
  
   - 07 - Embedding进阶：如何利用图结构数据生成Graph Embedding？.md
  
   - 08 - Embedding实战：如何使用Spark生成Item2vec和Graph Embedding？.md
  
   - 答疑 - 基础架构篇+特征工程篇常见问题解答.md
  
   - 09 - 线上服务：如何在线上提供高并发的推荐服务？.md
  
   - 10 - 存储模块：如何用Redis解决推荐系统特征的存储问题？.md
  
   - 11 - 召回层：如何快速又准确地筛选掉不相关物品？.md
  
   - 12 - 局部敏感哈希：如何在常数时间内搜索Embedding最近邻？.md
  
   - 13 - 模型服务：怎样把你的离线模型部署到线上？.md
  
   - 14 - 融会贯通：Sparrow RecSys中的电影相似推荐功能是如何实现的？.md
  
   - 答疑 - 线上服务篇留言问题详解.md
  
   - 15 - 协同过滤：最经典的推荐模型，我们应该掌握什么？.md
  
   - 16 - 深度学习革命：深度学习推荐模型发展的整体脉络是怎样的？.md
  
   - 模型实战准备（一） - TensorFlow入门和环境配置.md
  
   - 模型实战准备（二） - 模型特征、训练样本的处理.md
  
   - 17 - Embedding+MLP：如何用TensorFlow实现经典的深度学习模型？.md
  
   - 18-Wide&Deep：怎样让你的模型既有想象力又有记忆力？.md
  
   - 19-NeuralCF：如何用深度学习改造协同过滤？.md
  
   - 20 - DeepFM：如何让你的模型更好地处理特征交叉？.md
  
   - 21-注意力机制、兴趣演化：推荐系统如何抓住用户的心？.md
  
   - 22-强化学习：让推荐系统像智能机器人一样自主学习.md
  
   - 特别加餐 - “银弹”不可靠，最优的模型结构该怎么找？.md
  
   - 23- 实战：如何用深度学习模型实现Sparrow RecSys的个性化推荐功能？.md
  
   - 24 - 离线评估：常用的推荐系统离线评估方法有哪些？.md
  
   - 25 - 评估指标：我们可以用哪些指标来衡量模型的好坏？.md
  
   - 特别加餐-TensorFlow的模型离线评估实践怎么做？.md
  
   - 26 - 在线测试：如何在推荐服务器内部实现A-B测试？.md
  
   - 27 - 评估体系：如何解决A-B测试资源紧张的窘境？.md
  
   - 28 - 业界经典：YouTube深度学习推荐系统的经典架构长什么样？.md
  
   - 29 - 图神经网络：Pinterest是如何应用图神经网络的？.md
  
   - 30 - 流处理平台：Flink是如何快速识别用户兴趣，实现实时推荐的？.md
  
   - 31-模型迭代：阿里巴巴是如何迭代更新推荐模型的？.md
  
   - 32 - 强化学习案例：美团是如何在推荐系统中落地强化学习的？.md
  
   - 33-技术权衡：解决方案这么多，哪个最合适？.md
  
   - 结束语-深度学习时代需要什么样的推荐工程师？.md
  
   - 期末考试 - “深度学习推荐系统”100分试卷等你来挑战！.md
  