site_name: 手把手带你写一个MiniTomcat

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 手把手带你写一个MiniTomcat.md
  
   - 开篇词-重造轮子，探究Tomcat的秘密.md
  
   - 01-持久的传奇：Tomcat的发展历程与框架演进.md
  
   - 02-初出茅庐：构造一个极简的HttpServer.md
  
   - 03-动态Response：按照规范构造返回流.md
  
   - 04-各司其职的Server：拆分响应模块与处理模块.md
  
   - 05-Server性能提升：设计多个Processor.md
  
   - 06-规范化：引入HttpRequest与HttpResponse.md
  
   - 07-对内的保护：引入门面模式封装内部实现类.md
  
   - 08-解析参数：通过引入Cookie和Session避免反复登录.md
  
   - 09-有状态的Response：实现Session传递与Keep-alive.md
  
   - 10-Servlet Wrapper：如何维护Servlet生命周期及实现容器管理？.md
  
   - 11- 多层容器：如何通过实现Context与Wrapper形成多层容器？.md
  
   - 12-Pipeline与Valve：如何实现容器间的调用、事务管理、权限验证？.md
  
   - 13-Filter与Listener：如何实现过滤和持续监听？.md
  
   - 14-多应用支持：拆分Context、BootStrap与路由转发.md
  
   - 15-类加载机制的改变：如何自定义ClassLoader？.md
  
   - 16-大功告成：完成MiniTomcat.md
  
   - 17-更大的框架：MiniSpring与MiniTomcat集成.md
  
   - 18-高并发探讨：如何支持 NIO？.md
  
   - 19-Servlet与NIO的协同：如何在NIO模式下调用Servlet？.md
  
   - 结束语-像地质学家一样奋力往下挖.md
  
   - 结课测试-来赴一场满分之约.md
  