site_name: 软件设计之美

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 软件设计之美.md
  
   - 开篇词 - 软件设计，应对需求规模的“算法”.md
  
   - 01 - 软件设计到底是什么？.md
  
   - 02 - 分离关注点：软件设计至关重要的第一步.md
  
   - 03 - 可测试性： 一个影响软件设计的重要因素.md
  
   - 04 - 三步走：如何了解一个软件的设计？.md
  
   - 05 - Spring DI容器：如何分析一个软件的模型？.md
  
   - 06 - Ruby on Rails：如何分析一个软件的接口？.md
  
   - 07 - Kafka：如何分析一个软件的实现？.md
  
   - 08 - 语言的模型：如何打破单一语言局限，让设计更好地落地？.md
  
   - 09 - 语言的接口：语法和程序库，软件设计的发力点.md
  
   - 10 - 语言的实现：运行时，软件设计的地基.md
  
   - 11 - DSL：你也可以设计一门自己的语言.md
  
   - 加餐 - 再八卦几门语言！.md
  
   - 12 - 编程范式：明明写的是Java，为什么被人说成了C代码？.md
  
   - 13 - 结构化编程：为什么做设计时仅有结构化编程是不够的？.md
  
   - 14 - 面向对象之封装：怎样的封装才算是高内聚？.md
  
   - 15 - 面向对象之继承：继承是代码复用的合理方式吗？.md
  
   - 16 - 面向对象之多态：为什么“稀疏平常”的多态，是软件设计的大杀器？.md
  
   - 17 - 函数式编程：不用函数式编程语言，怎么写函数式的程序？.md
  
   - 18 - 函数式编程之组合性：函数式编程为什么如此吸引人？.md
  
   - 19 - 函数式编程之不变性：怎样保证我的代码不会被别人破坏？.md
  
   - 加餐 - 函数式编程拾遗.md
  
   - 20 - 单一职责原则：你的模块到底为谁负责？.md
  
   - 21 - 开放封闭原则：不改代码怎么写新功能？.md
  
   - 22 - Liskov替换原则：用了继承，子类就设计对了吗？.md
  
   - 23 - 接口隔离原则：接口里的方法，你都用得到吗？.md
  
   - 24 - 依赖倒置原则：高层代码和底层代码，到底谁该依赖谁？.md
  
   - 25 - 设计模式：每一种都是一个特定问题的解决方案.md
  
   - 26 - 简单设计：难道一开始就要把设计做复杂吗？.md
  
   - 27 - 领域驱动设计：如何从零开始设计一个软件？.md
  
   - 28 - 战略设计：如何划分系统的模块？.md
  
   - 29 - 战术设计：如何像写故事一样找出模型？.md
  
   - 30 - 程序库的设计：Moco是如何解决集成问题的？.md
  
   - 31 - 应用的设计：如何设计一个数据采集平台？.md
  
   - 32 - 应用的改进：如何改进我们的软件设计？.md
  
   - 结束语-那些没讲的事儿.md
  
   - 结课测试-这些软件设计的知识你都掌握了吗？.md
  
   - 第三季回归 - 我们一起来写好代码！.md
  
   - 第四季回归 - 通向高质量代码之路.md
  
   - 特别加餐-ChatGPT来了，工程师何去何从？.md
  
   - 私享直播-1小时参透程序员的AI三重境界.md
  
   - 私享直播-程序员的上限、下限和第二曲线.md
  
   - 第五季回归-让我们一起共赴AI时代！.md
  