site_name: Go 语言项目开发实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Go 语言项目开发实战.md
  
   - 开篇词 - 从 0 开始搭建一个企业级 Go 应用.md
  
   - 01 - IAM系统概述：我们要实现什么样的 Go 项目？.md
  
   - 02 - 环境准备：如何安装和配置一个基本的 Go 开发环境？.md
  
   - 03 - 项目部署：如何快速部署 IAM 系统？.md
  
   - 04 - 规范设计（上）：项目开发杂乱无章，如何规范？.md
  
   - 05 - 规范设计（下）：commit 信息风格迥异、难以阅读，如何规范？.md
  
   - 06 - 目录结构设计：如何组织一个可维护、可扩展的代码目录？.md
  
   - 07 - 工作流设计：如何设计合理的多人开发模式？.md
  
   - 08 - 研发流程设计（上）：如何设计 Go 项目的开发流程？.md
  
   - 09 - 研发流程设计（下）：如何管理应用的生命周期？.md
  
   - 10 - 设计方法：怎么写出优雅的 Go 项目？.md
  
   - 11 - 设计模式：Go常用设计模式概述.md
  
   - 12 - API 风格（上）：如何设计RESTful API？.md
  
   - 13 - API 风格（下）：RPC API介绍.md
  
   - 14 - 项目管理：如何编写高质量的Makefile？.md
  
   - 15 - 研发流程实战：IAM项目是如何进行研发流程管理的？.md
  
   - 16 - 代码检查：如何进行静态代码检查？.md
  
   - 17 - API 文档：如何生成 Swagger API 文档 ？.md
  
   - 18 - 错误处理（上）：如何设计一套科学的错误码？.md
  
   - 19 - 错误处理（下）：如何设计错误包？.md
  
   - 20 - 日志处理（上）：如何设计日志包并记录日志？.md
  
   - 21 - 日志处理（下）：手把手教你从 0 编写一个日志包.md
  
   - 22 - 应用构建三剑客：Pflag、Viper、Cobra 核心功能介绍.md
  
   - 23 - 应用构建实战：如何构建一个优秀的企业应用框架？.md
  
   - 24 - Web 服务：Web 服务核心功能有哪些，如何实现？.md
  
   - 25 - 认证机制：应用程序如何进行访问认证？.md
  
   - 26 - IAM项目是如何设计和实现访问认证功能的？.md
  
   - 27 - 权限模型：5大权限模型是如何进行资源授权的？.md
  
   - 28 - 控制流（上）：通过iam-apiserver设计，看Web服务的构建.md
  
   - 29-控制流（下）：iam-apiserver服务核心功能实现讲解.md
  
   - 30 - ORM：CURD 神器 GORM 包介绍及实战.md
  
   - 31 - 数据流：通过iam-authz-server设计，看数据流服务的设计.md
  
   - 32 - 数据处理：如何高效处理应用程序产生的数据？.md
  
   - 33 -  SDK 设计（上）：如何设计出一个优秀的 Go SDK？.md
  
   - 34 - SDK 设计（下）：IAM项目Go SDK设计和实现.md
  
   - 35 - 效率神器：如何设计和实现一个命令行客户端工具？.md
  
   - 36 - 代码测试（上）：如何编写 Go 语言单元测试和性能测试用例？.md
  
   - 37 - 代码测试（下）：Go 语言其他测试类型及 IAM 测试介绍.md
  
   - 38-性能分析（上）：如何分析 Go 语言代码的性能？.md
  
   - 39-性能分析（下）：API Server性能测试和调优实战.md
  
   - 40 - 软件部署实战（上）：部署方案及负载均衡、高可用组件介绍.md
  
   - 41 - 软件部署实战（中）：IAM 系统生产环境部署实战.md
  
   - 42 - 软件部署实战（下）：IAM系统安全加固、水平扩缩容实战.md
  
   - 43-技术演进（上）：虚拟化技术演进之路.md
  
   - 44-技术演进（下）：软件架构和应用生命周期技术演进之路.md
  
   - 45-基于Kubernetes的云原生架构设计.md
  
   - 46 - 如何制作Docker镜像？.md
  
   - 47 - 如何编写Kubernetes资源定义文件？.md
  
   - 48 - IAM 容器化部署实战.md
  
   - 49 - 服务编排（上）：Helm服务编排基础知识.md
  
   - 50 - 服务编排（下）：基于Helm的服务编排部署实战.md
  
   - 51 - 基于 GitHub Actions 的 CI 实战.md
  
   - 特别放送 - 给你一份清晰、可直接套用的Go编码规范.md
  
   - 特别放送 - 给你一份Go项目中最常用的Makefile核心语法.md
  
   - 特别放送 - Go Modules依赖包管理全讲.md
  
   - 特别放送 - IAM排障指南.md
  
   - 特别放送 - Go Modules实战.md
  
   - 特别放送 - 分布式作业系统设计和实现.md
  
   - 直播加餐-如何从小白进阶成 Go 语言专家？.md
  
   - 结束语 - 如何让自己的 Go 研发之路走得更远？.md
  
   - 期末考试-《Go语言项目开发实战》满分试卷，等你来挑战！.md
  