site_name: 编程高手必学的内存知识

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 编程高手必学的内存知识.md
  
   - 开篇词-为什么你要系统学习计算机的内存知识？.md
  
   - 导学（一）- 拆解CPU的基本结构和运行原理.md
  
   - 导学（二）- 汇编语言是怎么一回事？.md
  
   - 导学（三）- 一个CPU是怎么寻址的？.md
  
   - 01-虚拟内存：为什么可用内存会远超物理内存？.md
  
   - 02-聊聊x86体系架构中的实模式和保护模式.md
  
   - 03 - 内存布局：应用程序是如何安排数据的？.md
  
   - 04 - 深入理解栈：从CPU和函数的视角看栈的管理.md
  
   - 05 - 栈的魔法：从栈切换的角度理解进程和协程.md
  
   - 06 - 静态链接：变量与内存地址是如何映射的？.md
  
   - 07 - 动态链接（上）：地址无关代码是如何生成的？.md
  
   - 08 - 动态链接（下）：延迟绑定与动态链接器是什么？.md
  
   - 09 - 深入理解堆：malloc和内存池是怎么回事？.md
  
   - 10 - 页中断：fork、mmap背后的保护神.md
  
   - 11 - 即时编译：高性能JVM的核心秘密.md
  
   - 12 - 内存虚拟化：云原生时代的奠基者.md
  
   - 13 - 存储电路：计算机存储芯片的电路结构是怎样的？.md
  
   - 14 - CPU Cache：访存速度是如何大幅提升的？.md
  
   - 15 - MESI协议：多核CPU是如何同步高速缓存的？.md
  
   - 16 - 内存模型：有了MESI为什么还需要内存屏障？.md
  
   - 17 - NUMA：非均匀访存带来了哪些提升与挑战？.md
  
   - 18 - Java内存模型：Java中的volatile有什么用？.md
  
   - 19 - 垃圾回收：如何避免内存泄露？.md
  
   - 20 - Scavenge：基于copy的垃圾回收算法.md
  
   - 21 - 分代算法：基于生命周期的内存管理.md
  
   - 22 - G1 GC：分区回收算法说的是什么？.md
  
   - 23 - Pauseless GC：挑战无暂停的垃圾回收.md
  
   - 24 - GC实例：Python和Go的内存管理机制是怎样的？.md
  
   - 不定期福利第一期 - 海纳：我是如何学习计算机知识的？.md
  
   - 不定期福利第二期 - 软件篇答疑.md
  
   - 直播加餐-链接器和加载器是如何为你工作的？（合集）.md
  
   - 期末测试 - 来赴一场满分之约吧！.md
  
   - 结束语 - 自主基础软件开发的那片星辰大海.md
  