site_name: 玩转Vue 3全家桶

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 玩转Vue 3全家桶.md
  
   - 开篇词 - 如何借助Vue 3建构你的前端知识体系？.md
  
   - 01 - 宏观视角：从前端框架发展史聊聊为什么要学Vue 3？.md
  
   - 02 - 上手：一个清单应用帮你入门Vue.js.md
  
   - 03 - 新特性：初探Vue 3新特性.md
  
   - 04 - 升级：Vue 2项目如何升级到Vue 3？.md
  
   - 05 - 项目启动：搭建Vue 3工程化项目第一步.md
  
   - 06 - 新的代码组织方式：Composition API + <script setup> 到底好在哪里？.md
  
   - 07 - 巧妙的响应式：深入理解Vue 3的响应式机制.md
  
   - 08 - 组件化：如何像搭积木一样开发网页？.md
  
   - 09 - 动画：Vue中如何实现动画效果？.md
  
   - 10 - 数据流：如何使用Vuex设计你的数据流.md
  
   - 11 - 路由：新一代vue-router带来什么变化.md
  
   - 12 - 调试：提高开发效率必备的Vue Devtools.md
  
   - 13 - JSX：如何利用JSX应对更灵活的开发场景？.md
  
   - 14 - TypeScript：Vue 3中如何使用TypeScript？.md
  
   - 15 - 实战痛点1：复杂Vue项目的规范和基础库封装.md
  
   - 16 - 实战痛点2：项目开发中的权限系统.md
  
   - 17 - 实战痛点3：Vue 3中如何集成第三方框架.md
  
   - 18 - 实战痛点4：Vue 3项目中的性能优化.md
  
   - 加餐01-什么是好的项目？.md
  
   - 19 - 实战痛点5：如何打包发布你的Vue 3应用？.md
  
   - 加餐02-深入TypeScript.md
  
   - 20-组件库：如何设计你自己的通用组件库？.md
  
   - 21 - 单元测试：如何使用 TDD 开发一个组件？.md
  
   - 22-表单：如何设计一个表单组件？.md
  
   - 23 - 弹窗：如何设计一个弹窗组件？.md
  
   - 24-树：如何设计一个树形组件？.md
  
   - 25-表格：如何设计一个表格组件？.md
  
   - 26-文档：如何给你的组件库设计一个可交互式文档？.md
  
   - 27-自定义渲染器：如何实现Vue的跨端渲染 ？.md
  
   - 28-响应式：万能的面试题，怎么手写响应式系统.md
  
   - 29-运行时：Vue在浏览器里是怎么跑起来的？.md
  
   - 30-虚拟DOM（上）：如何通过虚拟DOM更新页面？.md
  
   - 31-虚拟DOM（下）：想看懂虚拟DOM算法，先刷个算法题.md
  
   - 32-编译原理（上）：手写一个迷你Vue 3 Compiler的入门原理.md
  
   - 33 - 编译原理（中）：Vue Compiler模块全解析.md
  
   - 34 - 编译原理（下）：编译原理给我们带来了什么？.md
  
   - 35-Vite原理：写一个迷你的Vite.md
  
   - 36-数据流原理：Vuex & Pinia源码剖析.md
  
   - 37-前端路由原理：vue-router源码剖析.md
  
   - 38-服务端渲染原理：Vue 3中的SSR是如何实现的？.md
  
   - 用户故事-有了手感，才能真正把知识学透.md
  
   - 结束语-Vue 3生态源码到底给我们带来了什么？.md
  
   - 期末测试-来赴一场满分之约！.md
  