site_name: AI大模型系统实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - AI大模型系统实战.md
  
   - 第二季回归-我带着LLaMA 3新课回来了！.md
  
   - 开篇词-漫游未来，一起开启AI大模型系统修炼之旅.md
  
   - 01-认知升级：你心中的AI大模型长啥样？.md
  
   - 02-具身智能：OpenAI真正的野心是什么？.md
  
   - 03-原型系统：开源工具自建AI大模型底座.md
  
   - 04-游目骋怀：工业级的大模型系统强在哪？.md
  
   - 05-策略建模：为什么AI系统能够猜你所想？.md
  
   - 06-特征工程：数据点石成金，给你的系统赋予灵魂.md
  
   - 07-模型工程：算法三大门派，取众家之长为我所用.md
  
   - 08 - 数据算法：因材施教，为你的系统选好老师.md
  
   - 09-系统构建（一）：AI系统的弹药库——离线系统.md
  
   - 10-系统构建（二）：AI系统的冲锋队——在线系统.md
  
   - 答疑课堂-前两章思考题答案.md
  
   - 11-地球往事：为什么CV领域首先引领预训练潮流？.md
  
   - 12-博观约取：重走NLP领域预训练模型的长征路.md
  
   - 13-厚积薄发：如何让模型更好地理解人类语言？.md
  
   - 14-变形金刚：Transformer是如何让模型变大的？.md
  
   - 15 - GPT1-3：技术爆炸，深入解析LLM的核心技术.md
  
   - 16-ChatGPT：是什么让LLM走向舞台中央？.md
  
   - 17-LLM展望：死神永生，LLM会带人们驶向何处？.md
  
   - 18-策略建模：取众家所长的工业级的AIGC系统.md
  
   - 19-提示语工程（一）：为什么说提示语引擎是“智能体本体”？.md
  
   - 20-提示语工程（二）：LLM的护卫舰队有哪些？.md
  
   - 21-提示语工程（三）：如何帮助智能体更好地管理记忆？.md
  
   - 国庆策划-赛程过半，检验一下你的学习成果吧！.md
  
   - 22-提示语工程（四）：如何让智能体学会反思过去和规划未来？.md
  
   - 23-提示语工程（五）：构建你自己的西部世界——AI小镇搭建实战.md
  
   - 24-提示语工程（六）：超越智能，让你的AI系统成为全知超人.md
  
   - 25-模型工程（一）：如何让你的训练数据无中生有？.md
  
   - 26-模型工程（二）：算力受限，如何为“无米之炊”？.md
  
   - 27-模型工程（三）：低成本领域模型方案，小团队怎么做大模型？.md
  
   - 28-总体回顾：工业级AI大模型系统的庐山真面目.md
  
   - 29-从创业到被收购，OpenAI经历了哪些关键阶段？.md
  
   - 30-藏宝图：大模型产业全景图，新业态带来哪些新机遇？.md
  
   - 31-发展趋势：生成式AI系统的未来发展趋势是什么？.md
  
   - 32-职场规划：面试准备，如何做大模型时代下的长远规划？.md
  
   - 答疑课堂（二）-后三章思考题答案.md
  
   - 结束语-AI大模型，技术人的双城记.md
  
   - 结课测试-来赴一场满分之约.md
  