site_name: iOS开发高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - iOS开发高手课.md
  
   - 开篇词 - 锚定一个点，然后在这个点上深耕.md
  
   - 01 - 建立你自己的iOS开发知识体系.md
  
   - 02 - App 启动速度怎么做优化与监控？.md
  
   - 03 - Auto Layout 是怎么进行自动布局的，性能如何？.md
  
   - 04 - 项目大了人员多了，架构怎么设计更合理？.md
  
   - 05 - 链接器：符号是怎么绑定到地址上的？.md
  
   - 06 - App 如何通过注入动态库的方式实现极速编译调试？.md
  
   - 07 - Clang、Infer 和 OCLint ，我们应该使用谁来做静态分析？.md
  
   - 08 - 如何利用 Clang 为 App 提质？.md
  
   - 09 - 无侵入的埋点方案如何实现？.md
  
   - 10 - 包大小：如何从资源和代码层面实现全方位瘦身？.md
  
   - 11 - 热点问题答疑（一）：基础模块问题答疑.md
  
   - 12 - iOS 崩溃千奇百怪，如何全面监控？.md
  
   - 13 - 如何利用 RunLoop 原理去监控卡顿？.md
  
   - 14 - 临近 OOM，如何获取详细内存分配信息，分析内存问题？.md
  
   - 15 - 日志监控：怎样获取 App 中的全量日志？.md
  
   - 16 - 性能监控：衡量 App 质量的那把尺.md
  
   - 17 - 远超你想象的多线程的那些坑.md
  
   - 18 - 怎么减少 App 电量消耗？.md
  
   - 19 - 热点问题答疑（二）：基础模块问题答疑.md
  
   - 20 - iOS开发的最佳学习路径是什么？.md
  
   - 21 - 除了 Cocoa，iOS还可以用哪些 GUI 框架开发？.md
  
   - 22 - 细说 iOS 响应式框架变迁，哪些思想可以为我所用？.md
  
   - 23 - 如何构造酷炫的物理效果和过场动画效果？.md
  
   - 24 - A-B 测试：验证决策效果的利器.md
  
   - 25 - 怎样构建底层的发布和订阅事件总线？.md
  
   - 26 - 如何提高 JSON 解析的性能？.md
  
   - 27 - 如何用 Flexbox 思路开发？跟自动布局比，Flexbox 好在哪？.md
  
   - 28 - 怎么应对各种富文本表现需求？.md
  
   - 29 - 如何在 iOS 中进行面向测试驱动开发和面向行为驱动开发？.md
  
   - 30 - 如何制定一套适合自己团队的 iOS 编码规范？.md
  
   - 31 - iOS 开发学习资料和书单推荐.md
  
   - 32 - 热点问题答疑（三）.md
  
   - 33 - iOS 系统内核 XNU：App 如何加载？.md
  
   - 34 - iOS 黑魔法 Runtime Method Swizzling 背后的原理.md
  
   - 35 - libffi：动态调用和定义 C 函数.md
  
   - 36 - iOS 是怎么管理内存的？.md
  
   - 37 - 如何编写 Clang 插件？.md
  
   - 38 - 热点问题答疑（四）.md
  
   - 39 - 打通前端与原生的桥梁：JavaScriptCore 能干哪些事情？.md
  
   - 40 - React Native、Flutter 等，这些跨端方案怎么选？.md
  
   - 41 - 原生布局转到前端布局，开发思路有哪些转变？.md
  
   - 42 - iOS原生、大前端和Flutter分别是怎么渲染的？.md
  
   - 43 - 剖析使 App 具有动态化和热更新能力的方案.md
  
   - 用户故事 - 我是如何学习这个专栏的？.md
  
   - 结束语 - 慢几步，深几度.md
  
   - 结课测试 - 这些iOS的开发知识你都掌握了吗？.md
  