site_name: 手把手教你落地DDD

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 手把手教你落地DDD.md
  
   - 开篇词-带你吃透DDD.md
  
   - 01-DDD小传：领域驱动设计为什么这么火？.md
  
   - 02-迭代一概述：怎样开启一个麻雀虽小五脏俱全的项目？.md
  
   - 03-事件风暴（上）：怎样和业务愉快地聊需求？.md
  
   - 04-事件风暴（下）：事件风暴还有哪些诀窍？.md
  
   - 05-领域建模实践（上）：怎样既准确又深刻地理解业务知识？.md
  
   - 06-领域建模实践（下）：领域建模还有什么其他技巧？.md
  
   - 07-领域建模原理：DDD领域建模和传统方法有什么区别？.md
  
   - 08-数据库设计：怎样按领域模型设计数据库？.md
  
   - 09-分层架构：怎样逃离“大泥球”？.md
  
   - 特别策划-AI是银弹么？.md
  
   - 10-代码实现（上）：要“贫血”还是要“充血”？.md
  
   - 11-代码实现（中）：怎样创建领域对象、实现领域逻辑？.md
  
   - 12-代码实现（下）：怎样更加“面向对象”？.md
  
   - 13-迭代二概述：怎样更深刻地理解领域知识？.md
  
   - 14-聚合的概念：怎样保护业务规则？.md
  
   - 15-聚合的实现（上）：怎样对聚合进行封装？.md
  
   - 16-聚合的实现（中）：怎样实现不变规则？.md
  
   - 17-聚合的实现（下）：怎样用事务保护聚合？.md
  
   - 18-值对象（上）：到底什么是值对象？.md
  
   - 19-值对象（中）：值对象有什么好处？.md
  
   - 20-值对象（下）：值对象和实体的本质区别是什么？.md
  
   - 21-用“限定”建模：怎样简化一对多关联？.md
  
   - 22-泛化建模（上）：领域知识更抽象怎么办？.md
  
   - 23-泛化建模（中）：可以不用泛化吗？.md
  
   - 24-泛化建模（下）：怎样权衡是否采用泛化？.md
  
   - 25-泛化的实现（上）：怎样为泛化设计数据库？.md
  
   - 26-泛化的实现（下）：怎样为泛化编写代码？.md
  
   - 27-迭代三概述：怎样处理规模更大的系统？.md
  
   - 28-限界上下文（上）：怎样为更大的需求建模？.md
  
   - 29-限界上下文（中）：限界上下文怎样影响架构设计？.md
  
   - 30-限界上下文（下）：限界上下文之间如何集成？.md
  
   - 31-CQRS（上）：实现查询功能有什么诀窍？.md
  
   - 32-CQRS（下）：CQRS还有哪些变化？.md
  
   - 33-分析模式初探：怎样解决更复杂的问题？.md
  
   - 34-落地经验：怎样在实际项目中推广DDD？.md
  
   - 加餐1-小试牛刀，测测你对DDD的掌握情况.md
  
   - 加餐2-读这些书，帮你学懂DDD.md
  
   - 加餐3-这些书里，藏着高手们的“不传之秘”.md
  
   - 加餐4-建模作业点评直播回放&获奖公示.md
  
   - 加餐5-DDD很难，学不会怎么办？.md
  
   - 用户故事-优秀软件方法学“漫游记”.md
  
   - 特别策划-AI时代程序员生存之道.md
  
   - 结束语-DDD，是技术也是艺术.md
  
   - 结课测试-来赴一场满分之约！.md
  