site_name: Linux内核技术实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Linux内核技术实战课.md
  
   - 开篇词 - 如何让Linux内核更好地服务应用程序？.md
  
   - 01 基础篇 - 如何用数据观测Page Cache？.md
  
   - 02 基础篇 - Page Cache是怎样产生和释放的？.md
  
   - 03 案例篇 - 如何处理Page Cache难以回收产生的load飙高问题？.md
  
   - 04 案例篇 - 如何处理Page Cache容易回收引起的业务性能问题？.md
  
   - 05 分析篇 - 如何判断问题是否由Page Cache产生的？.md
  
   - 06  基础篇 - 进程的哪些内存类型容易引起内存泄漏？.md
  
   - 07 案例篇 - 如何预防内存泄漏导致的系统假死？.md
  
   - 08 案例篇 - Shmem：进程没有消耗内存，内存哪去了？.md
  
   - 09 分析篇 - 如何对内核内存泄漏做些基础的分析？.md
  
   - 10 分析篇 - 内存泄漏时，我们该如何一步步找到根因？.md
  
   - 11 基础篇 - TCP连接的建立和断开受哪些系统配置影响？.md
  
   - 12 基础篇 - TCP收发包过程会受哪些配置项影响？.md
  
   - 13 案例篇 - TCP拥塞控制是如何导致业务性能抖动的？.md
  
   - 14 案例篇 -  TCP端到端时延变大，怎样判断是哪里出现了问题？.md
  
   - 15 分析篇 - 如何高效地分析TCP重传问题？.md
  
   - 16 套路篇 - 如何分析常见的TCP问题？.md
  
   - 17 基础篇 - CPU是如何执行任务的？.md
  
   - 18 案例篇 - 业务是否需要使用透明大页：水可载舟，亦可覆舟？.md
  
   - 19 案例篇 - 网络吞吐高的业务是否需要开启网卡特性呢？.md
  
   - 20 分析篇 - 如何分析CPU利用率飙高问题 ？.md
  
   - 加餐 - 我是如何使用tracepoint来分析内核Bug的？.md
  
   - 结束语 - 第一次看内核代码，我也很懵逼.md
  
   - 来领奖啦！你填写毕业问卷了吗？.md
  
   - 毕业问卷获奖用户名单.md
  
   - 结课测试 - 这些Linux内核技术实战技能你都掌握了吗？.md
  