site_name: 性能优化高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 性能优化高手课.md
  
   - 开篇词 - 与我一起修炼，成为一名软件性能大师吧！.md
  
   - 01 - 性能建模设计：如何满足软件设计中的性能需求？.md
  
   - 02 - 并行设计（上）：如何利用并行设计挖掘性能极限？.md
  
   - 03 - 并行设计（下）：如何高效解决同步互斥问题？.md
  
   - 04 - 缓存设计：做好缓存设计的关键是什么？.md
  
   - 05 - IO设计：如何设计IO交互来提升系统性能？.md
  
   - 06 - 通信设计：请不要让消息通信拖垮了系统的整体性能.md
  
   - 07 - 数据库选型：如何基于性能需求选择合适的数据库？.md
  
   - 08 - 可监控设计：如何利用eBPF来指导可监控设计？.md
  
   - 09 - 性能模式（上）：如何有效提升性能指标？.md
  
   - 10 - 性能模式（下）：如何解决核心的性能问题？.md
  
   - 11 - 如何针对特定业务场景设计数据结构和高性能算法？.md
  
   - 12 - 我们要先实现业务功能，还是先优化代码？.md
  
   - 13 - 编译期优化：只有修改业务代码才能提升系统性能？.md
  
   - 14 - 内存使用篇：如何高效使用内存来优化软件性能？.md
  
   - 15 - 并发实现：掌握不同并发框架的选择和使用秘诀.md
  
   - 16 - 技术探索：你真的把CPU的潜能都挖掘出来了吗？.md
  
   - 17 - Benchmark测试（上）：如何做好微基准测试？.md
  
   - 18 - Benchmark测试（下）：如何做好宏基准测试？.md
  
   - 19 - 性能测试工具：如何选择最合适的性能测试工具？.md
  
   - 20 - 性能看护： 如何更好地守护产品性能？.md
  
   - 21 - 性能CI：性能测试也可以集成到Pipeline中吗？.md
  
   - 22 - 性能调优方法论：如何科学高效地定位性能问题？.md
  
   - 23 - 监控分析：你的性能调优工具足够有效吗？.md
  
   - 24 - 动态监控：你的产品系统中有动态监控的能力吗？.md
  
   - 25 - 性能调优什么时候应该停止？.md
  
   - 26 - 一个嵌入式实时系统都要从哪些方面做好性能优化？.md
  
   - 27 - 解决一个互斥问题，系统并发用户数提升了10倍！.md
  
   - 28 - Web服务业务代码一行不动，性能提升20%，怎么做到的？.md
  
   - 结束语 - 千里之行，始于足下，你已踏上修炼之道！.md
  
   - 结课测试 - 《性能优化高手课》100分试卷等你来挑战！.md
  