site_name: Android开发高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Android开发高手课.md
  
   - 开篇词 - 焦虑的移动开发者该如何破局？.md
  
   - 导读 - 如何打造高质量的应用？.md
  
   - 01 - 崩溃优化（上）：关于“崩溃”那些事儿.md
  
   - 02 - 崩溃优化（下）：应用崩溃了，你应该如何去分析？.md
  
   - 03 - 内存优化（上）：4GB内存时代，再谈内存优化.md
  
   - 04 - 内存优化（下）：内存优化这件事，应该从哪里着手？.md
  
   - 05 - 卡顿优化（上）：你要掌握的卡顿分析方法.md
  
   - 06 - 卡顿优化（下）：如何监控应用卡顿？.md
  
   - 06补充篇 - 卡顿优化：卡顿现场与卡顿分析.md
  
   - 07 - 启动优化（上）：从启动过程看启动速度优化.md
  
   - 08 - 启动优化（下）：优化启动速度的进阶方法.md
  
   - 09 - I-O优化（上）：开发工程师必备的I-O优化知识.md
  
   - 10 - I-O优化（中）：不同I-O方式的使用场景是什么？.md
  
   - 11 - I-O优化（下）：如何监控线上I-O操作？.md
  
   - 12 - 存储优化（上）：常见的数据存储方法有哪些？.md
  
   - 13 - 存储优化（中）：如何优化数据存储？.md
  
   - 14 - 存储优化（下）：数据库SQLite的使用和优化.md
  
   - 15 - 网络优化（上）：移动开发工程师必备的网络优化知识.md
  
   - 16 - 网络优化（中）：复杂多变的移动网络该如何优化？.md
  
   - 17 - 网络优化（下）：大数据下网络该如何监控？.md
  
   - 18 - 耗电优化（上）：从电量优化的演进看耗电分析.md
  
   - 19 - 耗电优化（下）：耗电的优化方法与线上监控.md
  
   - 20 - UI 优化（上）：UI 渲染的几个关键概念.md
  
   - 21 - UI 优化（下）：如何优化 UI 渲染？.md
  
   - 22 - 包体积优化（上）：如何减少安装包大小？.md
  
   - 23 - 包体积优化（下）：资源优化的进阶实践.md
  
   - 24 - 想成为Android高手，你需要先搞定这三个问题.md
  
   - 25 - 如何提升组织与个人的研发效能？.md
  
   - 26 - 关于编译，你需要了解什么？.md
  
   - 27 - 编译插桩的三种方法：AspectJ、ASM、ReDex.md
  
   - 28 - 大数据与AI，如何高效地测试？.md
  
   - 29 - 从每月到每天，如何给版本发布提速？.md
  
   - 30 - 数据评估（上）：如何实现高可用的上报组件？.md
  
   - 31 - 数据评估（下）：什么是大数据平台？.md
  
   - 32 - 线上疑难问题该如何排查和跟踪？.md
  
   - 33 - 做一名有高度的移动开发工程师.md
  
   - 34 - 聊聊重构：优秀的架构都是演进而来的.md
  
   - 35 - Native Hook 技术，天使还是魔鬼？.md
  
   - 36 - 跨平台开发的现状与应用.md
  
   - 37 - 移动开发新大陆：工作三年半，移动开发转型手游开发.md
  
   - 38 - 移动开发新大陆：Android音视频开发.md
  
   - 39 - 移动开发新大陆： 边缘智能计算的趋势.md
  
   - 40 - 动态化实践，如何选择适合自己的方案？.md
  
   - 41 - 聊聊Flutter，面对层出不穷的新技术该如何跟进？.md
  
   - 42 - Android开发高手课学习心得.md
  
   - 练习Sample跑起来 - 热点问题答疑第1期.md
  
   - 练习Sample跑起来 - 热点问题答疑第2期.md
  
   - 练习Sample跑起来 - 热点问题答疑第3期.md
  
   - 练习Sample跑起来 - 热点问题答疑第4期.md
  
   - 练习Sample跑起来 - ASM插桩强化练习.md
  
   - 练习Sample跑起来 - 唯鹿同学的练习手记 第1辑.md
  
   - 练习Sample跑起来 - 唯鹿同学的练习手记 第2辑.md
  
   - 练习Sample跑起来 - 唯鹿同学的练习手记 第3辑.md
  
   - Android JVM TI机制详解（内含福利彩蛋）.md
  
   - 专栏学得苦？可能是方法没找对.md
  
   - 专栏学得苦？可能你还需要一份配套学习书单.md
  
   - Native下如何获取调用栈？.md
  
   - 聊聊Framework的学习方法.md
  
   - Android工程师的“面试指南”.md
  
   - 程序员修炼之路 - 设计能力的提升途径.md
  
   - 结束语 - 移动开发的今天和明天.md
  
   - 结课测试 - 这些Android知识，你都掌握了吗？.md
  