site_name: Python核心技术与实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Python核心技术与实战.md
  
   - 开篇词 - 从工程的角度深入理解Python.md
  
   - 01 - 如何逐步突破，成为Python高手？.md
  
   - 02 - Jupyter Notebook为什么是现代Python的必学技术？.md
  
   - 03 - 列表和元组，到底用哪一个？.md
  
   - 04 - 字典、集合，你真的了解吗？.md
  
   - 05 - 深入浅出字符串.md
  
   - 06 - Python “黑箱”：输入与输出.md
  
   - 07 - 修炼基本功：条件与循环.md
  
   - 08 - 异常处理：如何提高程序的稳定性？.md
  
   - 09 - 不可或缺的自定义函数.md
  
   - 10 - 简约不简单的匿名函数.md
  
   - 11 - 面向对象（上）：从生活中的类比说起.md
  
   - 12 - 面向对象（下）：如何实现一个搜索引擎？.md
  
   - 13 - 搭建积木：Python 模块化.md
  
   - 14 - 答疑（一）：列表和元组的内部实现是怎样的？.md
  
   - 15 - Python对象的比较、拷贝.md
  
   - 16 - 值传递，引用传递or其他，Python里参数是如何传递的？.md
  
   - 17 - 强大的装饰器.md
  
   - 18 - metaclass，是潘多拉魔盒还是阿拉丁神灯？.md
  
   - 19 - 深入理解迭代器和生成器.md
  
   - 20 - 揭秘 Python 协程.md
  
   - 21 - Python并发编程之Futures.md
  
   - 22 - 并发编程之Asyncio.md
  
   - 23 - 你真的懂Python GIL（全局解释器锁）吗？.md
  
   - 24 - 带你解析 Python 垃圾回收机制.md
  
   - 25 - 答疑（二）：GIL与多线程是什么关系呢？.md
  
   - 26 - 活都来不及干了，还有空注意代码风格？！.md
  
   - 27 - 学会合理分解代码，提高代码可读性.md
  
   - 28 - 如何合理利用assert？.md
  
   - 29 - 巧用上下文管理器和With语句精简代码.md
  
   - 30 - 真的有必要写单元测试吗？.md
  
   - 31 - pdb & cProfile：调试和性能分析的法宝.md
  
   - 32 - 答疑（三）：如何选择合适的异常处理方式？.md
  
   - 33 - 带你初探量化世界.md
  
   - 34 - RESTful & Socket：搭建交易执行层核心.md
  
   - 35 - RESTful & Socket：行情数据对接和抓取.md
  
   - 36 - Pandas & Numpy：策略与回测系统.md
  
   - 37 - Kafka & ZMQ：自动化交易流水线.md
  
   - 38 - MySQL：日志和数据存储系统.md
  
   - 39 - Django：搭建监控平台.md
  
   - 40 - 总结：Python中的数据结构与算法全景.md
  
   - 41 - 硅谷一线互联网公司的工作体验.md
  
   - 42 - 细数技术研发的注意事项.md
  
   - 加餐 - 带你上手SWIG：一份清晰好用的SWIG编程实践指南.md
  
   - 43 - Q&A：聊一聊职业发展和选择.md
  
   - 结束语 - 技术之外的几点成长建议.md
  
   - 结课测试 - 关于Python的这些知识，你都掌握了吗？.md
  