site_name: 后端工程师的高阶面经

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词｜面试如戏，台上一分钟，台下十年功.md
  
   - 01｜服务注册与发现_AP和CP，你选哪个_.md
  
   - 02｜负载均衡_调用结果、缓存机制是怎么影响负载均衡的_.md
  
   - 03｜熔断_熔断-恢复-熔断-恢复，抖来抖去怎么办_.md
  
   - 04｜降级_为什么每次大促的时候总是要把退款之类的服务停掉_.md
  
   - 05｜限流_别说算法了，就问你“阈值”怎么算_.md
  
   - 06｜隔离_怎么保证尊贵的VIP用户体验不受损_.md
  
   - 07｜超时控制_怎么保证用户一定能在1s内拿到响应_.md
  
   - 08｜调用第三方_下游的接口不稳定性能又差怎么办_.md
  
   - 09｜综合服务治理方案_怎么保证微服务应用的高可用_.md
  
   - 模拟面试（一）｜微服务架构面试思路一图懂.md
  
   - 10｜数据库索引_为什么MySQL用B&#43;树而不用B树_.md
  
   - 11｜SQL优化_如何发现SQL中的问题_.md
  
   - 12｜数据库锁_明明有行锁，怎么突然就加了表锁_.md
  
   - 13｜MVCC协议_MySQL在修改数据的时候，还能不能读到这条数据_.md
  
   - 14｜数据库事务_事务提交了，你的数据就一定不会丢吗_.md
  
   - 15｜数据迁移_如何在不停机的情况下保证迁移数据的一致性_.md
  
   - 16｜分库分表主键生成_如何设计一个主键生成算法_.md
  
   - 17｜分库分表分页查询_为什么你的分页查询又慢又耗费内存_.md
  
   - 18｜分布式事务_如何同时保证分库分表、ACID和高性能_.md
  
   - 19｜分库分表无分库分表键查询_你按照买家分库分表，那我卖家怎么查_.md
  
   - 20｜分库分表容量预估_分库分表的时候怎么计算需要多少个库多少个表_.md
  
   - 21｜数据库综合应用_怎么保证数据库的高可用、高性能_.md
  
   - 模拟面试｜数据库面试思路一图懂.md
  
   - 22｜消息队列_消息队列可以用来解决什么问题_.md
  
   - 23｜延迟消息_怎么在Kafka上支持延迟消息_.md
  
   - 24｜消息顺序_保证消息有序，一个topic只能有一个partition吗_.md
  
   - 25｜消息积压_业务突然增长，导致消息消费不过来怎么办_.md
  
   - 26｜消息不丢失_生产者收到写入成功响应后消息一定不会丢失吗_.md
  
   - 27｜重复消费_高并发场景下怎么保证消息不会重复消费_.md
  
   - 28｜架构设计_如果让你设计一个消息队列，你会怎么设计它的架构_.md
  
   - 29｜高性能_Kafka为什么性能那么好_.md
  
   - 30｜Kafka综合运用_怎么在实践中保证Kafka高性能_.md
  
   - 模拟面试｜消息队列面试思路一图懂.md
  
   - 31｜缓存过期_为什么Redis不立刻删除已经过期的数据_.md
  
   - 32｜缓存淘汰策略_怎么淘汰缓存命中率才不会下降_.md
  
   - 33｜缓存模式_缓存模式能不能解决缓存一致性问题_.md
  
   - 34｜缓存一致性问题_高并发服务如何保证缓存一致性_.md
  
   - 35｜缓存问题_怎么解决缓存穿透、击穿和雪崩问题_.md
  
   - 36｜Redis单线程_为什么Redis用单线程而Memcached用多线程_.md
  
   - 37｜分布式锁_如何保证Redis分布式锁的高可用和高性能_.md
  
   - 38｜缓存综合应用_怎么用缓存来提高整个应用的性能_.md
  
   - 模拟面试｜缓存面试思路一图懂.md
  
   - 39｜Elasticsearch高可用_怎么保证Elasticsearch的高可用_.md
  
   - 40｜Elasticsearch查询_怎么优化Elasticsearch的查询性能_.md
  
   - 41｜MongoDB_MongoDB是怎么做到高可用的_.md
  
   - 42｜MongoDB高性能_怎么优化MongoDB的查询性能_.md
  
   - 模拟面试｜NoSQL面试思路一图懂.md
  
   - 结束语｜未来掌握在自己手中.md
  
   - 结课测试｜来赴一场满分之约！.md
  
   - 直播加餐｜后端工程师如何在面试中脱颖而出_.md
  