site_name: 接口测试入门课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 接口测试入门课.md
  
   - 开篇词 - 把接口测试这件小事做深、做透.md
  
   - 01 - 基础：跳出细节看全局，接口测试到底是在做什么？.md
  
   - 02 - 方法论：没有任何文档，怎么才能快速了解接口的信息？.md
  
   - 03 - 思维方式：用一个案例彻底理解接口测试的关键逻辑.md
  
   - 04 - 案例：如何把流程化的测试脚本抽象为测试框架？.md
  
   - 05 - 案例：测试框架如何才能支持RESTful风格的接口？.md
  
   - 06 - 接口测试平台：工具和框架不可以兼容？.md
  
   - 07 - WebSocket接口：如何测试一个完全陌生的协议接口？.md
  
   - 08 - 测试数据：是不是可以把所有的参数都保存到Excel中？.md
  
   - 09 - 微服务接口：怎么用Mock解决混乱的调用关系？.md
  
   - 结束语 - 如何成为一名优秀的测试工程师？.md
  
   - 结课测试-这些接口测试知识你都掌握了吗？.md
  