site_name: 软件测试52讲

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 软件测试52讲.md
  
   - 开篇词 - 从“小工”到“专家”，我的软件测试修炼之道.md
  
   - 01 - 你真的懂测试吗？从“用户登录”测试谈起.md
  
   - 02 - 如何设计一个“好的”测试用例？.md
  
   - 03 - 什么是单元测试？如何做好单元测试？.md
  
   - 04 - 为什么要做自动化测试？什么样的项目适合做自动化测试？.md
  
   - 05 - 你知道软件开发各阶段都有哪些自动化测试技术吗？.md
  
   - 06 - 你真的懂测试覆盖率吗？.md
  
   - 07 - 如何高效填写软件缺陷报告？.md
  
   - 08 - 以终为始，如何才能做好测试计划？.md
  
   - 09 - 软件测试工程师的核心竞争力是什么？.md
  
   - 10 - 软件测试工程师需要掌握的非测试知识有哪些？.md
  
   - 11 - 互联网产品的测试策略应该如何设计？.md
  
   - 12 - 从0到1：你的第一个GUI自动化测试.md
  
   - 13 - 效率为王：脚本与数据的解耦 + Page Object模型.md
  
   - 14 - 更接近业务的抽象：让自动化测试脚本更好地描述业务.md
  
   - 15 - 过不了的坎：聊聊GUI自动化过程中的测试数据.md
  
   - 16 - 脑洞大开：GUI测试还能这么玩（Page Code Gen + Data Gen + Headless）？.md
  
   - 17 - 精益求精：聊聊提高GUI测试稳定性的关键技术.md
  
   - 18 - 眼前一亮：带你玩转GUI自动化的测试报告.md
  
   - 19 - 真实的战场：如何在大型项目中设计GUI自动化测试策略.md
  
   - 20 - 与时俱进：浅谈移动应用测试方法与思路.md
  
   - 21 - 移动测试神器：带你玩转Appium.md
  
   - 22 - 从0到1：API测试怎么做？常用API测试工具简介.md
  
   - 23 - 知其然知其所以然：聊聊API自动化测试框架的前世今生.md
  
   - 24 - 紧跟时代步伐：微服务模式下API测试要怎么做？.md
  
   - 25 - 不破不立：掌握代码级测试的基本理念与方法.md
  
   - 26 - 深入浅出之静态测试方法.md
  
   - 27 - 深入浅出之动态测试方法.md
  
   - 28 - 带你一起解读不同视角的软件性能与性能指标.md
  
   - 29 - 聊聊性能测试的基本方法与应用领域.md
  
   - 30 - 工欲善其事必先利其器：后端性能测试工具原理与行业常用工具简介.md
  
   - 31 - 工欲善其事必先利其器：前端性能测试工具原理与行业常用工具简介.md
  
   - 32 - 无实例无真相：基于LoadRunner实现企业级服务器端性能测试的实践（上）.md
  
   - 33 - 无实例无真相：基于LoadRunner实现企业级服务器端性能测试的实践（下）.md
  
   - 34 - 站在巨人的肩膀：企业级实际性能测试案例与经验分享.md
  
   - 35 - 如何准备测试数据？.md
  
   - 36 - 浅谈测试数据的痛点.md
  
   - 37 - 测试数据的“银弹”- 统一测试数据平台（上）.md
  
   - 38 - 测试数据的“银弹”- 统一测试数据平台（下）.md
  
   - 39 - 从小作坊到工厂：什么是Selenium Grid？如何搭建Selenium Grid？.md
  
   - 40 - 从小工到专家：聊聊测试执行环境的架构设计（上）.md
  
   - 41 - 从小工到专家：聊聊测试执行环境的架构设计（下）.md
  
   - 42 - 实战：大型全球化电商的测试基础架构设计.md
  
   - 43 - 发挥人的潜能：探索式测试.md
  
   - 44 - 测试先行：测试驱动开发(TDD).md
  
   - 45 - 打蛇打七寸：精准测试.md
  
   - 46 - 安全第一：渗透测试.md
  
   - 47 - 用机器设计测试用例：基于模型的测试.md
  
   - 48 - 优秀的测试工程师为什么要懂大型网站的架构设计？.md
  
   - 49 - 深入浅出网站高性能架构设计.md
  
   - 50 - 深入浅出网站高可用架构设计.md
  
   - 51 - 深入浅出网站伸缩性架构设计.md
  
   - 52 - 深入浅出网站可扩展性架构设计.md
  
   - 测试专栏特别放送 - 答疑解惑第一期.md
  
   - 测试专栏特别放送 - 答疑解惑第二期.md
  
   - 测试专栏特别放送 - 答疑解惑第三期.md
  
   - 测试专栏特别放送 - 答疑解惑第四期.md
  
   - 测试专栏特别放送 - 答疑解惑第五期.md
  
   - 测试专栏特别放送 - 答疑解惑第六期.md
  
   - 测试专栏特别放送 - 答疑解惑第七期.md
  
   - 测试专栏特别放送 - 浅谈全链路压测.md
  
   - 测一测 - 这些软件测试题目，你都掌握了吗？.md
  
   - 结束语 - 不是结束，而是开始.md
  