site_name: eBPF核心技术与实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - eBPF核心技术与实战.md
  
   - 开篇词 - 想要洞悉系统底层的黑盒？先掌握eBPF.md
  
   - 01-技术概览：eBPF的发展历程及工作原理.md
  
   - 02 - 先利其器：如何高效学习eBPF？.md
  
   - 03 - 初窥门径：开发并运行你的第一个eBPF程序.md
  
   - 04 - 运行原理：eBPF是一个新的虚拟机吗？.md
  
   - 05 - 编程接口：eBPF程序是怎么跟内核进行交互的？.md
  
   - 06 - 事件触发：各类eBPF程序的触发机制及其应用场景.md
  
   - 07 - 内核跟踪（上）：如何查询内核中的跟踪点？.md
  
   - 08-内核跟踪（下）：开发内核跟踪程序的进阶方法.md
  
   - 09 - 用户态跟踪：如何使用eBPF排查应用程序？.md
  
   - 10 - 网络跟踪：如何使用eBPF排查网络问题？.md
  
   - 11 - 容器安全：如何使用eBPF增强容器安全？.md
  
   - 12-高性能网络实战（上）：如何开发一个负载均衡器？.md
  
   - 13-高性能网络实战（下）：如何完善负载均衡器？.md
  
   - 大咖助场-李程远：谈谈eBPF在云原生中的纵与横.md
  
   - 用户故事-eBPF从入门到放弃？在实践中找到突破口.md
  
   - 14-阶段总结：实用eBPF工具及最新开源项目总结.md
  
   - 15-未来可期：邀你与eBPF共赴一场技术革新之约.md
  
   - 16-难点解析：eBPF开发环境搭建及内核编译详解.md
  
   - 17-难点解析：eBPF多内核版本兼容详解.md
  
   - 18-年度总结：eBPF的2022之旅.md
  
   - 19-案例解析：云原生网络Cilium详解.md
  
   - 20-学习路径：借助ChatGPT学习和实践eBPF.md
  
   - 21-平台移植：Windows平台上的eBPF实现.md
  
   - 22-技术解析：如何使用Go开发eBPF程序？.md
  
   - 23-年度总结：eBPF的2023之旅.md
  
   - 24-技术解析：HTTPS跟踪详解（上）.md
  
   - 25-技术解析：HTTPS跟踪详解（下）.md
  
   - 26-技术解析：eBPF程序参数原理详解.md
  