site_name: Spring编程常见错误50例

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Spring编程常见错误50例.md
  
   - 开篇词-贴心“保姆”Spring罢工了怎么办？.md
  
   - 导读-5分钟轻松了解Spring基础知识.md
  
   - 01-Spring Bean 定义常见错误.md
  
   - 02-Spring Bean 依赖注入常见错误（上）.md
  
   - 03-Spring Bean 依赖注入常见错误（下）.md
  
   - 04-Spring Bean 生命周期常见错误.md
  
   - 05-Spring AOP 常见错误（上）.md
  
   - 06-Spring AOP 常见错误（下）.md
  
   - 07-Spring事件常见错误.md
  
   - 08-答疑现场：Spring Core 篇思考题合集.md
  
   - 导读-5分钟轻松了解一个HTTP请求的处理过程.md
  
   - 09-Spring Web URL 解析常见错误.md
  
   - 10 - Spring Web Header 解析常见错误.md
  
   - 11 - Spring Web Body 转化常见错误.md
  
   - 12-Spring Web 参数验证常见错误.md
  
   - 13 - Spring Web 过滤器使用常见错误（上）.md
  
   - 14 - Spring Web 过滤器使用常见错误（下）.md
  
   - 15 - Spring Security 常见错误.md
  
   - 16-Spring Exception 常见错误.md
  
   - 17-答疑现场：Spring Web 篇思考题合集.md
  
   - 18 - Spring Data 常见错误.md
  
   - 19 - Spring 事务常见错误（上）.md
  
   - 20 - Spring 事务常见错误（下）.md
  
   - 21 - Spring Rest Template 常见错误.md
  
   - 22 - Spring Test 常见错误.md
  
   - 23-答疑现场：Spring 补充篇思考题合集.md
  
   - 知识回顾 - 系统梳理Spring编程错误根源.md
  
   - 结束语-问题总比解决办法多.md
  
   - 期末测试-来赴一场100分之约！.md
  