site_name: 深入拆解Tomcat & Jetty 

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 深入拆解Tomcat & Jetty .md
  
   - 开篇词 - Java程序员如何快速成长？.md
  
   - 01 - Web容器学习路径.md
  
   - 02 - HTTP协议必知必会.md
  
   - 03 - 你应该知道的Servlet规范和Servlet容器.md
  
   - 04 - 实战：纯手工打造和运行一个Servlet.md
  
   - 05 - Tomcat系统架构（上）： 连接器是如何设计的？.md
  
   - 06 - Tomcat系统架构（下）：聊聊多层容器的设计.md
  
   - 07 - Tomcat如何实现一键式启停？.md
  
   - 08 - Tomcat的“高层们”都负责做什么？.md
  
   - 09 - 比较：Jetty架构特点之Connector组件.md
  
   - 10 - 比较：Jetty架构特点之Handler组件.md
  
   - 11 - 总结：从Tomcat和Jetty中提炼组件化设计规范.md
  
   - 12 - 实战：优化并提高Tomcat启动速度.md
  
   - 13 - 热点问题答疑（1）：如何学习源码？.md
  
   - 14 - NioEndpoint组件：Tomcat如何实现非阻塞I-O？.md
  
   - 15 - Nio2Endpoint组件：Tomcat如何实现异步I-O？.md
  
   - 16 - AprEndpoint组件：Tomcat APR提高I-O性能的秘密.md
  
   - 17 - Executor组件：Tomcat如何扩展Java线程池？.md
  
   - 18 - 新特性：Tomcat如何支持WebSocket？.md
  
   - 19 - 比较：Jetty的线程策略EatWhatYouKill.md
  
   - 20 - 总结：Tomcat和Jetty中的对象池技术.md
  
   - 21 - 总结：Tomcat和Jetty的高性能、高并发之道.md
  
   - 22 - 热点问题答疑（2）：内核如何阻塞与唤醒进程？.md
  
   - 23 - Host容器：Tomcat如何实现热部署和热加载？.md
  
   - 24 - Context容器（上）：Tomcat如何打破双亲委托机制？.md
  
   - 25 - Context容器（中）：Tomcat如何隔离Web应用？.md
  
   - 26 - Context容器（下）：Tomcat如何实现Servlet规范？.md
  
   - 27 - 新特性：Tomcat如何支持异步Servlet？.md
  
   - 28 - 新特性：Spring Boot如何使用内嵌式的Tomcat和Jetty？.md
  
   - 29 - 比较：Jetty如何实现具有上下文信息的责任链？.md
  
   - 30 - 热点问题答疑（3）：Spring框架中的设计模式.md
  
   - 31 - Logger组件：Tomcat的日志框架及实战.md
  
   - 32 - Manager组件：Tomcat的Session管理机制解析.md
  
   - 33 - Cluster组件：Tomcat的集群通信原理.md
  
   - 特别放送 - 如何持续保持对学习的兴趣？.md
  
   - 34 - JVM GC原理及调优的基本思路.md
  
   - 35 - 如何监控Tomcat的性能？.md
  
   - 36 - Tomcat I-O和线程池的并发调优.md
  
   - 37 - Tomcat内存溢出的原因分析及调优.md
  
   - 38 - Tomcat拒绝连接原因分析及网络优化.md
  
   - 39 - Tomcat进程占用CPU过高怎么办？.md
  
   - 40 - 谈谈Jetty性能调优的思路.md
  
   - 41 - 热点问题答疑（4）： Tomcat和Jetty有哪些不同？.md
  
   - 结束语 - 静下心来，品味经典.md
  
   - 结课测试 - 这些Tomcat&Jetty的知识你都掌握了吗？.md
  