site_name: 消息队列高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 消息队列高手课.md
  
   - 再次起航-从“旁观者”视角再看消息队列.md
  
   - 如何实现消息保序？.md
  
   - 如何使用 Actor 模型解决并发问题？.md
  
   - 开篇词 - 优秀的程序员，你的技术栈中不能只有“增删改查”.md
  
   - 预习 - 怎样更好地学习这门课？.md
  
   - 01 - 为什么需要消息队列？.md
  
   - 02 - 该如何选择消息队列？.md
  
   - 03 - 消息模型：主题和队列有什么区别？.md
  
   - 04 - 如何利用事务消息实现分布式事务？.md
  
   - 05 - 如何确保消息不会丢失？.md
  
   - 06 - 如何处理消费过程中的重复消息？.md
  
   - 07 - 消息积压了该如何处理？.md
  
   - 08 - 答疑解惑（一） ： 网关如何接收服务端的秒杀结果？.md
  
   - 09 - 学习开源代码该如何入手？.md
  
   - 10 - 如何使用异步设计提升系统性能？.md
  
   - 11 - 如何实现高性能的异步网络传输？.md
  
   - 12 - 序列化与反序列化：如何通过网络传输结构化的数据？.md
  
   - 13 - 传输协议：应用程序之间对话的语言.md
  
   - 14 - 内存管理：如何避免内存溢出和频繁的垃圾回收？.md
  
   - 加餐 - JMQ的Broker是如何异步处理消息的？.md
  
   - 15 - Kafka如何实现高性能IO？.md
  
   - 16 - 缓存策略：如何使用缓存来减少磁盘IO？.md
  
   - 17 - 如何正确使用锁保护共享数据，协调异步线程？.md
  
   - 18 - 如何用硬件同步原语（CAS）替代锁？.md
  
   - 19 - 数据压缩：时间换空间的游戏.md
  
   - 20 - RocketMQ Producer源码分析：消息生产的实现过程.md
  
   - 21 - Kafka Consumer源码分析：消息消费的实现过程.md
  
   - 22 - Kafka和RocketMQ的消息复制实现的差异点在哪？.md
  
   - 23 - RocketMQ客户端如何在集群中找到正确的节点？.md
  
   - 24 - Kafka的协调服务ZooKeeper：实现分布式系统的“瑞士军刀”.md
  
   - 25 - RocketMQ与Kafka中如何实现事务？.md
  
   - 26 - MQTT协议：如何支持海量的在线IoT设备？.md
  
   - 27 - Pulsar的存储计算分离设计：全新的消息队列设计思路.md
  
   - 28 - 答疑解惑（二）：我的100元哪儿去了？.md
  
   - 29 - 流计算与消息（一）：通过Flink理解流计算的原理.md
  
   - 30 - 流计算与消息（二）：在流计算中使用Kafka链接计算任务.md
  
   - 31 - 动手实现一个简单的RPC框架（一）：原理和程序的结构.md
  
   - 32 - 动手实现一个简单的RPC框架（二）：通信与序列化.md
  
   - 33 - 动手实现一个简单的RPC框架（三）：客户端.md
  
   - 34 - 动手实现一个简单的RPC框架（四）：服务端.md
  
   - 35 - 答疑解惑（三）：主流消息队列都是如何存储消息的？.md
  
   - 期中测试丨10个消息队列热点问题自测.md
  
   - 期末测试 - 消息队列100分试卷等你来挑战！.md
  
   - 结束语 - 程序员如何构建知识体系？.md
  
   - 第二季回归丨这次我们一起实战后端存储.md
  