site_name: Vue 3 企业级项目实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Vue 3 企业级项目实战课.md
  
   - 开篇词-为何掌握了技术API，依然在项目中处处掣肘？.md
  
   - 01-编译和非编译模式：离开Vue工具，你还知道怎么用Vue 3吗？.md
  
   - 02-Webpack编译搭建：如何用Webpack初构建Vue 3项目？.md
  
   - 03-从Rollup到Vite：如何用Vite构建你的Vue 3项目？.md
  
   - 04-模版语法和JSX语法：你知道Vue可以用JSX写吗？.md
  
   - 05-响应式开发操作：如何理解和使用Vue 3的响应式数据？.md
  
   - 06-跨组件数据通信：常见的组件间数据通信方式有哪些？.md
  
   - 07-项目代码规范：如何成为一名合格的团队协作工程师？.md
  
   - 加餐-基础篇思考题答疑.md
  
   - 08-如何从零搭建自研的Vue组件库？.md
  
   - 09-主题方案和基础组件：如何设计组件库的主题方案？.md
  
   - 10-动态渲染组件：如何实现Vue的动态渲染组件？.md
  
   - 11-布局组件：如何实现自研组件库的布局方案？.md
  
   - 12-受控表单组件：如何开发受控的表单组件？.md
  
   - 13-动态表单组件：怎么优雅地动态渲染表单？.md
  
   - 14-代码单元测试：如何轻松地保证自己的代码质量？.md
  
   - 加餐-进阶篇思考题答疑.md
  
   - 围炉夜话-学了新技术，在公司用不上怎么办？.md
  
   - 围炉夜话-Leader 眼里最有潜力的仔长什么样？.md
  
   - 围炉夜话-你的职业起点和职业终点是什么？.md
  
   - 15-定制运营拖拽组件：如何实现运营搭建页面的拖拽功能？.md
  
   - 16-单页面应用：如何理解和实现单页面应用开发？.md
  
   - 17-Koa.js：如何结合Koa.js开发Node.js Web服务？.md
  
   - 18-Node.js服务端渲染页面：客户端渲染和服务端渲染有何区别？.md
  
   - 19-全栈项目搭建：如何搭建Vue.js的前后台全栈项目？.md
  
   - 20-数据库方案设计：如何设计运营搭建平台的数据库？.md
  
   - 21-用户注册和登录：如何结合Vue 3和Koa.js实现注册登录？.md
  
   - 22-物料组件的编译和管理：如何处理组件的多种模块格式？.md
  
   - 23-运营物料的后台管理：如何全栈化实现列表分页的功能？.md
  
   - 加餐-实战篇思考题答疑（上）.md
  
   - 24-后台搭建数据源：如何设计运营搭建页面的数据结构？.md
  
   - 25-后台搭建功能：如何设计和实现Vue.js运营后台的搭建功能？.md
  
   - 26-页面编译和运行：如何设计Vue.js搭建页面的渲染策略？.md
  
   - 27-后台发布流程：如何实现Vue.js搭建页面的发布流程？.md
  
   - 28-前台页面版本化管理：如何实现搭建页面的迭代策略？.md
  
   - 29-前台页面的渲染方式：如何设计前台页面的渲染策略？.md
  
   - 30-前台页面的性能优化：如何实现前台页面的性能优化？.md
  
   - 31-前台页面的日志监控：如何进行页面实时监控与问题定位？.md
  
   - 加餐-实战篇思考题答疑（下）.md
  
   - 32-单元测试：如何打造Vue.js和Node.js全栈项目的单元测试？.md
  
   - 33-页面功能扩展：如何对Vue.js全栈项目做优雅扩展？.md
  
   - 34-服务端功能扩展：如何对Vue.js全栈项目做服务端功能扩展？.md
  
   - 35-多进程部署：如何最大限度利用服务器资源运行Node.js服务？.md
  
   - 36-日志收集与问题排错：如何守护好Vue.js和Node.js的全栈项目？.md
  
   - 加餐-增强篇思考题答疑.md
  
   - 结束语-时刻做好“军备竞赛”，机会只留给有准备的人.md
  
   - 期末测试-来赴一场满分之约！.md
  