site_name: 安全攻防技能30讲

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 安全攻防技能30讲.md
  
   - 开篇词 - 别说你没被安全困扰过.md
  
   - 01 - 安全的本质：数据被窃取后，你能意识到问题来源吗？.md
  
   - 02 - 安全原则：我们应该如何上手解决安全问题？.md
  
   - 03 - 密码学基础：如何让你的密码变得“不可见”？.md
  
   - 04 - 身份认证：除了账号密码，我们还能怎么做身份认证？.md
  
   - 05 - 访问控制：如何选取一个合适的数据保护方案？.md
  
   - 06 - XSS：当你“被发送”了一条微博时，到底发生了什么？.md
  
   - 07 - SQL注入：明明设置了强密码，为什么还会被别人登录？.md
  
   - 08 - CSRF-SSRF：为什么避免了XSS，还是“被发送”了一条微博？.md
  
   - 09 - 反序列化漏洞：使用了编译型语言，为什么还是会被注入？.md
  
   - 10 - 信息泄露：为什么黑客会知道你的代码逻辑？.md
  
   - 11 - 插件漏洞：我的代码看起来很安全，为什么还会出现漏洞？.md
  
   - 12 - 权限提升和持久化：为什么漏洞修复了，黑客还是能够自由进出？.md
  
   - 13 - Linux系统安全：多人共用服务器，如何防止别人干“坏事”？.md
  
   - 14 - 网络安全：和别人共用Wi-Fi时，你的信息会被窃取吗？.md
  
   - 15 - Docker安全：在虚拟的环境中，就不用考虑安全了吗？.md
  
   - 16 - 数据库安全：数据库中的数据是如何被黑客拖取的？.md
  
   - 17 - 分布式安全：上百个分布式节点，不会出现“内奸”吗？.md
  
   - 18 - 安全标准和框架：怎样依“葫芦”画出好“瓢”？.md
  
   - 19 - 防火墙：如何和黑客“划清界限”？.md
  
   - 20 - WAF：如何为漏洞百出的Web应用保驾护航？.md
  
   - 21 - IDS：当黑客绕过了防火墙，你该如何发现？.md
  
   - 22 - RASP：写规则写得烦了？尝试一下更底层的IDS.md
  
   - 23 - SIEM：一个人管理好几个安全工具，如何高效运营？.md
  
   - 24 - SDL：怎样才能写出更“安全”的代码？.md
  
   - 25 - 业务安全体系：对比基础安全，业务安全有哪些不同？.md
  
   - 26 - 产品安全方案：如何降低业务对黑灰产的诱惑？.md
  
   - 27 - 风控系统：如何从海量业务数据中，挖掘黑灰产？.md
  
   - 28 - 机器学习：如何教会机器识别黑灰产？.md
  
   - 29 - 设备指纹：面对各种虚拟设备，如何进行对抗？.md
  
   - 30 - 安全运营：“黑灰产”打了又来，如何正确处置？.md
  
   - 模块串讲（一）- Web安全：如何评估用户数据和资产数据面临的威胁？.md
  
   - 模块串讲（二）- Linux系统和应用安全：如何大范围提高平台安全性？.md
  
   - 模块串讲（三）- 安全防御工具：如何选择和规划公司的安全防御体系？.md
  
   - 加餐1 - 数据安全：如何防止内部员工泄露商业机密？.md
  
   - 加餐2 - 前端安全：如何打造一个可信的前端环境？.md
  
   - 加餐3 - 职业发展：应聘安全工程师，我需要注意什么？.md
  
   - 加餐4 - 个人成长：学习安全，哪些资源我必须要知道？.md
  
   - 加餐5 -  安全新技术：IoT、IPv6、区块链中的安全新问题.md
  
   - 结束语 - 在与黑客的战役中，我们都是盟友！.md
  
   - 结课测试-这些安全知识，你都掌握了吗？.md
  