site_name: 深入剖析Kubernetes

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 深入剖析Kubernetes.md
  
   - 开篇词 - 打通“容器技术”的任督二脉.md
  
   - 01 - 预习篇 · 小鲸鱼大事记（一）：初出茅庐.md
  
   - 02 - 预习篇 · 小鲸鱼大事记（二）：崭露头角.md
  
   - 03 - 预习篇 · 小鲸鱼大事记（三）：群雄并起.md
  
   - 04 - 预习篇 · 小鲸鱼大事记（四）：尘埃落定.md
  
   - 05 - 白话容器基础（一）：从进程说开去.md
  
   - 06 - 白话容器基础（二）：隔离与限制.md
  
   - 07 - 白话容器基础（三）：深入理解容器镜像.md
  
   - 08 - 白话容器基础（四）：重新认识Docker容器.md
  
   - 09 - 从容器到容器云：谈谈Kubernetes的本质.md
  
   - 10 - Kubernetes一键部署利器：kubeadm.md
  
   - 11 - 从0到1：搭建一个完整的Kubernetes集群.md
  
   - 12 - 牛刀小试：我的第一个容器化应用.md
  
   - 13 - 为什么我们需要Pod？.md
  
   - 14 - 深入解析Pod对象（一）：基本概念.md
  
   - 15 - 深入解析Pod对象（二）：使用进阶.md
  
   - 16 - 编排其实很简单：谈谈“控制器”模型.md
  
   - 17 - 经典PaaS的记忆：作业副本与水平扩展.md
  
   - 18 - 深入理解StatefulSet（一）：拓扑状态.md
  
   - 19 - 深入理解StatefulSet（二）：存储状态.md
  
   - 20 - 深入理解StatefulSet（三）：有状态应用实践.md
  
   - 21 - 容器化守护进程的意义：DaemonSet.md
  
   - 22 - 撬动离线业务：Job与CronJob.md
  
   - 23 - 声明式API与Kubernetes编程范式.md
  
   - 24 - 深入解析声明式API（一）：API对象的奥秘.md
  
   - 25 - 深入解析声明式API（二）：编写自定义控制器.md
  
   - 26 - 基于角色的权限控制：RBAC.md
  
   - 27 - 聪明的微创新：Operator工作原理解读.md
  
   - 28 - PV、PVC、StorageClass，这些到底在说啥？.md
  
   - 29 - PV、PVC体系是不是多此一举？从本地持久化卷谈起.md
  
   - 30 - 编写自己的存储插件：FlexVolume与CSI.md
  
   - 31 - 容器存储实践：CSI插件编写指南.md
  
   - 32 - 浅谈容器网络.md
  
   - 33 - 深入解析容器跨主机网络.md
  
   - 34 - Kubernetes网络模型与CNI网络插件.md
  
   - 35 - 解读Kubernetes三层网络方案.md
  
   - 36 - 为什么说Kubernetes只有soft multi-tenancy？.md
  
   - 37 - 找到容器不容易：Service、DNS与服务发现.md
  
   - 38 - 从外界连通Service与Service调试“三板斧”.md
  
   - 39 - 谈谈Service与Ingress.md
  
   - 40 - Kubernetes的资源模型与资源管理.md
  
   - 41 - 十字路口上的Kubernetes默认调度器.md
  
   - 42 - Kubernetes默认调度器调度策略解析.md
  
   - 43 - Kubernetes默认调度器的优先级与抢占机制.md
  
   - 44 - Kubernetes GPU管理与Device Plugin机制.md
  
   - 45 - 幕后英雄：SIG-Node与CRI.md
  
   - 46 - 解读 CRI 与 容器运行时.md
  
   - 47 - 绝不仅仅是安全：Kata Containers 与 gVisor.md
  
   - 48 - Prometheus、Metrics Server与Kubernetes监控体系.md
  
   - 49 - Custom Metrics： 让Auto Scaling不再“食之无味”.md
  
   - 50 - 让日志无处可逃：容器日志收集与管理.md
  
   - 51 - 谈谈Kubernetes开源社区和未来走向.md
  
   - 52 - 答疑：在问题中解决问题，在思考中产生思考.md
  
   - 特别放送 - 2019 年，容器技术生态会发生些什么？.md
  
   - 特别放送 - 基于 Kubernetes 的云原生应用管理，到底应该怎么做？.md
  
   - 结束语 - Kubernetes：赢开发者赢天下.md
  
   - 结课测试-这些Kubernetes的相关知识，你都掌握了吗？.md
  