site_name: 浏览器工作原理与实践

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 浏览器工作原理与实践.md
  
   - 开篇词 - 参透了浏览器的工作原理，你就能解决80%的前端难题.md
  
   - 01 - Chrome架构：仅仅打开了1个页面，为什么有4个进程？.md
  
   - 02 - TCP协议：如何保证页面文件能被完整送达浏览器？.md
  
   - 03 - HTTP请求流程：为什么很多站点第二次打开速度会很快？.md
  
   - 04 - 导航流程：从输入URL到页面展示，这中间发生了什么？.md
  
   - 05 - 渲染流程（上）：HTML、CSS和JavaScript，是如何变成页面的？.md
  
   - 06 - 渲染流程（下）：HTML、CSS和JavaScript，是如何变成页面的？.md
  
   - 07 - 变量提升：JavaScript代码是按顺序执行的吗？.md
  
   - 08 - 调用栈：为什么JavaScript代码会出现栈溢出？.md
  
   - 09 - 块级作用域：var缺陷以及为什么要引入let和const？.md
  
   - 10 - 作用域链和闭包 ：代码中出现相同的变量，JavaScript引擎是如何选择的？.md
  
   - 11 - this：从JavaScript执行上下文的视角讲清楚this.md
  
   - 12 - 栈空间和堆空间：数据是如何存储的？.md
  
   - 13 - 垃圾回收：垃圾数据是如何自动回收的？.md
  
   - 14 - 编译器和解释器：V8是如何执行一段JavaScript代码的？.md
  
   - 15 - 消息队列和事件循环：页面是怎么“活”起来的？.md
  
   - 16 - WebAPI：setTimeout是如何实现的？.md
  
   - 17 - WebAPI：XMLHttpRequest是怎么实现的？.md
  
   - 18 - 宏任务和微任务：不是所有任务都是一个待遇.md
  
   - 19 - Promise：使用Promise，告别回调函数.md
  
   - 20 - async-await：使用同步的方式去写异步代码.md
  
   - 21 - Chrome开发者工具：利用网络面板做性能分析.md
  
   - 22 - DOM树：JavaScript是如何影响DOM树构建的？.md
  
   - 23 - 渲染流水线：CSS如何影响首次加载时的白屏时间？.md
  
   - 24 - 分层和合成机制：为什么CSS动画比JavaScript高效？.md
  
   - 25 - 页面性能：如何系统地优化页面？.md
  
   - 26 - 虚拟DOM：虚拟DOM和实际的DOM有何不同？.md
  
   - 27 - 渐进式网页应用（PWA）：它究竟解决了Web应用的哪些问题？.md
  
   - 28 - WebComponent：像搭积木一样构建Web应用.md
  
   - 29 - HTTP-1：HTTP性能优化.md
  
   - 30-HTTP-2：如何提升网络速度？.md
  
   - 31-HTTP-3：甩掉TCP、TLS 的包袱，构建高效网络.md
  
   - 32 - 同源策略：为什么XMLHttpRequest不能跨域请求资源？.md
  
   - 33 - 跨站脚本攻击（XSS）：为什么Cookie中有HttpOnly属性？.md
  
   - 34 - CSRF攻击：陌生链接不要随便点.md
  
   - 35 - 安全沙箱：页面和系统之间的隔离墙.md
  
   - 36 - HTTPS：让数据传输更安全.md
  
   - 结束语 - 大道至简.md
  
   - 第二季回归 - 这次我们来专门聊聊V8.md
  
   - 结课测试 - 这些浏览器的知识你都掌握了吗？.md
  
   - 加餐一-浏览上下文组：如何计算Chrome中渲染进程的个数？.md
  
   - 加餐二-任务调度：有了setTimeOut，为什么还要使用rAF？.md
  
   - 加餐三-加载阶段性能：使用Audits来优化Web性能.md
  
   - 加餐四-页面性能工具：如何使用Performance？.md
  
   - 加餐五 - 性能分析工具：如何分析Performance中的Main指标？.md
  
   - 加餐六-HTTPS：浏览器如何验证数字证书？.md
  