site_name: MySQL运维实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - MySQL运维实战课.md
  
   - 开篇词-理论+实践，带你解决90%以上的MySQL运维问题.md
  
   - 01-快速上手数据库安装部署.md
  
   - 02-MySQL账号和权限管理.md
  
   - 03-数据库连接问题诊断分析.md
  
   - 04-MySQL中不同类型的参数与参数配置.md
  
   - 05-你用对数据类型了吗？.md
  
   - 06-SQL Mode对程序有怎样的影响？.md
  
   - 07-乱码是怎么产生的，以及如何避免？.md
  
   - 08-程序访问数据库内存溢出怎么解决？.md
  
   - 09-MySQL如何快速导入导出数据？（上）.md
  
   - 10-MySQL如何快速导入导出数据？（下）.md
  
   - 11-表太大了，修改表结构太慢怎么解决？（上）.md
  
   - 12-表太大了，修改表结构太慢怎么解决？（下）.md
  
   - 13-定位MySQL问题的思路：数据库为什么慢了？.md
  
   - 14-Linux问题诊断入门：操作系统是否存在瓶颈？.md
  
   - 15-非典型数据库故障解析：数据库故障一定是数据库的锅吗？.md
  
   - 16-如何在不影响业务的情况下平滑升级MySQL？.md
  
   - 17-SQL优化第一步：理解访问路径.md
  
   - 18-读懂MySQL中的执行计划（上）.md
  
   - 18-读懂MySQL中的执行计划（下）.md
  
   - 19-优化器成本模型：优化器为什么选择这个执行计划？.md
  
   - 20-单表查询：如何评估单表访问成本？.md
  
   - 21-表连接如何执行？.md
  
   - 22-MySQL子查询优化策略.md
  
   - 23-10+ SQL执行性能不佳的真实案例（上）.md
  
   - 24-10+ SQL执行性能不佳的真实案例（下）.md
  
   - 25-数据库无法启动，如何读取InnoDB文件中的数据？（上）.md
  
   - 26-数据库无法启动，如何读取InnoDB文件中的数据？（下）.md
  
   - 27-InnoDB Buffer Pool 如何提高数据库性能？(上）.md
  
   - 28-InnoDB Buffer Pool如何提高数据库性能？(下）.md
  
   - 29-数据都在内存里修改，服务器或数据库宕机会丢数据吗？.md
  
   - 30-事务怎么回滚？（上）.md
  
   - 31-事务怎么回滚？（下）.md
  
   - 32-隔离级别对应用程序有什么影响？.md
  
   - 33- InnoDB锁定和死锁问题：为什么我的SQL锁超时了？.md
  
   - 34-MySQL数据库高可用架构部署和维护.md
  
   - 35-MySQL半同步能提高主备数据的一致性吗？.md
  
   - 36-备库有延迟怎么办？.md
  
   - 37-备库服务器异常重启，备库损坏了该如何修复？.md
  
   - 38-为什么有了备库还要做备份？兼谈 Xtrabackup 的使用.md
  
   - 39-数据误操作了如何快速恢复？.md
  
   - 40-MySQL 8.0 Clone 插件的应用和内部原理.md
  
   - 41-MySQL 8.0 组复制技术的应用（上）.md
  
   - 42-MySQL 8.0 组复制技术的应用（下）.md
  
   - 43-ProxySQL：数据库高可用了，应用高可用怎么做？.md
  
   - 44-如何搭建一个 MySQL 监控平台？.md
  
   - 45-MySQL源码分析和GDB调试器的应用.md
  
   - 结束语-如何系统地掌握一门数据库技术？.md
  
   - 结课测试-来赴一场满分之约吧.md
  
   - 基础篇-课后题答疑.md
  
   - SQL优化篇-课后题答疑.md
  
   - InnoDB存储引擎篇-课后题答疑.md
  
   - 高可用篇-课后题答疑.md
  