site_name: 容器实战高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 容器实战高手课.md
  
   - 开篇词 - 一个态度两个步骤，成为容器实战高手.md
  
   - 01 - 认识容器：容器的基本操作和实现原理.md
  
   - 02 - 理解进程（1）：为什么我在容器中不能kill 1号进程？.md
  
   - 03-理解进程（2）：为什么我的容器里有这么多僵尸进程？.md
  
   - 04 - 理解进程（3）：为什么我在容器中的进程被强制杀死了？.md
  
   - 05-容器CPU（1）：怎么限制容器的CPU使用？.md
  
   - 06 - 容器CPU（2）：如何正确地拿到容器CPU的开销？.md
  
   - 07 - Load Average：加了CPU Cgroup限制，为什么我的容器还是很慢？.md
  
   - 08 - 容器内存：我的容器为什么被杀了？.md
  
   - 09 - Page Cache：为什么我的容器内存使用量总是在临界点？.md
  
   - 10 - Swap：容器可以使用Swap空间吗？.md
  
   - 11 - 容器文件系统：我在容器中读写文件怎么变慢了？.md
  
   - 12 - 容器文件Quota：容器为什么把宿主机的磁盘写满了？.md
  
   - 13 - 容器磁盘限速：我的容器里磁盘读写为什么不稳定？.md
  
   - 14 - 容器中的内存与I-O：容器写文件的延时为什么波动很大？.md
  
   - 15 - 容器网络：我修改了-proc-sys-net下的参数，为什么在容器中不起效？.md
  
   - 16 - 容器网络配置（1）：容器网络不通了要怎么调试？.md
  
   - 17-容器网络配置（2）：容器网络延时要比宿主机上的高吗？.md
  
   - 18 - 容器网络配置（3）：容器中的网络乱序包怎么这么高？.md
  
   - 19 - 容器安全（1）：我的容器真的需要privileged权限吗？.md
  
   - 20 - 容器安全（2）：在容器中，我不以root用户来运行程序可以吗？.md
  
   - 结束语 - 跳出舒适区，突破思考的惰性.md
  
   - 结课测试-这些容器技术的问题，你都掌握了么？.md
  
   - 用户故事 - 莫名：相信坚持的力量，终会厚积薄发.md
  
   - 加餐福利 - 课后思考题答案合集.md
  
   - 加餐01 - 案例分析：怎么解决海量IPVS规则带来的网络延时抖动问题？.md
  
   - 加餐02 - 理解perf：怎么用perf聚焦热点函数？.md
  
   - 加餐03 - 理解ftrace（1）：怎么应用ftrace查看长延时内核函数？.md
  
   - 加餐04 - 理解ftrace（2）：怎么理解ftrace背后的技术tracepoint和kprobe？.md
  
   - 加餐05 - eBPF：怎么更加深入地查看内核中的函数？.md
  
   - 加餐06 - BCC：入门eBPF的前端工具.md
  