site_name: 朱涛 · Kotlin编程第一课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 朱涛 · Kotlin编程第一课.md
  
   - 开篇词 - 入门Kotlin有多容易，精通Kotlin就有多难.md
  
   - 01 - Kotlin基础语法：正式开启学习之旅.md
  
   - 02 - 面向对象：理解Kotlin设计者的良苦用心.md
  
   - 03 - Kotlin原理：编译器在幕后干了哪些“好事”？.md
  
   - 04 - 实战：构建一个Kotlin版本的四则运算计算器.md
  
   - 05 - object关键字：你到底有多少种用法？.md
  
   - 06 - 扩展：你的能力边界到底在哪里？.md
  
   - 07 - 高阶函数：为什么说函数是Kotlin的“一等公民”？.md
  
   - 08 - 实战：用Kotlin写一个英语词频统计程序.md
  
   - 加餐一 - 初识Kotlin函数式编程.md
  
   - 09 - 委托：你为何总是被低估？.md
  
   - 10 - 泛型：逆变or协变，傻傻分不清？.md
  
   - 11 - 注解与反射：进阶必备技能.md
  
   - 12 - 实战：用Kotlin实现一个网络请求框架KtHttp.md
  
   - 加餐二 - 什么是“表达式思维”？.md
  
   - 加餐三 - 什么是“不变性思维”？.md
  
   - 加餐四 - 什么是“空安全思维”？.md
  
   - 春节刷题计划（一）- 当Kotlin遇上LeetCode.md
  
   - 春节刷题计划（二）- 一题三解，搞定版本号判断.md
  
   - 春节刷题计划（三）- 一题双解，搞定求解方程.md
  
   - 春节刷题计划（四）- 一题三解，搞定分式加减法.md
  
   - 13 - 什么是“协程思维模型”？.md
  
   - 14 - 如何启动协程？.md
  
   - 15 - 挂起函数：Kotlin协程的核心.md
  
   - 16 - Job：协程也有生命周期吗？.md
  
   - 17 - Context：万物皆为Context？.md
  
   - 18 - 实战：让KtHttp支持挂起函数.md
  
   - 期中考试 - 用Kotlin实现图片处理程序.md
  
   - 题目解答 - 期中考试版本参考实现.md
  
   - 19 - Channel：为什么说Channel是“热”的？.md
  
   - 20 - Flow：为什么说Flow是“冷”的？.md
  
   - 21 - select：到底是在选择什么？.md
  
   - 22 - 并发：协程不需要处理同步吗？.md
  
   - 23 - 异常：try-catch居然会不起作用？坑！.md
  
   - 24 - 实战：让KtHttp支持Flow.md
  
   - 答疑（一）- Java和Kotlin到底谁好谁坏？.md
  
   - 25 - 集合操作符：你也会“看完就忘”吗？.md
  
   - 26 - 协程源码的地图：如何读源码才不会迷失？.md
  
   - 27 - 图解挂起函数：原来你就是个状态机？.md
  
   - 加餐五 - 深入理解协程基础元素.md
  
   - 28 - launch的背后到底发生了什么？.md
  
   - 29 - Dispatchers是如何工作的？.md
  
   - 30 - CoroutineScope是如何管理协程的？.md
  
   - 31 - 图解Channel：如何理解它的CSP通信模型？.md
  
   - 32 - 图解Flow：原来你是只纸老虎？.md
  
   - 33 - Java Android开发者还会有未来吗？.md
  
   - 34 - Kotlin与Jetpack简直是天生一对！.md
  
   - 35 - 用Kotlin写一个GitHub Trending App.md
  
   - 结课测试 - “Kotlin编程第一课”100分试卷等你来挑战！.md
  
   - 结束语 - 不忘初心.md
  