site_name: AI技术内参

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - AI技术内参.md
  
   - 开篇词 - 你的360度人工智能信息助理.md
  
   - 001 - 聊聊2017年KDD大会的时间检验奖.md
  
   - 002 - 精读2017年KDD最佳研究论文.md
  
   - 003 - 精读2017年KDD最佳应用数据科学论文.md
  
   - 004 - 精读2017年EMNLP最佳长论文之一.md
  
   - 005 - 精读2017年EMNLP最佳长论文之二.md
  
   - 006 - 精读2017年EMNLP最佳短论文.md
  
   - 007 - 精读2017年ICCV最佳研究论文.md
  
   - 008 - 精读2017年ICCV最佳学生论文.md
  
   - 009 - 如何将“深度强化学习”应用到视觉问答系统？.md
  
   - 010 - 精读2017年NIPS最佳研究论文之一：如何解决非凸优化问题？.md
  
   - 011 - 精读2017年NIPS最佳研究论文之二：KSD测试如何检验两个分布的异同？.md
  
   - 012 - 精读2017年NIPS最佳研究论文之三：如何解决非完美信息博弈问题？.md
  
   - 013 - WSDM 2018论文精读：看谷歌团队如何做位置偏差估计.md
  
   - 014 - WSDM 2018论文精读：看京东团队如何挖掘商品的替代信息和互补信息.md
  
   - 015 - WSDM 2018论文精读：深度学习模型中如何使用上下文信息？.md
  
   - 016 - The Web 2018论文精读：如何对商品的图片美感进行建模？.md
  
   - 017 - The Web 2018论文精读：如何改进经典的推荐算法BPR？.md
  
   - 018 - The Web 2018论文精读：如何从文本中提取高元关系？.md
  
   - 019 - SIGIR 2018论文精读：偏差和“流行度”之间的关系.md
  
   - 020 - SIGIR 2018论文精读：如何利用对抗学习来增强排序模型的普适性？.md
  
   - 021 - SIGIR 2018论文精读：如何对搜索页面上的点击行为进行序列建模？.md
  
   - 022 - CVPR 2018论文精读：如何研究计算机视觉任务之间的关系？.md
  
   - 023 - CVPR 2018论文精读：如何从整体上对人体进行三维建模？.md
  
   - 024 - CVPR 2018论文精读：如何解决排序学习计算复杂度高这个问题？.md
  
   - 025 - ICML 2018论文精读：模型经得起对抗样本的攻击？这或许只是个错觉.md
  
   - 026 - ICML 2018论文精读：聊一聊机器学习算法的“公平性”问题.md
  
   - 027 - ICML 2018论文精读：优化目标函数的时候，有可能放大了“不公平”？.md
  
   - 028 - ACL 2018论文精读：问答系统场景下，如何提出好问题？.md
  
   - 029 - ACL 2018论文精读：什么是对话中的前提触发？如何检测？.md
  
   - 030 - ACL 2018论文精读：什么是“端到端”的语义哈希？.md
  
   - 复盘 7 - 一起来读人工智能国际顶级会议论文.md
  
   - 031 - 经典搜索核心算法：TF-IDF及其变种.md
  
   - 032 - 经典搜索核心算法：BM25及其变种（内附全年目录）.md
  
   - 033 - 经典搜索核心算法：语言模型及其变种.md
  
   - 034 - 机器学习排序算法：单点法排序学习.md
  
   - 035 - 机器学习排序算法：配对法排序学习.md
  
   - 036 - 机器学习排序算法：列表法排序学习.md
  
   - 037 - “查询关键字理解”三部曲之分类.md
  
   - 038 - “查询关键字理解”三部曲之解析.md
  
   - 039 - “查询关键字理解”三部曲之扩展.md
  
   - 040 - 搜索系统评测，有哪些基础指标？.md
  
   - 041 - 搜索系统评测，有哪些高级指标？.md
  
   - 042 - 如何评测搜索系统的在线表现？.md
  
   - 043 - 文档理解第一步：文档分类.md
  
   - 044 - 文档理解的关键步骤：文档聚类.md
  
   - 045 - 文档理解的重要特例：多模文档建模.md
  
   - 046 - 大型搜索框架宏观视角：发展、特点及趋势.md
  
   - 047 - 多轮打分系统概述.md
  
   - 048 - 搜索索引及其相关技术概述.md
  
   - 049 - PageRank算法的核心思想是什么？.md
  
   - 050 - 经典图算法之HITS.md
  
   - 051 - 社区检测算法之“模块最大化 ”.md
  
   - 052 - 机器学习排序算法经典模型：RankSVM.md
  
   - 053 - 机器学习排序算法经典模型：GBDT.md
  
   - 054 - 机器学习排序算法经典模型：LambdaMART.md
  
   - 055 - 基于深度学习的搜索算法：深度结构化语义模型.md
  
   - 056 - 基于深度学习的搜索算法：卷积结构下的隐含语义模型.md
  
   - 057 - 基于深度学习的搜索算法：局部和分布表征下的搜索模型.md
  
   - 复盘 1 - 搜索核心技术模块.md
  
   - 058 - 简单推荐模型之一：基于流行度的推荐模型.md
  
   - 059 - 简单推荐模型之二：基于相似信息的推荐模型.md
  
   - 060 - 简单推荐模型之三：基于内容信息的推荐模型.md
  
   - 061 - 基于隐变量的模型之一：矩阵分解.md
  
   - 062 - 基于隐变量的模型之二：基于回归的矩阵分解.md
  
   - 063 - 基于隐变量的模型之三：分解机.md
  
   - 064 - 高级推荐模型之一：张量分解模型.md
  
   - 065 - 高级推荐模型之二：协同矩阵分解.md
  
   - 066 - 高级推荐模型之三：优化复杂目标函数.md
  
   - 067 - 推荐的Exploit和Explore算法之一：EE算法综述.md
  
   - 068 - 推荐的Exploit和Explore算法之二：UCB算法.md
  
   - 069 - 推荐的Exploit和Explore算法之三：汤普森采样算法.md
  
   - 070 - 推荐系统评测之一：传统线下评测.md
  
   - 071 - 推荐系统评测之二：线上评测.md
  
   - 072 - 推荐系统评测之三：无偏差估计.md
  
   - 073 - 现代推荐架构剖析之一：基于线下离线计算的推荐架构.md
  
   - 074 - 现代推荐架构剖析之二：基于多层搜索架构的推荐系统.md
  
   - 075 - 现代推荐架构剖析之三：复杂现代推荐架构漫谈.md
  
   - 076 - 基于深度学习的推荐模型之一：受限波兹曼机.md
  
   - 077 - 基于深度学习的推荐模型之二：基于RNN的推荐系统.md
  
   - 078 - 基于深度学习的推荐模型之三：利用深度学习来扩展推荐系统.md
  
   - 复盘 2 - 推荐系统核心技术模块.md
  
   - 079 - 广告系统概述.md
  
   - 080 - 广告系统架构.md
  
   - 081 - 广告回馈预估综述.md
  
   - 082 - Google的点击率系统模型.md
  
   - 083 - Facebook的广告点击率预估模型.md
  
   - 084 - 雅虎的广告点击率预估模型.md
  
   - 085 - LinkedIn的广告点击率预估模型.md
  
   - 086 - Twitter的广告点击率预估模型.md
  
   - 087 - 阿里巴巴的广告点击率预估模型.md
  
   - 088 - 什么是“基于第二价位的广告竞拍”？.md
  
   - 089 - 广告的竞价策略是怎样的？.md
  
   - 090 - 如何优化广告的竞价策略？.md
  
   - 091 - 如何控制广告预算？.md
  
   - 092 - 如何设置广告竞价的底价？.md
  
   - 093 - 聊一聊“程序化直接购买”和“广告期货”.md
  
   - 094 - 归因模型：如何来衡量广告的有效性.md
  
   - 095 - 广告投放如何选择受众？如何扩展受众群？.md
  
   - 096 - 如何利用机器学习技术来检测广告欺诈？.md
  
   - 复盘 4 - 广告系统核心技术模块.md
  
   - 097 - LDA模型的前世今生.md
  
   - 098 - LDA变种模型知多少.md
  
   - 099 - 针对大规模数据，如何优化LDA算法？.md
  
   - 100 - 基础文本分析模型之一：隐语义分析.md
  
   - 101 - 基础文本分析模型之二：概率隐语义分析.md
  
   - 102 - 基础文本分析模型之三：EM算法.md
  
   - 103 - 为什么需要Word2Vec算法？.md
  
   - 104 - Word2Vec算法有哪些扩展模型？.md
  
   - 105 - Word2Vec算法有哪些应用？.md
  
   - 106 - 序列建模的深度学习利器：RNN基础架构.md
  
   - 107 - 基于门机制的RNN架构：LSTM与GRU.md
  
   - 108 - RNN在自然语言处理中有哪些应用场景？.md
  
   - 109 - 对话系统之经典的对话模型.md
  
   - 110 - 任务型对话系统有哪些技术要点？.md
  
   - 111 - 聊天机器人有哪些核心技术要点？.md
  
   - 112 - 什么是文档情感分类？.md
  
   - 113 - 如何来提取情感“实体”和“方面”呢？.md
  
   - 114 - 文本情感分析中如何做意见总结和搜索？.md
  
   - 复盘 3 - 自然语言处理及文本处理核心技术模块.md
  
   - 115 - 什么是计算机视觉？.md
  
   - 116 - 掌握计算机视觉任务的基础模型和操作.md
  
   - 117 - 计算机视觉中的特征提取难在哪里？.md
  
   - 118 - 基于深度学习的计算机视觉技术（一）：深度神经网络入门.md
  
   - 119 - 基于深度学习的计算机视觉技术（二）：基本的深度学习模型.md
  
   - 120 - 基于深度学习的计算机视觉技术（三）：深度学习模型的优化.md
  
   - 121 - 计算机视觉领域的深度学习模型（一）：AlexNet.md
  
   - 122 - 计算机视觉领域的深度学习模型（二）：VGG & GoogleNet.md
  
   - 123 - 计算机视觉领域的深度学习模型（三）：ResNet.md
  
   - 124 - 计算机视觉高级话题（一）：图像物体识别和分割.md
  
   - 125 - 计算机视觉高级话题（二）：视觉问答.md
  
   - 126 - 计算机视觉高级话题（三）：产生式模型.md
  
   - 复盘 5 - 计算机视觉核心技术模块.md
  
   - 127 - 数据科学家基础能力之概率统计.md
  
   - 128 - 数据科学家基础能力之机器学习.md
  
   - 129 - 数据科学家基础能力之系统.md
  
   - 130 - 数据科学家高阶能力之分析产品.md
  
   - 131 - 数据科学家高阶能力之评估产品.md
  
   - 132 - 数据科学家高阶能力之如何系统提升产品性能.md
  
   - 133 - 职场话题：当数据科学家遇见产品团队.md
  
   - 134 - 职场话题：数据科学家应聘要具备哪些能力？.md
  
   - 135 - 职场话题：聊聊数据科学家的职场规划.md
  
   - 136 - 如何组建一个数据科学团队？.md
  
   - 137 - 数据科学团队养成：电话面试指南.md
  
   - 138 - 数据科学团队养成：Onsite面试面面观.md
  
   - 139 - 成为“香饽饽”的数据科学家，如何衡量他们的工作呢？.md
  
   - 140 - 人工智能领域知识体系更新周期只有5～6年，数据科学家如何培养？.md
  
   - 141 - 数据科学家团队组织架构：水平还是垂直，这是个问题.md
  
   - 142 - 数据科学家必备套路之一：搜索套路.md
  
   - 143 - 数据科学家必备套路之二：推荐套路.md
  
   - 144 - 数据科学家必备套路之三：广告套路.md
  
   - 145 - 如何做好人工智能项目的管理？.md
  
   - 146 - 数据科学团队必备的工程流程三部曲.md
  
   - 147 - 数据科学团队怎么选择产品和项目？.md
  
   - 148 - 曾经辉煌的雅虎研究院.md
  
   - 149 - 微软研究院：工业界研究机构的楷模.md
  
   - 150 - 聊一聊谷歌特立独行的混合型研究.md
  
   - 复盘 6 - 数据科学家与数据科学团队是怎么养成的？.md
  
   - 151 - 精读AlphaGo Zero论文.md
  
   - 152 - 2017人工智能技术发展盘点.md
  
   - 153 - 如何快速学习国际顶级学术会议的内容？.md
  
   - 154 - 在人工智能领域，如何快速找到学习的切入点？.md
  
   - 155 - 人工智能技术选择，该从哪里获得灵感？.md
  
   - 156 - 近在咫尺，走进人工智能研究.md
  
   - 内参特刊 - 和你聊聊每个人都关心的人工智能热点话题.md
  
   - 结束语 - 雄关漫道真如铁，而今迈步从头越.md
  