site_name: 10x程序员工作法

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 10x程序员工作法.md
  
   - 开篇词 - 程序员解决的问题，大多不是程序问题.md
  
   - 01 - 10x程序员是如何思考的？.md
  
   - 02 - 以终为始：如何让你的努力不白费？.md
  
   - 04 - 接到需求任务，你要先做哪件事？.md
  
   - 05 - 持续集成：集成本身就是写代码的一个环节.md
  
   - 06 - 精益创业：产品经理不靠谱，你该怎么办？.md
  
   - 07 - 解决了很多技术问题，为什么你依然在“坑”里？.md
  
   - 08 - 为什么说做事之前要先进行推演？.md
  
   - 09 - 你的工作可以用数字衡量吗？.md
  
   - 10 - 迭代0： 启动开发之前，你应该准备什么？.md
  
   - 答疑解惑 - 如何管理你的上级？.md
  
   - 划重点 - 关于“以终为始”，你要记住的9句话.md
  
   - 11 - 向埃隆·马斯克学习任务分解.md
  
   - 12 - 测试也是程序员的事吗？.md
  
   - 13 - 先写测试，就是测试驱动开发吗？.md
  
   - 14 - 大师级程序员的工作秘笈.md
  
   - 15 - 一起练习：手把手带你分解任务.md
  
   - 16 - 为什么你的测试不够好？.md
  
   - 17 - 程序员也可以“砍”需求吗？.md
  
   - 18 - 需求管理：太多人给你安排任务，怎么办？.md
  
   - 19 - 如何用最小的代价做产品？.md
  
   - 答疑解惑 - 如何分解一个你不了解的技术任务？.md
  
   - 划重点 - 关于“任务分解”，你要重点掌握哪些事？.md
  
   - 20 - 为什么世界和你的理解不一样？.md
  
   - 21 - 你的代码为谁而写？.md
  
   - 22 - 轻量级沟通：你总是在开会吗？.md
  
   - 23 - 可视化：一种更为直观的沟通方式.md
  
   - 24 - 快速反馈：为什么你们公司总是做不好持续集成？.md
  
   - 25 - 开发中的问题一再出现，应该怎么办？.md
  
   - 26 - 作为程序员，你也应该聆听用户声音.md
  
   - 用户故事 - 站在前人的肩膀上，领取属于你的高效工作秘籍.md
  
   - 27 - 尽早暴露问题： 为什么被指责的总是你？.md
  
   - 28 - 结构化：写文档也是一种学习方式.md
  
   - 答疑解惑 - 持续集成，一条贯穿诸多实践的主线.md
  
   - 划重点 - 一次关于“沟通反馈”主题内容的复盘.md
  
   - 加餐 - 你真的了解重构吗？.md
  
   - 29 - “懒惰”应该是所有程序员的骄傲.md
  
   - 30 - 一个好的项目自动化应该是什么样子的？.md
  
   - 31 - 程序员怎么学习运维知识？.md
  
   - 32 - 持续交付：有持续集成就够了吗？.md
  
   - 33 - 如何做好验收测试？.md
  
   - 34 - 你的代码是怎么变混乱的？.md
  
   - 35 - 总是在说MVC分层架构，但你真的理解分层吗？.md
  
   - 36 - 为什么总有人觉得5万块钱可以做一个淘宝？.md
  
   - 37 - 先做好DDD再谈微服务吧，那只是一种部署形式.md
  
   - 答疑解惑 - 持续集成、持续交付，然后呢？.md
  
   - 划重点 - “自动化”主题的重点内容回顾汇总.md
  
   - 38 - 新入职一家公司，怎么快速进入工作状态？.md
  
   - 39 - 面对遗留系统，你应该这样做.md
  
   - 40 - 我们应该如何保持竞争力？.md
  
   - 答疑解惑 - 如何在实际工作中推行新观念？.md
  
   - 划重点 - “综合运用”主题内容的全盘回顾.md
  
   - 总复习 - 重新审视“最佳实践”.md
  
   - 总复习 - 重新来“看书”.md
  
   - 03 - DoD的价值：你完成了工作，为什么他们还不满意？.md
  
   - 结束语 - 少做事，才能更有效地工作.md
  
   - 结课测试 - 这些10x程序员工作法的知识你都掌握了吗？.md
  
   - 第二季回归 - 我带着软件设计课回来了！.md
  
   - 第三季回归 - 我们一起来写好代码！.md
  
   - 第四季回归 - 通向高质量代码之路.md
  
   - 特别加餐 - ChatGPT来了，你的编程效率提高了吗？.md
  
   - 私享直播-1小时参透程序员的AI三重境界.md
  
   - 私享直播-程序员的上限、下限和第二曲线.md
  
   - 第五季回归-让我们一起共赴AI时代！.md
  