site_name: Kafka核心技术与实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Kafka核心技术与实战.md
  
   - 开篇词 - 为什么要学习Kafka？.md
  
   - 01 -  消息引擎系统ABC.md
  
   - 02 - 一篇文章带你快速搞定Kafka术语.md
  
   - 03 - Kafka只是消息引擎系统吗？.md
  
   - 04 - 我应该选择哪种Kafka？.md
  
   - 05 - 聊聊Kafka的版本号.md
  
   - 06 - Kafka线上集群部署方案怎么做？.md
  
   - 07 - 最最最重要的集群参数配置（上）.md
  
   - 08 - 最最最重要的集群参数配置（下）.md
  
   - 09 -  生产者消息分区机制原理剖析.md
  
   - 10 - 生产者压缩算法面面观.md
  
   - 11 - 无消息丢失配置怎么实现？.md
  
   - 12 - 客户端都有哪些不常见但是很高级的功能？.md
  
   - 13 -  Java生产者是如何管理TCP连接的？.md
  
   - 14 - 幂等生产者和事务生产者是一回事吗？.md
  
   - 15 - 消费者组到底是什么？.md
  
   - 16 - 揭开神秘的“位移主题”面纱.md
  
   - 17 - 消费者组重平衡能避免吗？.md
  
   - 18 - Kafka中位移提交那些事儿.md
  
   - 19 - CommitFailedException异常怎么处理？.md
  
   - 20 - 多线程开发消费者实例.md
  
   - 21 - Java 消费者是如何管理TCP连接的？.md
  
   - 22 - 消费者组消费进度监控都怎么实现？.md
  
   - 23 - Kafka副本机制详解.md
  
   - 24 - 请求是怎么被处理的？.md
  
   - 25 - 消费者组重平衡全流程解析.md
  
   - 26 - 你一定不能错过的Kafka控制器.md
  
   - 27 - 关于高水位和Leader Epoch的讨论.md
  
   - 28 - 主题管理知多少？.md
  
   - 29 - Kafka动态配置了解下？.md
  
   - 30 - 怎么重设消费者组位移？.md
  
   - 31 - 常见工具脚本大汇总.md
  
   - 32 - KafkaAdminClient：Kafka的运维利器.md
  
   - 33 - Kafka认证机制用哪家？.md
  
   - 34 - 云环境下的授权该怎么做？.md
  
   - 35 - 跨集群备份解决方案MirrorMaker.md
  
   - 36 - 你应该怎么监控Kafka？.md
  
   - 37 - 主流的Kafka监控框架.md
  
   - 38 - 调优Kafka，你做到了吗？.md
  
   - 39 - 从0搭建基于Kafka的企业级实时日志流处理平台.md
  
   - 40 - Kafka Streams与其他流处理平台的差异在哪里？.md
  
   - 41 - Kafka Streams DSL开发实例.md
  
   - 42 - Kafka Streams在金融领域的应用.md
  
   - 加餐 - 搭建开发环境、阅读源码方法、经典学习资料大揭秘.md
  
   - 用户故事 - 黄云：行百里者半九十.md
  
   - 结束语 - 以梦为马，莫负韶华！.md
  
   - 期末测试 - 这些Kafka核心要点，你都掌握了吗？.md
  