site_name: LangChain实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - LangChain实战课.md
  
   - 开篇词-带你亲证AI应用开发的“奇点”时刻.md
  
   - 01-LangChain系统安装和快速入门.md
  
   - 02-用LangChain快速构建基于“易速鲜花”本地知识库的智能问答系统.md
  
   - 03-模型I-O：输入提示、调用模型、解析输出.md
  
   - 04-提示工程（上）：用少样本FewShotTemplate和ExampleSelector创建应景文案.md
  
   - 05-提示工程（下）：用思维链和思维树提升模型思考质量.md
  
   - 06-调用模型：使用OpenAI API还是微调开源Llama2-ChatGLM？.md
  
   - 07-输出解析：用OutputParser生成鲜花推荐列表.md
  
   - 08-链（上）：写一篇完美鲜花推文？用SequencialChain链接不同的组件.md
  
   - 09-链（下）：想学“育花”还是“插花”？用RouterChain确定客户意图.md
  
   - 10-记忆：通过Memory记住客户上次买花时的对话细节.md
  
   - 11-代理（上）：ReAct框架，推理与行动的协同.md
  
   - 12-代理（中）：AgentExecutor究竟是怎样驱动模型和工具完成任务的？.md
  
   - 13-代理（下）：结构化工具对话、Self-Ask with Search以及Plan and execute代理.md
  
   - 14-工具和工具箱：LangChain中的Tool和Toolkits一览.md
  
   - 15-检索增强生成：通过RAG助力鲜花运营.md
  
   - 16-连接数据库：通过链和代理查询鲜花信息.md
  
   - 17-回调函数：在AI应用中引入异步通信机制.md
  
   - 18-CAMEL：通过角色扮演脑暴一个鲜花营销方案.md
  
   - 19-BabyAGI：根据气候变化自动制定鲜花存储策略.md
  
   - 20-部署一个鲜花网络电商的人脉工具（上）.md
  
   - 21-部署一个鲜花网络电商的人脉工具（下）.md
  
   - 22-易速鲜花聊天客服机器人的开发（上）.md
  
   - 23-易速鲜花聊天客服机器人的开发（下）.md
  
   - 结束语-人生的价值就在于创造.md
  
   - 结课测试-来赴一场满分之约.md
  
   - 直播加餐-LangChain表达式语言LCEL初探.md
  
   - 直播加餐-LangChain的Tracing、Debug和LangSmith平台解读.md
  