site_name: Spring Cloud 微服务项目实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Spring Cloud 微服务项目实战.md
  
   - 开篇词 - 跟着学，你也能成为微服务高手.md
  
   - 01 - 是什么推动了单体应用到微服务架构的演进？.md
  
   - 02 - 微服务全家桶：走进 Spring Cloud 的世界.md
  
   - 03 - 初窥门径：我们要搭建一个怎样的微服务实战项目？.md
  
   - 04 - 十八般兵器：如何搭建项目所需的开发环境？.md
  
   - 05 - 牛刀小试：如何搭建优惠券模板服务？.md
  
   - 06 - 牛刀小试：如何搭建优惠券计算服务和用户服务？.md
  
   - 07 - Nacos体系架构：什么是服务治理？.md
  
   - 08 - 服务治理：Nacos集群环境搭建.md
  
   - 09 - 集成 Nacos：如何将服务提供者注册到 Nacos 服务器？.md
  
   - 10 - 集成 Nacos：如何通过服务发现机制向服务提供者发起调用？.md
  
   - 11 - Loadbalancer 实战：通过自定义负载均衡策略实现金丝雀测试.md
  
   - 12 - OpenFeign：服务间调用组件 OpenFeign 是怎么“隔空取物”的？.md
  
   - 13 - OpenFeign 实战：如何实现服务间调用功能？.md
  
   - 14 - OpenFeign 实战：OpenFeign 组件有哪些高级玩法？.md
  
   - 15 - 配置中心在微服务中发挥着怎样的作用？.md
  
   - 16 - 如何集成 Nacos Config 实现配置项动态刷新？.md
  
   - 17 - Sentinel 体系结构：什么是服务容错（降级熔断、流量整形）？.md
  
   - 18 - Sentinel 实战：如何实施流量整形与限流策略？.md
  
   - 19 - Sentinel 实战：如何为项目添加异常降级方案？.md
  
   - 20 - Sentinel 实战：如何接入 Nacos 实现规则持久化？.md
  
   - 加餐：说透微服务 - 什么是主链路规划？.md
  
   - 21 - Sleuth 体系架构：为什么微服务架构需要链路追踪？.md
  
   - 22 - 调用链追踪：集成 Sleuth 和 Zipkin，实现链路打标.md
  
   - 23 - 调用链追踪：如何通过 ELK 实现日志检索？.md
  
   - 24 - 为什么微服务架构少不了微服务网关？.md
  
   - 25 - 微服务网关：Gateway 中的路由和谓词有何应用？.md
  
   - 26 - 微服务网关：如何设置请求转发、跨域和限流规则？.md
  
   - 27 - 微服务网关：如何借助 Nacos 实现动态路由规则？.md
  
   - 28 - 消息驱动：谁说消息队列只能削峰填谷？.md
  
   - 29 - 消息驱动：如何集成 Stream 实现消息驱动？.md
  
   - 30 - 消息驱动：如何高效处理 Stream 中的异常？.md
  
   - 31 - 消息驱动：如何通过 RabbitMQ 插件实现延迟消息？.md
  
   - 32 - Alibaba Seata 框架：什么是分布式事务？.md
  
   - 33 - 分布式事务：搭建 Seata 服务器.md
  
   - 34 - 分布式事务：使用 Nacos+Seata 实现AT模式.md
  
   - 35 - 分布式事务：使用 Nacos+Seata 实现 TCC 补偿模式.md
  
   - 结束语 - 站在聚光灯下.md
  