site_name: 技术与商业案例解读

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 技术与商业案例解读.md
  
   - 开篇词 - 突破技术思维，站在商业的角度看问题.md
  
   - 001 - 西雅图IT公司之RealNetworks：一个帝国的兴衰（上）.md
  
   - 002 - 西雅图IT公司之RealNetworks：一个帝国的兴衰（下）.md
  
   - 003 - 以RealNetworks为例，谈谈初创公司如何应对巨头碾压.md
  
   - 004 - 可视化分析鼻祖Tableau.md
  
   - 005 - 从Tableau上市，看学术界和工业界人士创业.md
  
   - 006 - 在线旅游帝国Expedia崛起的背后.md
  
   - 007 - 房产经纪的颠覆者Redfin：在“传统”与“现代”间徘徊.md
  
   - 008 - 房产经纪的“协作者”Zillow：一个地产数据平台.md
  
   - 009 - 颠覆还是协作，房地产市场上Redfin和Zillow的抉择.md
  
   - 010 - 应用交付网络大厂F5：“一招鲜”之殇.md
  
   - 011 - 在线差旅报销鼻祖Concur：在转型中获得发展.md
  
   - 012 - 漫谈企业转型：在市场变迁中寻找生机.md
  
   - 013 - 克雷公司沉浮录：行走在超级计算机市场.md
  
   - 014 - “单一化”的隐忧：从克雷公司看“一条腿走路”.md
  
   - 015 - Halo的开发者Bungie：与微软的聚散.md
  
   - 016 - “卖身”须谨慎：创业公司面临的抉择.md
  
   - 017 - 亚马逊领导力准则之要有硬骨头.md
  
   - 018 - 亚马逊领导力准则之决策正确.md
  
   - 019 - 亚马逊领导力准则之客户至尚.md
  
   - 020 - 亚马逊领导力准则之勤俭节约.md
  
   - 021 - 亚马逊领导力准则之主人翁精神.md
  
   - 022 - 亚马逊领导力准则之选贤育能.md
  
   - 023 - 亚马逊领导力准则之最高标准.md
  
   - 024 - 亚马逊领导力准则之创新简化.md
  
   - 025 - 亚马逊领导力准则之崇尚行动.md
  
   - 026 - 亚马逊领导力准则之远见卓识.md
  
   - 027 - 亚马逊领导力准则之好奇求知与赢得信任.md
  
   - 028 - 亚马逊领导力准则之刨根问底与达成业绩.md
  
   - 029 - 智能音箱的战斗：亚马逊的硬件路.md
  
   - 030 - 智能音箱的战斗：Echo攻城略地.md
  
   - 031 - 智能音箱的战斗：语音助手Alexa.md
  
   - 032 - 智能音箱的战斗：谷歌的杀入.md
  
   - 033 - 智能音箱的战斗：亚马逊的战略布局.md
  
   - 034 - 智能音箱的战斗：巨头纷纷入场.md
  
   - 035 - 智能音箱的战斗：白马非马.md
  
   - 036 - 如何透过一个领域去联合分析多家企业？.md
  
   - 037 - 管中窥豹之从面试看企业文化：微软.md
  
   - 038 - 管中窥豹之从面试看企业文化：亚马逊.md
  
   - 039 - 管中窥豹之从面试看企业文化：谷歌.md
  
   - 040 - 管中窥豹之从面试看企业文化：甲骨文.md
  
   - 041 - 管中窥豹之从面试看企业文化：Facebook.md
  
   - 042 - 透过企业用人之道看企业发展.md
  
   - 043 - 办公软件的战斗：开篇.md
  
   - 044 - VisiCalc：第一个电子表格软件的诞生.md
  
   - 045 - WordStar：第一个字处理软件的故事.md
  
   - 046 - 微软：办公软件战场的螳螂.md
  
   - 047 - WordPerfect：字处理软件的新秀.md
  
   - 048 - Lotus 1-2-3：莲花公司的电子表格帝国.md
  
   - 049 - 红狮会战：微软的反击.md
  
   - 050 - 大杀器Lotus Notes 和被收购的莲花公司.md
  
   - 051 - 无敌寂寞的微软之为创新而创新.md
  
   - 052 - 办公软件的新时代：微软和谷歌的战斗.md
  
   - 053 - 异军突起的Slack.md
  
   - 054 - 办公软件战斗的启示：内忧总是强于外患.md
  
   - 055 - 办公软件战斗的启示：敌人的出现常常出其不意.md
  
   - 056 - 半条命的Dota帝国Valve：半条命.md
  
   - 057 - 半条命的Dota帝国Valve：Steam平台.md
  
   - 058 - 半条命的Dota帝国Valve：Dota 2.md
  
   - 059 - 半条命的Dota帝国Valve：无领导管理.md
  
   - 060 - 半条命的Dota帝国Valve：虚拟现实.md
  
   - 061 - Gabe Newell：Valve帝国制度的利弊.md
  
   - 062 - 文档数据库的缔造者MongoDB（上）.md
  
   - 063 - 文档数据库的缔造者MongoDB（下）.md
  
   - 064 - 以MongoDB为例，看基础架构类产品创业.md
  
   - 065 - 直面MongoDB，谈微软的NoSQL战略.md
  
   - 066 - Hadoop三国之魏国Cloudera.md
  
   - 067 - Hadoop三国之吴国MapR.md
  
   - 068 - Hadoop三国之蜀国Hortonworks.md
  
   - 069 - Hadoop及其发行商的未来.md
  
   - 070 - 谷歌的大数据路：从“三驾马车”到一无所有.md
  
   - 071 - 谷歌的大数据路：一场影响深远的论战.md
  
   - 072 - 谷歌的大数据路：谷歌的“黑科技”.md
  
   - 073 - 如何读懂类似谷歌“三驾马车”这样的技术论文？.md
  
   - 074 - 雅虎：大数据领域的“活雷锋”.md
  
   - 075 - IBM的大数据路之起早贪黑赶了晚集.md
  
   - 076 - 社交公司们的大数据贡献.md
  
   - 077 - 微软的大数据发展史：微软硅谷研究院.md
  
   - 078 - 微软的大数据发展史：必应的Cosmos.md
  
   - 079 - 微软的大数据发展史：Azure的大数据发展.md
  
   - 080 - 亚马逊的大数据故事：从先驱者到插管吸血开源.md
  
   - 081 - 亚马逊的大数据故事：创新和拿来并存的云服务.md
  
   - 082 - 阿里巴巴的大数据故事：数据分析平台发展史.md
  
   - 083 - 阿里巴巴的大数据故事：流计算引擎发展史.md
  
   - 084 - 大公司的大数据战略得失：自建轮子成本高.md
  
   - 085 - 大公司的大数据战略得失：抱团取暖难敌插管吸血者.md
  
   - 086 - Palantir：神秘的大数据独角兽.md
  
   - 087- Splunk：机器大数据的分析帝国.md
  
   - 088 - Confluent：在Kafka上飞驰的数据交换者.md
  
   - 089 - Powerset：HBase的老东家.md
  
   - 090 - Cassandra和DataStax的故事.md
  
   - 091 - Databricks之Spark的数据金砖王国.md
  
   - 092 - Data Artisans：浴火重生的新一代大数据计算引擎Flink.md
  
   - 093 - Dremio：在Drill和Arrow上的大数据公司.md
  
   - 094 - Imply：基于Druid的大数据分析公司.md
  
   - 095 - Kyligence：阿帕奇麒麟背后的大数据公司.md
  
   - 096 - Snowflake：云端的弹性数据仓库.md
  
   - 097 - TiDB：一个国产新数据库的创业故事.md
  
   - 098 - 大数据创业公司的前景：红海创业多艰辛.md
  
   - 099 - 如何通过企业技术积累去分析一家企业？.md
  
   - 100 - 仁科：被迫再创业的David Duffield.md
  
   - 101 - 仁科：飞跃发展的企业级软件帝国.md
  
   - 102 - 仁科：收购和被收购.md
  
   - 103 - 仁科的成与败.md
  
   - 104 - WorkDay：杜菲尔德复仇记.md
  
   - 105 - David Duffield的眼界和成败.md
  
   - 106 - 分析企业的两要素：远见和执行力.md
  
   - 107 - Zenefits：一个卖保险的创业公司.md
  
   - 108 - Glassdoor：让公司信息对个人透明.md
  
   - 109 - 从巴顿的创业史看巴顿.md
  
   - 110 - 免费还是收费？WinRAR的生意经.md
  
   - 111 - 周鸿祎和BAT的沉浮录（上）.md
  
   - 112 - 周鸿祎和BAT的沉浮录（中）.md
  
   - 113 - 周鸿祎和BAT的沉浮录（下）.md
  
   - 114 - 周鸿祎和BAT的沉浮录（后记）.md
  
   - 115 - 互联网第一股雅虎的兴衰：霸主的诞生.md
  
   - 116 - 互联网第一股雅虎的兴衰：运气不敌技术.md
  
   - 117 - 互联网第一股雅虎的兴衰：没有救世主.md
  
   - 118 - 成也杨致远，败也杨致远.md
  
   - 119 - 企业因人成事，领导人很重要.md
  
   - 120 - 彼得 · 蒂尔的投资人生.md
  
   - 121 - 商业之外的彼得 · 蒂尔.md
  
   - 122 - 创业的智慧：从彼得·蒂尔的创投哲学说起.md
  
   - 123 - 谷歌的创新精神：好的、坏的和丑陋的（上）.md
  
   - 124 - 谷歌的创新精神：好的、坏的和丑陋的（下）.md
  
   - 125 - Facebook的黑客精神.md
  
   - 126 - Twitter：蓝色小鸟还能飞多久（上）.md
  
   - 127 - Twitter：蓝色小鸟还能飞多久（下）.md
  
   - 128 - 赚钱是根本，换CEO也没救.md
  
   - 129 - Square：手机POS机和比特币交易.md
  
   - 130 - 创意很重要，但不是一切.md
  
   - 131 - 杰克·多西：分身有术之兼任两家上市公司CEO.md
  
   - 132 - Groupon：团购鼻祖的兴衰.md
  
   - 133 - 卖掉自己是不是更好.md
  
   - 134 - 企业在线存储Box.md
  
   - 135 - 个人在线存储 Dropbox.md
  
   - 136 - 做产品先做消费者市场，还是先做企业市场.md
  
   - 137 - 今天我们都来Pin图片之Pinterest的图片社交路.md
  
   - 138 - 企业不上市为哪般.md
  
   - 139 - 微软的综合工程师改革.md
  
   - 140 - SaaS先驱Salesforce.md
  
   - 141 - 太超前好不好.md
  
   - 142 - Sun：太阳的升起.md
  
   - 143 - Sun：太阳的陨落.md
  
   - 144 - 看错敌人多可怕.md
  
   - 145 - SAP的HANA战略（上）.md
  
   - 146 - SAP的HANA战略（下）.md
  
   - 147 - 成功的忽悠 + 成功的执行 = 成功的产品.md
  
   - 148 - SQL Server发展史.md
  
   - 149 - 眼光决定一切.md
  
   - 150 - Ashton-Tate：桌面数据库王者的兴衰.md
  
   - 151 - 无敌不可以肆意妄为.md
  
   - 152 - Reddit：天涯论坛美国版.md
  
   - 153 - Hacker News：创业社交两不误.md
  
   - 154 - Y Combinator：孵化器还是培训班？.md
  
   - 155 - 创业公司进孵化器真的值得吗？.md
  
   - 156 - Paul Graham：硅谷创业教父.md
  
   - 157 - Zynga：发家从农场开始.md
  
   - 158 - 论Zynga的倒台.md
  
   - 159 - 企业分析要求综合素质.md
  
   - 结束语 - 积跬步，而终至千里.md
  
   - 一键直达 - 系列解读文章回顾.md
  
   - 新书首发丨《大数据浪潮之巅》.md
  
   - 结课测试 - 这些技术与商业的知识你都掌握了吗？.md
  