site_name: 编译原理实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 编译原理实战课.md
  
   - 开篇词 - 在真实世界的编译器中游历.md
  
   - 学习指南 - 如何学习这门编译原理实战课？.md
  
   - 01 - 编译的全过程都悄悄做了哪些事情？.md
  
   - 02 - 词法分析：用两种方式构造有限自动机.md
  
   - 03 - 语法分析：两个基本功和两种算法思路.md
  
   - 04 - 语义分析：让程序符合语义规则.md
  
   - 05 - 运行时机制：程序如何运行，你有发言权.md
  
   - 06 - 中间代码：不是只有一副面孔.md
  
   - 07 - 代码优化：跟编译器做朋友，让你的代码飞起来.md
  
   - 08 - 代码生成：如何实现机器相关的优化？.md
  
   - 知识地图 - 一起来复习编译技术核心概念与算法.md
  
   - 09 - Java编译器（一）：手写的编译器有什么优势？.md
  
   - 10 - Java编译器（二）：语法分析之后，还要做些什么？.md
  
   - 11 - Java编译器（三）：属性分析和数据流分析.md
  
   - 12 - Java编译器（四）：去除语法糖和生成字节码.md
  
   - 13 - Java JIT编译器（一）：动手修改Graal编译器.md
  
   - 14 - Java JIT编译器（二）：Sea of Nodes为何如此强大？.md
  
   - 15 - Java JIT编译器（三）：探究内联和逃逸分析的算法原理.md
  
   - 16 - Java JIT编译器（四）：Graal的后端是如何工作的？.md
  
   - 17 - Python编译器（一）：如何用工具生成编译器？.md
  
   - 18 - Python编译器（二）：从AST到字节码.md
  
   - 19 - Python编译器（三）：运行时机制.md
  
   - 20 - JavaScript编译器（一）：V8的解析和编译过程.md
  
   - 21 - JavaScript编译器（二）：V8的解释器和优化编译器.md
  
   - 22 - Julia编译器（一）：如何让动态语言性能很高？.md
  
   - 23 - Julia编译器（二）：如何利用LLVM的优化和后端功能？.md
  
   - 24 - Go语言编译器：把它当作教科书吧.md
  
   - 25 - MySQL编译器（一）：解析一条SQL语句的执行过程.md
  
   - 26 - MySQL编译器（二）：编译技术如何帮你提升数据库性能？.md
  
   - 热点问题答疑 - 如何吃透7种真实的编译器？.md
  
   - 划重点 - 7种编译器的核心概念与算法.md
  
   - 期中考试 - 这些编译原理知识，你都掌握了吗？.md
  
   - 用户故事 - 易昊：程序员不止有Bug和加班，还有诗和远方.md
  
   - 27 - 课前导读：学习现代语言设计的正确姿势.md
  
   - 28 - 前端总结：语言设计也有人机工程学.md
  
   - 29 - 中端总结：不遗余力地进行代码优化.md
  
   - 30 - 后端总结：充分发挥硬件的能力.md
  
   - 31 - 运行时（一）：从0到语言级的虚拟化.md
  
   - 32 - 运行时（二）：垃圾收集与语言的特性有关吗？.md
  
   - 33 - 并发中的编译技术（一）：如何从语言层面支持线程？.md
  
   - 34 - 并发中的编译技术（二）：如何从语言层面支持协程？.md
  
   - 35 - 并发中的编译技术（三）：Erlang语言厉害在哪里？.md
  
   - 36 - 高级特性（一）：揭秘元编程的实现机制.md
  
   - 37 - 高级特性（二）：揭秘泛型编程的实现机制.md
  
   - 38 - 综合实现（一）：如何实现面向对象编程？.md
  
   - 39 - 综合实现（二）：如何实现函数式编程？.md
  
   - 40 - 成果检验：方舟编译器的优势在哪里？.md
  
   - 期末答疑与总结 - 再次审视学习编译原理的作用.md
  
   - 结束语 - 实战是唯一标准！.md
  
   - 期末考试 - “编译原理实战课”100分试卷等你来挑战！.md
  
   - 不定期加餐1 - 远程办公，需要你我具备什么样的素质？.md
  
   - 不定期加餐2 - 学习技术的过程，其实是训练心理素质的过程.md
  
   - 不定期加餐3 - 这几年，打动我的两本好书.md
  
   - 不定期加餐4 - 从身边的牛人身上，我学到的一些优秀品质.md
  
   - 不定期加餐5 - 借助实例，探究C++编译器的内部机制.md
  