site_name: ToB市场品牌实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_成为下一个万亿市场风口上的操盘人.md
  
   - 01_ToB市场营销到底是做什么的_.md
  
   - 02_ToB消费心理学_如何把握客户CEO心理，让他买单_.md
  
   - 03_第一印象（上）_如何策划一场产品发布会_.md
  
   - 04_第一印象（下）_如何策划一场产品发布会_.md
  
   - 05_Leads_如何成体系地寻找高质量的Leads_.md
  
   - 06_案例_怎样0成本把一个新产品的市场认知率做到76%_.md
  
   - 07_产品世界观_如何构建一个好的对外产品故事体系_.md
  
   - 08_口碑_如何打造一个有影响力的Demo_.md
  
   - 09_后疫情时代，如何做ToB市场品牌内容的线上转型_.md
  
   - 10_如何用“周边”产品构建ToB影响力_.md
  
   - 11_打造案例（上）_如何做优质客户案例的选型和内容构造_.md
  
   - 12_打造案例（中）_如何引发现象级讨论，打赢PR战役_.md
  
   - 13_打造案例（下）_如何通过营销战役把商机转化为销量_.md
  
   - 14_颜值美学_如何体现ToB产品营销的设计感_.md
  
   - 15_如何给企业讲一个“降本”的故事_.md
  
   - 16｜如何给企业讲一个“增效”的故事_.md
  
   - 17｜市场中的禁忌_ToB营销中容易犯哪些错误_.md
  
   - 18_ToB营销的阵地_我们在哪里说话，也很重要.md
  
   - ToB会客厅｜SDR是如何优化线索跟进策略，提升销售效能的_.md
  
   - ToB会客厅｜如何通过整体营销迎接后疫情时代的市场挑战_.md
  
   - 结束语_一个ToB的市场人应该具备怎样的特质_.md
  