site_name: 分布式数据库从入门到实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 分布式数据库从入门到实战.md
  
   - 开篇词-玩转数据库，让数据尽在你的掌控.md
  
   - 01-列式存储已经取代行式存储了吗？.md
  
   - 02-分布式存储数据结构LSM，如何优化读写性能？.md
  
   - 03-编码和压缩有什么用？.md
  
   - 04-数据库都需要事务和MVCC吗？.md
  
   - 05-分布式数据库如何合理分区与设计行键？.md
  
   - 06-数据分区后，如何应对Join？.md
  
   - 07-从一个手机云服务数据存储的需求开始.md
  
   - 08-HBase如何组织与存储数据？.md
  
   - 09-为什么HBase能够实现海量数据的实时随机存取？.md
  
   - 10-不支持二级索引，如何自己实现一个？.md
  
   - 11-实现：基于HBase的手机云服务数据存储设计.md
  
   - 12-还有哪些调优可以提升性能？.md
  
   - 13-客户数据平台（CDP）的存储与计算需求.md
  
   - 14-技术上，StarRocks如何应对CDP需求？.md
  
   - 15-数据存储上如何选用合适的表存储类型？.md
  
   - 16-性能上如何优化数据查询？.md
  
   - 17-ClickHouse为什么会给人极致速度的印象？.md
  
   - 18-ClickHouse应该如何选用表引擎？.md
  
   - 19-如何在ClickHouse利用集群能力实现并行计算？.md
  
   - 20-如何用ClickHouse bitmap加速人群计算.md
  
   - 21-向量数据库：图片、音频、文本等非结构化数据的搜索需求是怎么实现的？.md
  
   - 22-Faiss是一个向量数据库吗？.md
  
   - 23-案例：带你用Faiss手撸一个人脸识别系统.md
  
   - 24-带你看一个完整的向量数据库Milvus.md
  
   - 25-案例：RAG+Milvus+大模型，搭建个人知识库.md
  
   - 26-向量数据库，十字路口向左还是向右？.md
  
   - 结束语-不让技术成为自我目的.md
  
   - 结课测试-来赴一场满分之约.md
  