site_name: Serverless入门课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Serverless入门课.md
  
   - 开篇词 - 说来说去，到底Serverless要解决什么问题？.md
  
   - 特别放送 - 为什么阿里要举集团之力趟坑Serverless？.md
  
   - 01-定义：到底什么是Serverless？.md
  
   - 02 - 原理：通过一个案例，理解FaaS的运行逻辑.md
  
   - 03 - 原理：FaaS的两种进程模型及应用场景.md
  
   - 04 - 原理：FaaS应用如何才能快速扩缩容？.md
  
   - 05 - 后端BaaS化（上）：NoOps的微服务.md
  
   - 06 - 后端BaaS化（中）：业务逻辑的拆与合.md
  
   - 07 - 后端BaaS化（下）：Container Serverless.md
  
   - 08 - 搭建私有Serverless（一）：K8s和云原生CNCF.md
  
   - 09 - 搭建私有Serverless（二）：基于K8s的Serverless.md
  
   - 10 - 经验：Serverless架构应该如何选型？.md
  
   - 11 - 经验：Serverless开发最佳实践.md
  
   - 结束语 - 带你整体回顾我们的Serverless案例.md
  
   - 结课问卷获奖用户名单.md
  
   - 期末测试 - 有关Serverless，你掌握了多少呢？.md
  