site_name: 手机摄影

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 手机摄影.md
  
   - 开篇词-手机拍照这件小事.md
  
   - 01-拍摄前，我们需要做什么？.md
  
   - 02-一张好照片的背后，都隐含着哪些要素？.md
  
   - 03-你的照片里是否有内容？.md
  
   - 04 - 除了横平竖直，照片还能怎么拍？.md
  
   - 05-拍照的光影有最优解吗？.md
  
   - 06-后期概述：工具选择与调色倾向.md
  
   - 07-后期调色：基础工具使用.md
  
   - 08-后期调色：HSL、局部.md
  
   - 09-建筑和场景摄影.md
  
   - 10-人像摄影.md
  
   - 11-食物摄影.md
  
   - 12-专业相机功能与 Live Photos 的使用.md
  
   - 13-忘记构图规则.md
  
   - 14-从零到“零”：多拍与多看.md
  
   - 结束语-记录生活这件大事.md
  