site_name: 现代C++20实战高手课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 现代C++20实战高手课.md
  
   - 开篇词-为什么掌握现代C++新特性如此重要？.md
  
   - 01-Modules（上）：C++模块化问题的前世今生.md
  
   - 02-Modules（中）：解决编译性能和符号隔离的银弹.md
  
   - 03-Modules（下）：实战写个多模块图像处理服务.md
  
   - 04-Concepts背景：C++泛型编程之殇.md
  
   - 05-Concepts：解决模板接口的类型与约束定义难题.md
  
   - 06-Concepts实战：写个向量计算模板库.md
  
   - 07-Coroutines背景：异步I-O的复杂性.md
  
   - 08-Coroutines：“零”开销降低异步编程复杂度.md
  
   - 09-Coroutines实战（一）：异步文件操作库.md
  
   - 10-Coroutines实战（二）：异步文件操作库.md
  
   - 期中周-扩展现有协程框架，实现高级任务调度.md
  
   - 期中周-期中测试题，你做对了么？.md
  
   - 11-Ranges（一）：数据序列处理的新工具.md
  
   - 12-Ranges（二）：用“视图”破除函数式编程之困.md
  
   - 13-Ranges实战：数据序列函数式编程.md
  
   - 14-Formatting：千呼万唤始出来的新format标准.md
  
   - 15-Formatting实战：如何构建一个数据流处理实例？.md
  
   - 16-Bit library（一）：如何利用新bit操作库释放编程生产力？.md
  
   - 17-Bit library（二）：如何利用新bit操作库释放编程生产力？.md
  
   - 18-其他重要标准库特性：还有哪些库变更值得关注？.md
  
   - 19-其他重要标准库特性实战：利用日历应用熟悉新特性.md
  
   - 20-漫游C++23：更好的C++20.md
  
   - 21-重大变更（一）：关于C++26的十大猜想.md
  
   - 22-重大变更（二）：关于C++26的十大猜想.md
  
   - 23-未来展望：透过未来标准演进看C++设计哲学.md
  
   - 结束语-这只长颈鹿在我家后院生活得不错.md
  
   - 期末测试-来赴一场满分之约！.md
  
   - 加餐-软件工程师在AIGC浪潮下的生存指南.md
  