site_name: 手把手带你搭建推荐系统

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 手把手带你搭建推荐系统.md
  
   - 开篇词-从企业级项目开始，进阶推荐系统.md
  
   - 01-推荐系统：我们应该怎样学习推荐系统？.md
  
   - 02-Netflix推荐系统：企业级的推荐系统架构是怎样的？.md
  
   - 03-数据处理：我们应该如何获取和处理数据？.md
  
   - 04-MongoDB：如何安装和使用MongoDB数据库？.md
  
   - 05-Redis：如何安装和使用Redis数据库？.md
  
   - 06-网络爬虫：爬取一个网站的流程是怎样的？.md
  
   - 07-数据获取：什么是Scrapy框架？.md
  
   - 08-数据获取：如何使用Scrapy框架爬取新闻数据？.md
  
   - 09-数据存储：如何将爬取到的数据存入数据库中？.md
  
   - 10-数据加工：如何将原始数据做成内容画像？.md
  
   - 11-基于规则的召回：如何使用规则找到用户的兴趣点？.md
  
   - 12-基于热度的召回：如何使用热门内容来吸引用户？.md
  
   - 13-基于关键词的召回：如何使用关键词吸引用户？.md
  
   - 14-基于Flask的推荐服务：搭建基础的Flask服务.md
  
   - 15-基于Flask的推荐服务：如何把召回集推荐出去？.md
  
   - 16-基础用户画像：如何用好用户的注册信息？.md
  
   - 17-推荐系统前端：如何用一个界面展示我们的成果？.md
  
   - 18-一个简单的推荐服务闭环包括哪些模块？.md
  
   - 19-协同过滤：召回算法中永远不落幕的经典.md
  
   - 20-Embedding：深入挖掘用户底层特征.md
  
   - 21-YouTubeDNN：召回算法的后起之秀（上）.md
  
   - 22-YouTubeDNN：召回算法的后起之秀（下）.md
  
   - 23-流程串联：数据处理和协同过滤串联进行内容推荐.md
  
   - 24-GBDT+LR：排序算法经典中的经典.md
  
   - 25-DeepFM：如何使用深度学习技术给数据排序？.md
  
   - 26-重排序：如何对排序后的内容进行微调？.md
  
   - 27-部署：如何在Linux上配合定时任务部署推荐系统服务？.md
  
   - 28-珠联璧合：Kafka与推荐服务的联动.md
  
   - 29-推荐系统的工程化策略及服务部署策略.md
  
   - 30-推荐系统的后处理及日志回采.md
  
   - 特别放送-知识回顾（上）.md
  
   - 特别放送-知识回顾（中）.md
  
   - 特别放送-知识回顾（下）.md
  
   - 结束语-如何成为企业中不可或缺的推荐系统工程师？.md
  
   - 期末测试-来赴一场满分之约！.md
  