site_name: 研发效率破局之道

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 研发效率破局之道.md
  
   - 开篇词 - 为什么你要关注研发效能？.md
  
   - 01 - 效能模型：如何系统地理解研发效能？.md
  
   - 02 - 效能度量：效果不好甚至有副作用，怎么回事？.md
  
   - 03 - 效能度量：如何选对指标与方法，真正提升效能？.md
  
   - 04 - 流程优化：怎样才能让敏捷、精益真正为我所用？.md
  
   - 05 - 代码入库前：Facebook如何让开发人员聚焦于开发？.md
  
   - 06 - 代码入库到产品上线：Facebook如何使用CI-CD满足业务要求？.md
  
   - 07 - 分支管理：Facebook的策略，适合我的团队吗？.md
  
   - 08 - DevOps、SRE的共性：应用全栈思路打通开发和运维.md
  
   - 09 - 信息流通：让团队高效协同，让产品准确击中目标.md
  
   - 10 - 答疑篇：反对996并不是反对奋斗.md
  
   - 11 - 研发环境：Facebook怎样让开发人员不再操心环境？.md
  
   - 12 - 代码审查：哪种方式更适合我的团队？.md
  
   - 13 - 代码审查：学习Facebook真正发挥代码审查的提效作用.md
  
   - 14 - 质量与速度的均衡：让“唯快不破”快得更持久.md
  
   - 15 - 开源：从Phabricator的开源历程看开源利弊.md
  
   - 16 - 高效上云：如何用云计算来提高效能？.md
  
   - 17 - 测试左移：测试如何应对新的开发模式？.md
  
   - 18 - 蓝绿红黑灰度发布：这些五颜六色的发布到底怎么用？.md
  
   - 19 - 不再掉队，研发流程、工程方法趋势解读和展望.md
  
   - 20 - 答疑篇：如何平衡短期收益和长期收益？.md
  
   - 21 - 高效工作：Facebook的10x程序员效率心法.md
  
   - 22 - 深度工作：聚焦最有价值的事儿.md
  
   - 23 - 效率工具：选对用对才能事半功倍.md
  
   - 特别放送 - 每个开发人员都应该学一些VIM.md
  
   - 24 - VIM：如何高性价比地学习VIM的实用技巧？.md
  
   - 25 - 玩转Git：五种提高代码提交原子性的基本操作.md
  
   - 26 - Facebook怎样实现代码提交的原子性？.md
  
   - 27 - 命令行：不只是酷，更重要的是能提高个人效能.md
  
   - 28 - 从工作场景出发，寻找炫酷且有效的命令行工具.md
  
   - 29 -  1+1>2，灵活的工具组合及环境让你的工作效率翻倍.md
  
   - 30 - 答疑篇：关于价值导向和沟通.md
  
   - 31 - 业务目标和技术目标两手抓：怎样打造高效团队？.md
  
   - 32 - 从Netflix公开的著名PPT谈硅谷公司文化.md
  
   - 33 - Facebook企业文化：工程师文化是创造力引擎.md
  
   - 34 - Facebook工程师文化实践三大支柱之一做感兴趣的事.md
  
   - 35 - Facebook工程师文化实践三大支柱之二拥有信息和权限.md
  
   - 36 - Facebook工程师文化实践三大支柱之三绩效调节.md
  
   - 结束语 - 超越昨天的自己，享受成长的快乐.md
  
   - 结课测试 - 关于研发效率的这些知识，你都掌握了吗？.md
  