site_name: 苏杰的产品创新课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_人人都是产品经理吗_.md
  
   - 01_为什么每个人都要学产品创新课_.md
  
   - 02_四轮MVP框架导读_产品从无到有的创新，有通杀的法门吗_.md
  
   - 03_从理解用户开始_故事、生态、画像、旅程.md
  
   - 04_竞品生态_真正有效的竞品分析怎么做_.md
  
   - 05_打造属于你的点子过滤器.md
  
   - 06_Y模型_从问题域到方案域的最硬核解题思路.md
  
   - 07_用“原型”低成本验证_差个程序员，也可以做产品.md
  
   - 08_设计冲刺_谷歌创投如何帮助产品成功_.md
  
   - 09_产品服务系统_避免狭隘，再聊什么是产品.md
  
   - 10_好产品的评价标准_单一产品的两个维度.md
  
   - 11_习惯、启程、发现、精通_一个好产品的起步逻辑.md
  
   - 12_和用户一起成长_生命周期，不同阶段怎么运营.md
  
   - 13_真正的成功指标_用户数、收入等等都不是.md
  
   - 14_赚到钱只是结果_做出来和推出去的效率.md
  
   - 15_需求采集_各种方法怎么灵活应用.md
  
   - 16_KANO模型_雪中送炭与锦上添花.md
  
   - 17_产品进化案例_千岛湖啤酒的脑洞.md
  
   - 18_我的实践_这门“产品创新课”本身.md
  
   - 19_从产品到产品矩阵_可复用、能积累、善生死.md
  
   - 20_组织团队的支撑_面向未来，如何提升你的竞争力.md
  
   - 加餐_知识地图_学习产品创新的意义是什么_.md
  
   - 21_长大以后_从4轮到6轮MVP（M2V6P）.md
  
   - 22_步步为营_项目、产品、平台、生态.md
  
   - 23_痛苦抉择_从满足用户到“伤害”用户.md
  
   - 24_众里寻他_怎么找到合适的产品达人_.md
  
   - 25_借力打力_和产品达人做朋友.md
  
   - 26_养家糊口_商业模式=价值&#43;收入&#43;过程.md
  
   - 27_群策群力_组织效率，管理_沟通_协作_.md
  
   - 28_长期主义_从产品到职场、人生.md
  
   - 结束语_死亡是宇宙最伟大的发明.md
  
   - 结课测试_这些产品创新知识，你真的掌握了吗_.md
  