site_name: 重学前端

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 重学前端.md
  
   - 开篇词 - 从今天起，重新理解前端.md
  
   - 明确你的前端学习路线与方法.md
  
   - 列一份前端知识架构图.md
  
   - JavaScript类型：关于类型，有哪些你不知道的细节？.md
  
   - JavaScript对象：面向对象还是基于对象？.md
  
   - JavaScript对象：我们真的需要模拟类吗？.md
  
   - JavaScript对象：你知道全部的对象分类吗？.md
  
   - JavaScript执行（一）：Promise里的代码为什么比setTimeout先执行？.md
  
   - JavaScript执行（二）：闭包和执行上下文到底是怎么回事？.md
  
   - JavaScript执行（三）：你知道现在有多少种函数吗？.md
  
   - JavaScript执行（四）：try里面放return，finally还会执行吗？.md
  
   - JavaScript词法：为什么12.toString会报错？.md
  
   - （小实验）理解编译原理：一个四则运算的解释器.md
  
   - JavaScript语法（预备篇）：到底要不要写分号呢？.md
  
   - JavaScript语法（一）：在script标签写export为什么会抛错？.md
  
   - JavaScript语法（二）：你知道哪些JavaScript语句？.md
  
   - JavaScript语法（三）：什么是表达式语句？.md
  
   - JavaScript语法（四）：新加入的**运算符，哪里有些不一样呢？.md
  
   - HTML语义：div和span不是够用了吗？.md
  
   - HTML语义：如何运用语义类标签来呈现Wiki网页？.md
  
   - CSS语法：除了属性和选择器，你还需要知道这些带@的规则.md
  
   - HTML元信息类标签：你知道head里一共能写哪几种标签吗？.md
  
   - CSS 选择器：如何选中svg里的a元素？.md
  
   - CSS选择器：伪元素是怎么回事儿？.md
  
   - HTML链接：除了a标签，还有哪些标签叫链接？.md
  
   - CSS排版：从毕昇开始，我们就开始用正常流了.md
  
   - HTML替换型元素：为什么link一个CSS要用href，而引入js要用src呢？.md
  
   - HTML小实验：用代码分析HTML标准.md
  
   - CSS Flex排版：为什么垂直居中这么难？.md
  
   - CSS动画与交互：为什么动画要用贝塞尔曲线这么奇怪的东西？.md
  
   - HTML语言：DTD到底是什么？.md
  
   - CSS渲染：CSS是如何绘制颜色的？.md
  
   - CSS小实验：动手做，用代码挖掘CSS属性.md
  
   - HTML·ARIA：可访问性是只给盲人用的特性么？.md
  
   - 浏览器：一个浏览器是如何工作的？（阶段一）.md
  
   - 浏览器：一个浏览器是如何工作的？（阶段二）.md
  
   - 浏览器：一个浏览器是如何工作的（阶段三）.md
  
   - 浏览器：一个浏览器是如何工作的？（阶段四）.md
  
   - 浏览器：一个浏览器是如何工作的？（阶段五）.md
  
   - 浏览器DOM：你知道HTML的节点有哪几种吗？.md
  
   - 浏览器CSSOM：如何获取一个元素的准确位置.md
  
   - 浏览器事件：为什么会有捕获过程和冒泡过程？.md
  
   - 浏览器API（小实验）：动手整理全部API.md
  
   - 性能：前端的性能到底对业务数据有多大的影响？.md
  
   - 工具链：什么样的工具链才能提升团队效率？.md
  
   - 持续集成：几十个前端一起工作，如何保证工作质量？.md
  
   - 搭建系统：大量的低价值需求应该如何应对？.md
  
   - 前端架构：前端架构有哪些核心问题？.md
  
   - 新年彩蛋 - 2019，有哪些前端技术值得关注？.md
  
   - 用户故事 - 那些你与“重学前端”的不解之缘.md
  
   - 期中答疑 - name(){}与name： function() {}，两种写法有什么区别吗？.md
  
   - 答疑加餐 - 学了这么多前端的“小众”知识，到底对我有什么帮助？.md
  
   - 加餐 - 前端与图形学.md
  
   - 加餐 - 前端交互基础设施的建设.md
  
   - 期末答疑（一）：前端代码单元测试怎么做？.md
  
   - 期末答疑（二）：前端架构中，每个逻辑页面如何可以做到独立发布呢？.md
  
   - 尾声 - 长风破浪会有时，直挂云帆济沧海.md
  