site_name: 系统性能调优必知必会

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 系统性能调优必知必会.md
  
   - 开篇词 - 万变不离其宗，性能优化也有章可循.md
  
   - 01 - CPU缓存：怎样写代码能够让CPU执行得更快？.md
  
   - 02 - 内存池：如何提升内存分配的效率？.md
  
   - 03 - 索引：如何用哈希表管理亿级对象？.md
  
   - 04 - 零拷贝：如何高效地传输文件？.md
  
   - 05 - 协程：如何快速地实现高并发服务？.md
  
   - 06 - 锁：如何根据业务场景选择合适的锁？.md
  
   - 07 - 性能好，效率高的一对多通讯该如何实现？.md
  
   - 08 - 事件驱动：C10M是如何实现的？.md
  
   - 09 - 如何提升TCP三次握手的性能？.md
  
   - 10 - 如何提升TCP四次挥手的性能？.md
  
   - 11 - 如何修改TCP缓冲区才能兼顾并发数量与传输速度？.md
  
   - 12 - 如何调整TCP拥塞控制的性能？.md
  
   - 13 - 实战：单机如何实现管理百万主机的心跳服务？.md
  
   - 14 - 优化TLS-SSL性能该从何下手？.md
  
   - 15 - 如何提升HTTP-1.1性能？.md
  
   - 16 - HTTP-2是怎样提升性能的？.md
  
   - 17 - Protobuf是如何进一步提高编码效率的？.md
  
   - 18 - 如何通过gRPC实现高效远程过程调用？.md
  
   - 期中考试-行至半程，你的收获如何呢？.md
  
   - 加餐1-特别福利：陶辉视频课精选.md
  
   - 加餐2 -答疑精选：这些问题你都清楚吗？.md
  
   - 19 - 如何通过监控找到性能瓶颈？.md
  
   - 20 - CAP理论：怎样舍弃一致性去换取性能？.md
  
   - 21 - AKF立方体：怎样通过可扩展性来提高性能？.md
  
   - 22 - NWR算法：如何修改读写模型以提升性能？.md
  
   - 23 - 负载均衡：选择Nginx还是OpenResty？.md
  
   - 24 - 一致性哈希：如何高效地均衡负载？.md
  
   - 25 - 过期缓存：如何防止缓存被流量打穿？.md
  
   - 26 - 应用层多播：如何快速地分发内容？.md
  
   - 27 - 消息队列：如何基于异步消息提升性能？.md
  
   - 28 - MapReduce：如何通过集群实现离线计算？.md
  
   - 29 - 流式计算：如何通过集群实现实时计算？.md
  
   - 30 - 如何权衡关系数据库与NoSQL数据库？.md
  
   - 加餐3 - 大厂面试到底在考些什么？.md
  
   - 大咖助场1 - 李玥：高并发场景下如何优化微服务的性能？.md
  
   - 大咖助场2-庄振运：与程序员相关的SSD性能知识.md
  
   - 加餐4-百万并发下Nginx的优化之道.md
  
   - 大咖助场3-傅健：那些年，影响我们达到性能巅峰的常见绊脚石（上）.md
  
   - 大咖助场4-傅健：那些年，影响我们达到性能巅峰的常见绊脚石（下）.md
  
   - 加餐5 - 如何理解分布式系统？.md
  
   - 加餐6-分布式系统的本质是什么？.md
  
   - 加餐7-深入剖析HTTP-3协议.md
  
   - 结束语 - 从业 IT 20年后，我将最看重什么？.md
  
   - 来领奖啦！你填写毕业问卷了吗？.md
  
   - 毕业问卷获奖用户名单.md
  
   - 期末测试-对于性能优化，你掌握了多少呢？.md
  