site_name: 零基础入门Spark

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra_css:
  - static/css/extra.css

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright &copy; 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 开篇词_入门Spark，你需要学会“三步走”.md
  
   - 01｜Spark_从“大数据的HelloWorld”开始.md
  
   - 02_RDD与编程模型_延迟计算是怎么回事_.md
  
   - 03_RDD常用算子（一）_RDD内部的数据转换.md
  
   - 04_进程模型与分布式部署_分布式计算是怎么回事_.md
  
   - 05_调度系统_如何把握分布式计算的精髓_.md
  
   - 06_Shuffle管理_为什么Shuffle是性能瓶颈_.md
  
   - 07_RDD常用算子（二）_Spark如何实现数据聚合_.md
  
   - 08_内存管理_Spark如何使用内存_.md
  
   - 09_RDD常用算子（三）_数据的准备、重分布与持久化.md
  
   - 10_广播变量&amp;amp;累加器_共享变量是用来做什么的_.md
  
   - 11_存储系统_数据到底都存哪儿了_.md
  
   - 12_基础配置详解_哪些参数会影响应用程序稳定性_.md
  
   - 13_SparkSQL_让我们从“小汽车摇号分析”开始.md
  
   - 14_台前幕后_DataFrame与SparkSQL的由来.md
  
   - 15_数据源与数据格式_DataFrame从何而来_.md
  
   - 16_数据转换_如何在DataFrame之上做数据处理_.md
  
   - 17_数据关联_不同的关联形式与实现机制该怎么选_.md
  
   - 18_数据关联优化_都有哪些Join策略，开发者该如何取舍_.md
  
   - 19_配置项详解_哪些参数会影响应用程序执行性能_.md
  
   - 20_Hive&#43;Spark强强联合_分布式数仓的不二之选.md
  
   - 21｜SparkUI（上）_如何高效地定位性能问题_.md
  
   - 22｜SparkUI（下）_如何高效地定位性能问题_.md
  
   - 23_SparkMLlib_从“房价预测”开始.md
  
   - 24_特征工程（上）_有哪些常用的特征处理函数_.md
  
   - 25_特征工程（下）_有哪些常用的特征处理函数_.md
  
   - 26_模型训练（上）_决策树系列算法详解.md
  
   - 27_模型训练（中）_回归、分类和聚类算法详解.md
  
   - 28_模型训练（下）_协同过滤与频繁项集算法详解.md
  
   - 29_SparkMLlibPipeline_高效开发机器学习应用.md
  
   - 30｜StructuredStreaming_从“流动的WordCount”开始.md
  
   - 31｜新一代流处理框架_Batchmode和Continuousmode哪家强_.md
  
   - 32｜Window操作&amp;amp;Watermark_流处理引擎提供了哪些优秀机制_.md
  
   - 33｜流计算中的数据关联_流与流、流与批.md
  
   - 34｜Spark&#43;Kafka_流计算中的“万金油”.md
  
   - 用户故事_小王_保持空杯心态，不做井底之蛙.md
  
   - 结束语_进入时间裂缝，持续学习.md
  
   - 期末测试｜来赴一场100分之约！.md
  