site_name: 如何落地业务建模

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 如何落地业务建模.md
  
   - 开篇词-为什么你需要学习业务建模？.md
  
   - 01-领域驱动设计到底在讲什么？.md
  
   - 02-统一语言是必要的吗？.md
  
   - 03-我们要怎么理解领域驱动设计？.md
  
   - 04-跨越现实的障碍（上）：要性能还是要模型？.md
  
   - 05-跨越现实的障碍（中）：富含知识还是代码坏味道？.md
  
   - 06 - 跨越现实的障碍（下）：架构分层就对了吗？.md
  
   - 07-统一语言可以是领域模型本身吗？.md
  
   - 08 - 什么办法可以在讨论中自然形成统一语言？.md
  
   - 09-怎么才能更有效地获得事件流？.md
  
   - 10 - 将模型实现为RESTful API（上）.md
  
   - 11-将模型实现为RESTful API（下）.md
  
   - 说点题外话01-好耦和与坏耦和.md
  
   - 说点题外话02-模式并不是解决方案.md
  
   - 说点题外话03-银弹可以杀死狼人，但你怎么知道狼人不是你呢？.md
  
   - 说点题外话04-面向对象的原则适用于RESTful API吗？.md
  
   - 12-云时代的挑战（上）：弹性边界还是业务边界？.md
  
   - 13-云时代的挑战（下）：如何保持弹性边界的独立性？.md
  
   - 14 - 8X Flow（上）：何为业务？何为领域？.md
  
   - 15-8X Flow（中）：如何通过模型发现业务系统的变化点？.md
  
   - 16-8X Flow（下）：多于一个例子.md
  
   - 17-中台建模（上）：到底什么是中台？.md
  
   - 18-中台建模（下）：如何寻找可复用的业务模式？.md
  
   - 19-如何将模型实现为微服务？.md
  
   - 20-云时代的下一站：SaaS化与魔球建模法.md
  
   - 结课测试题-这些业务建模知识你都掌握了吗？.md
  
   - 结束语-吃喝玩乐如何让我成为更好的程序员？.md
  
   - 编辑手记01-写给专栏读者的一封小信.md
  
   - 用户故事01-知瑕：如何通过刻意练习，掌握建模方法？.md
  
   - 用户故事02-邹海龙：大道千条，我选其一.md
  
   - 直播加餐01-如何使用8X Flow实施面向业务设计？.md
  
   - 直播加餐02-如何使用Smart Domain实现DDD？.md
  