site_name: To B市场品牌实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - To B市场品牌实战课.md
  
   - 开篇词 - 成为下一个万亿市场风口上的操盘人.md
  
   - 01 - To B市场营销到底是做什么的？.md
  
   - 02 - To B消费心理学：如何把握客户CEO心理，让他买单？.md
  
   - 03 - 第一印象（上）：如何策划一场产品发布会？.md
  
   - 04 - 第一印象（下）：如何策划一场产品发布会？.md
  
   - 05 - Leads：如何成体系地寻找高质量的Leads？.md
  
   - 06 - 案例：怎样0成本把一个新产品的市场认知率做到76%？.md
  
   - 07 - 产品世界观：如何构建一个好的对外产品故事体系？.md
  
   - 08 - 口碑：如何打造一个有影响力的Demo？.md
  
   - 09 - 后疫情时代，如何做To B市场品牌内容的线上转型？.md
  
   - 10 - 如何用“周边”产品构建To B影响力？.md
  
   - 11 - 打造案例（上）：如何做优质客户案例的选型和内容构造？.md
  
   - 12 - 打造案例（中）：如何引发现象级讨论，打赢PR战役？.md
  
   - 13 - 打造案例（下）：如何通过营销战役把商机转化为销量？.md
  
   - 14 - 颜值美学：如何体现To B产品营销的设计感？.md
  
   - 15 - 如何给企业讲一个“降本”的故事？.md
  
   - 16-如何给企业讲一个“增效”的故事？.md
  
   - 17-市场中的禁忌：To B营销中容易犯哪些错误？.md
  
   - 18 - To B营销的阵地：我们在哪里说话，也很重要.md
  
   - To B会客厅-SDR是如何优化线索跟进策略，提升销售效能的？.md
  
   - To B会客厅-如何通过整体营销迎接后疫情时代的市场挑战？.md
  
   - 结束语 - 一个To B的市场人应该具备怎样的特质？.md
  