site_name: Linux性能优化实战

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - Linux性能优化实战.md
  
   - 开篇词 - 别再让Linux性能问题成为你的绊脚石.md
  
   - 01 - 如何学习Linux性能优化？.md
  
   - 02 - 基础篇：到底应该怎么理解“平均负载”？.md
  
   - 03 - 基础篇：经常说的 CPU 上下文切换是什么意思？（上）.md
  
   - 04 - 基础篇：经常说的 CPU 上下文切换是什么意思？（下）.md
  
   - 05 - 基础篇：某个应用的CPU使用率居然达到100%，我该怎么办？.md
  
   - 06 - 案例篇：系统的 CPU 使用率很高，但为啥却找不到高 CPU 的应用？.md
  
   - 07 - 案例篇：系统中出现大量不可中断进程和僵尸进程怎么办？（上）.md
  
   - 08 - 案例篇：系统中出现大量不可中断进程和僵尸进程怎么办？（下）.md
  
   - 09 - 基础篇：怎么理解Linux软中断？.md
  
   - 10 - 案例篇：系统的软中断CPU使用率升高，我该怎么办？.md
  
   - 11 - 套路篇：如何迅速分析出系统CPU的瓶颈在哪里？.md
  
   - 12 - 套路篇：CPU 性能优化的几个思路.md
  
   - 13 - 答疑（一）：无法模拟出 RES 中断的问题，怎么办？.md
  
   - 14 - 答疑（二）：如何用perf工具分析Java程序？.md
  
   - 15 - 基础篇：Linux内存是怎么工作的？.md
  
   - 16 - 基础篇：怎么理解内存中的Buffer和Cache？.md
  
   - 17 - 案例篇：如何利用系统缓存优化程序的运行效率？.md
  
   - 18 - 案例篇：内存泄漏了，我该如何定位和处理？.md
  
   - 19 - 案例篇：为什么系统的Swap变高了（上）.md
  
   - 20 - 案例篇：为什么系统的Swap变高了？（下）.md
  
   - 21 - 套路篇：如何“快准狠”找到系统内存的问题？.md
  
   - 22 - 答疑（三）：文件系统与磁盘的区别是什么？.md
  
   - 23 - 基础篇：Linux 文件系统是怎么工作的？.md
  
   - 24 - 基础篇：Linux 磁盘I-O是怎么工作的（上）.md
  
   - 25 - 基础篇：Linux 磁盘I-O是怎么工作的（下）.md
  
   - 26 - 案例篇：如何找出狂打日志的“内鬼”？.md
  
   - 27 - 案例篇：为什么我的磁盘I-O延迟很高？.md
  
   - 28 - 案例篇：一个SQL查询要15秒，这是怎么回事？.md
  
   - 29 - 案例篇：Redis响应严重延迟，如何解决？.md
  
   - 30 - 套路篇：如何迅速分析出系统I-O的瓶颈在哪里？.md
  
   - 31 - 套路篇：磁盘 I-O 性能优化的几个思路.md
  
   - 32 - 答疑（四）：阻塞、非阻塞 I-O 与同步、异步 I-O 的区别和联系.md
  
   - 33 - 关于 Linux 网络，你必须知道这些（上）.md
  
   - 34 - 关于 Linux 网络，你必须知道这些（下）.md
  
   - 35 - 基础篇：C10K 和 C1000K 回顾.md
  
   - 36 - 套路篇：怎么评估系统的网络性能？.md
  
   - 37 - 案例篇：DNS 解析时快时慢，我该怎么办？.md
  
   - 38 - 案例篇：怎么使用 tcpdump 和 Wireshark 分析网络流量？.md
  
   - 39 - 案例篇：怎么缓解 DDoS 攻击带来的性能下降问题？.md
  
   - 40 - 案例篇：网络请求延迟变大了，我该怎么办？.md
  
   - 41 - 案例篇：如何优化 NAT 性能？（上）.md
  
   - 42 - 案例篇：如何优化 NAT 性能？（下）.md
  
   - 43 - 套路篇：网络性能优化的几个思路（上）.md
  
   - 44 - 套路篇：网络性能优化的几个思路（下）.md
  
   - 45 - 答疑（五）：网络收发过程中，缓冲区位置在哪里？.md
  
   - 46 - 案例篇：为什么应用容器化后，启动慢了很多？.md
  
   - 47 - 案例篇：服务器总是时不时丢包，我该怎么办？（上）.md
  
   - 48 - 案例篇：服务器总是时不时丢包，我该怎么办？（下）.md
  
   - 49 - 案例篇：内核线程 CPU 利用率太高，我该怎么办？.md
  
   - 50 - 案例篇：动态追踪怎么用？（上）.md
  
   - 51 - 案例篇：动态追踪怎么用？（下）.md
  
   - 52 - 案例篇：服务吞吐量下降很厉害，怎么分析？.md
  
   - 53 - 套路篇：系统监控的综合思路.md
  
   - 54 - 套路篇：应用监控的一般思路.md
  
   - 55 - 套路篇：分析性能问题的一般步骤.md
  
   - 56 - 套路篇：优化性能问题的一般方法.md
  
   - 57 - 套路篇：Linux 性能工具速查.md
  
   - 58 - 答疑（六）：容器冷启动如何性能分析？.md
  
   - 加餐（一） - 书单推荐：性能优化和Linux 系统原理.md
  
   - 加餐（二） - 书单推荐：网络原理和 Linux 内核实现.md
  
   - 用户故事 - “半路出家 ”，也要顺利拿下性能优化！.md
  
   - 用户故事 - 运维和开发工程师们怎么说？.md
  
   - 结束语 - 愿你攻克性能难关.md
  
   - 结课测试-这些Linux性能知识你都掌握了吗？.md
  